### ISSUE TITLE
[4.0] Use envelope Endpoint

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-ruby#1062]
The new SDK should only send envelopes vs. send events `/store/`.

https://develop.sentry.dev/sdk/envelopes/

So we should only send things to `/envelopes/`, we can even discontinue the `send_event` function on the Transport and only have `send_envelope`.

So we need to intro a `Envelope` class with a few helpers:

```ruby
env = Envelope::from_event()

env = Envelope::from_transaction()
```

**Comment by st0012** [comment]
@HazAT When I send events with a large amount of contextual data, like with many breadcrumbs or backtraces, I get `413` from the Sentry. I guess this means I need to compress & encode the event item like the current transport does for the `/store` endpoint. So I did and Sentry responded with `200`, but the event never showed up on the list. 

This is one of the compressed payloads I sent:

```
{"event_id":"592c33dfefbe4e79b656cd533a4d7369","dsn":"https://2fb45f003d054a7ea47feb45898f7649@o447951.ingest.sentry.io/5434472","sdk":{"name":"sentry.ruby","version":"0.1.0"},"sent_at":"2020-10-25T21:22:09+08:00"}
{"type":"event","content_type":"application/octet-stream"}
eJztfQ1z27ay9l9B7JlGzpWoD3/rNE1cx218mjQ+ttPb89oeDkVCEmOKVEjKH0l8f/u7uwBJkKJEKollOZWn04ggCCywDxaLxWL
xeYVfcTfUbWulvbK52zLX160u73b4Bt/e7WxtbpnW5vq6sWFtr2/trlRXHMjuQFbu+54Pz6E94EFoDIaQ1mq0GrVmo9baZM31d
qvVbuyy96f7kMvsc/MyGA0gEzxx98r2PXcA9UKChSV6Q3qqrgTcv+K+7hoDDu/eGuavnndZO/K9WgveDjxr5PBgpf15xTcuMU
dzXWtoTazCc82R70MpNX/UucVXWlPbhjd2c8elxx1tE8uwXTsEmrG9WnNDw3LDvs8NSw+MLpbZ0Na1LUz9ZLtdjz5tUUmfu
B1ec/8S26ptaA1IMszQvuLBaDj0fCxyS8Ov1+FNZ2Q7FvchbR0+38B2A2E2FbdL3yIlOn5nO7yllOl6l17P9kXWJjQPE33DdoKa5
Q1qSLzt9uiDBlVl+kYQUO4GEe54XtfoU4ZtLfm4Hw6cWmBA8+1PRFg # and more
```

And here are my questions:
1. If encoded event payload is not acceptable, shouldn't I get a `4xx` response?
2. If the event payload must be in the json format, does it mean I need to trim down some data before sending it?

**Comment by st0012** [comment]
Close via #1079 and #1081
