### ISSUE TITLE
Configurations for ActiveJob integrations

### ISSUE THREAD

**Issue by tvec** [getsentry/sentry-ruby#1107]
Is there a way to configure Sentry's ActiveJob integration to update the list of adapters seen in `ALREADY_SUPPORTED_SENTRY_ADAPTERS`? Alternatively, are there a ways of just skipping this integration completely?

Our use case is we have a custom QueueAdapter not in that list. Currently, it gets picked up by `capture_and_reraise_with_sentry` in `ActiveJobExtensions`. However, we want to skip that and just use the existing Sidekiq integration.

Is this possible? Thanks!

**Comment by st0012** [comment]
unfortunately, it's not possible in both old and new SDKs. but I understand how helpful it'd be if it's configurable. so I may introduce it in the new SDK in the future.
