### ISSUE TITLE
Reported User IP shows local IP address instead of the real one

### ISSUE THREAD

**Issue by vojtad** [getsentry/sentry-ruby#1121]
**Describe the bug**
All tracked events sent from Heroku show Heroku local IP sent in `REMOTE_ADDR` instead of the real IP sent in `X-Forwarded-For` HTTP header.

Heroku uses local IP from `10.0.0.0/8` range which is filtered according to current `sentry-raven` code and the real IP from `X-Forwarded-For` should be used.

I tested `Raven::Utils::RealIp` used for filtering IPs manually by creating it with IPs from one of the reported events and it worked like it was supposed to. `Raven::Utils::RealIp#calculate_ip` returned the IP from `X-Forwarded-For` HTTP header.

**To Reproduce**
Install `sentry-raven` on Heroku and raise an exception during a request. When it is reported to Sentry User IP will be the local one from Heroku.

**Expected behavior**
User IP should be the one reported in `X-Forwarded-For` HTTP header.

**Actual behavior**
User IP shows local IP reported in `REMOTE_ADDR`.

**Environment**
 - Ruby Version: ruby 2.6.6
 - SDK Version: sentry-raven 2.13.0
 - rails 6.0.2.1

**Raven Config**

Content of our `sentry.rb` intializer.

```ruby
# frozen_string_literal: true

SENTRY_IGNORED_EXCEPTIONS = {
  SilentError => true,
  ApplicationJob::RescheduleException => true
}.freeze

Raven.configure do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
  config.should_capture = proc do |e|
    if SENTRY_IGNORED_EXCEPTIONS[e.class].respond_to?(:call)
      !SENTRY_IGNORED_EXCEPTIONS[e.class].call(e)
    elsif SENTRY_IGNORED_EXCEPTIONS[e.class].is_a?(TrueClass)
      false
    else
      true
    end
  end
  config.processors -= [Raven::Processor::PostData]
end

Raven.inject if Rails.env.production?
```

**Comment by st0012** [comment]
I think this issue has been addressed in the new `sentry-ruby` SDK but we don't plan to backport it to `sentry-raven` atm. I recommend you follow [the migration guide](https://docs.sentry.io/platforms/ruby/migration/) for migrating to the new SDK 🙂
