### ISSUE TITLE
Add sentry-delayed_job

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1129]

**Comment by booleanbetrayal** [comment]
Are there any updates to the status of `sentry-delayed_job`? It's currently blocking our adoption of the new `sentry-ruby` migration. Thanks for any info in advance!

**Comment by st0012** [comment]
I'll try to make a beta version of it in the upcoming weekend 🙂

**Comment by dan-jensen** [comment]
@st0012 would you mind elaborating in the issue description?  I'm just not sure what this issue represents.

According to the [Sentry documentation](https://docs.sentry.io/clients/ruby/configuration/integrations/): "For common environments and frameworks like Rails, Rack, and others [including DelayedJob], we provide automatic integration for reporting."  But after upgrading from `sentry-raven` to `sentry-ruby`, I've found that exceptions raised in the DelayedJob context are NOT being reported to Sentry.  Does this issue capture the reason why?

**Comment by st0012** [comment]
the document you point to is for the old `sentry-raven` SDK. the new `sentry-ruby` currently doesn't support capturing errors in `DelayedJob` because the integration gem `sentry-delayed_job` is still a work in progress (which is what this issue is for).

**Comment by dan-jensen** [comment]
@st0012 you are awesome – thank you for the explanation, and even more for PR #1273  🙇

**Comment by st0012** [comment]
I've added the gem in #1273. I think it should be working now, but I want to gather some feedback before releasing it. can anyone give it a try and tell me what can be improved 🙂 

you can install it with

```ruby
gem "sentry-delayed_job", github: "getsentry/sentry-ruby", branch: "sentry-delayed_job"
```

**Comment by dan-jensen** [comment]
@st0012 just followed your instructions and it's working in Rails 6.1.1 on Ruby 2.6.3.  (Specifically, it's calling Sentry.capture_exception when an exception is raised in the DelayedJob context.)  No deprecation warnings either.  Nicely done, thanks so much!  🎉

**Comment by st0012** [comment]
sorry for the long-waiting everyone, we've just released `sentry-delayed_job` yesterday 😄 
although it relies on `sentry-ruby 4.2.0`, `4.2.0` doesn't require any extra setup compared with migrating to `4.0`.
