### ISSUE TITLE
Re-Add client-side data scrubbing

### ISSUE THREAD

**Issue by sriedel** [getsentry/sentry-ruby#1133]
The ability to scrub sentitive data on the client side seems to have been removed with version 4. 

Wanting to have access to a request bodies data in an excception report, while not transmitting PII to the server is important to us. Scrubbing data server side before persisting would still entail transmitting PII to the server.

I've had a look at the before_send callback code, however the Event instance does not expose the @request, where @request.data seems to be the place where request body data is stored. So this does not seem to be a viable alternative to Ravens Processor classes.

**Comment by st0012** [comment]
removing client-side data scrubbing is a policy for all SDKs, so we won't add it back again. instead, I'll expose `Event`'s interface attributes in #1135  so you can access them in the `before_send` callback, for example:

```ruby
config.before_send = lambda do |event, hint|
  event.request.data = process_request_data(event.request.data)
  event
end
```

**Comment by sriedel** [comment]
That would be great, thanks.

**Comment by st0012** [comment]
closing because of #1135

**Comment by RobinDaugherty** [comment]
The `before_send` snippet above is now in the documentation. But it fails in many cases (when an event has no `request` or the request doesn't respond to `data`). And when it fails, it silently swallows the error. No error is logged, and `last_event_id` returns an ID as if it worked.

**Comment by st0012** [comment]
@RobinDaugherty thanks for reporting this. I've added https://github.com/getsentry/sentry-ruby/issues/1289 to log the failed `before_send` calls.
