### ISSUE TITLE
Re-Add Rake integration

### ISSUE THREAD

**Issue by sriedel** [getsentry/sentry-ruby#1134]
Version 4.0 of the gem seems to have removed ravens rake integration. The migration documentation doesn't mention this integration at all and I can't find any appropriate code in the sentry-ruby gem, nor a sentry-rake gem.  Having a lot of complex rake tasks would make it very helpful to have a centralized rake integration.

**Comment by st0012** [comment]
what rake integrations did you use with `sentry-raven`? also can you provide a few examples on how a rake integration would be helpful?

**Comment by sriedel** [comment]
Yes, thats it.

**Comment by st0012** [comment]
@sriedel added in #1137

**Comment by mario-amazing** [comment]
@st0012, could you help me to configure sentry in rails -> rake tasks?
My current config doesn't work:
```ruby
require_relative 'config/application'
require "sentry-ruby"

Sentry.init do |config|
  config.dsn = DSN
end

Rails.application.load_tasks
```

**Comment by mario-amazing** [comment]
@st0012, could you help me to configure sentry in rails -> rake tasks?
My current config doesn't work:
```ruby
require_relative 'config/application'
require "sentry-ruby"

Sentry.init do |config|
  config.dsn = DSN
end

Rails.application.load_tasks
```
