### ISSUE TITLE
Uncaught exceptions

### ISSUE THREAD

**Issue by rainerborene** [getsentry/sentry-ruby#114]
I'm not sure If this bug is related to the `raven-ruby` library but some exceptions like `NoMethodError` on the view layer is not being handled by `raven-ruby` in some way. By the way, I'm using the slim template language.

Rails middleware stack on production environment:

> use Raven::Rack
> use Rack::Cache
> use ActionDispatch::Static
> use Rack::Lock
> use Rack::Runtime
> use Rack::MethodOverride
> use RemoteVote
> use ActionDispatch::RequestId
> use Rails::Rack::Logger
> use ActionDispatch::ShowExceptions
> use ActionDispatch::DebugExceptions
> use BetterErrors::Middleware
> use ActionDispatch::RemoteIp
> use ActionDispatch::Reloader
> use ActionDispatch::Callbacks
> use ActiveRecord::ConnectionAdapters::ConnectionManagement
> use ActiveRecord::QueryCache
> use ActionDispatch::Cookies
> use ActionDispatch::Session::CookieStore
> use ActionDispatch::Flash
> use ActionDispatch::Head
> use Rack::ConditionalGet
> use Rack::ETag
> use ActionDispatch::BestStandardsSupport
> use Warden::Manager
> use NewRelic::Rack::DeveloperMode
> use NewRelic::Rack::DeveloperMode
> use NewRelic::Rack::AgentHooks
> use NewRelic::Rack::ErrorCollector
> use OmniAuth::Strategies::Facebook
> run Example::Application.routes

**Comment by fwuensche** [comment]
If you too are missing exceptions such as: 

```
** [Raven] User excluded error: #<ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound
```

To remove all default filtered error classes, you can change your config to: 

```
Sentry.init do |config|
  config.excluded_exceptions = []
end
```
