### ISSUE TITLE
sentry-ruby raises exceptions when Rails/Rake processes run in Rails 6.1.0

### ISSUE THREAD

**Issue by geoffharcourt** [getsentry/sentry-ruby#1145]
**Describe the bug**

Our application is currently running Rails 6.0.3.4 and sentry-ruby 4.0.1. When we try to update to Rails 6.1.0, almost all of our processes fail to start with what looks like a Sentry error:

```
rake aborted!
NoMethodError: undefined method `current_client' for nil:NilClass.
```

If we remove `sentry-ruby` the application and test processes (mostly started by `rake`) are able to start. The backtrace is longer with sentry-ruby 4.0.1 than 4.0.0, but it's the same exception. We're unable to run `rake`, or `rspec`.

**To Reproduce**

1. Generate a Rails 6.1 app with `rails new proof_of_concept`
2. Add `gem "sentry-ruby", "4.0.1"` to the Gemfile and run `bundle install`
3. Run any Rake command such as `bundle exec rake routes` or bundle exec rake notes`

**Expected behavior**

Rake tasks should be able to execute.

**Actual behavior**

An exception is raised.

**Environment**
 - Ruby Version: 2.6.6
 - SDK Version: 4.0.1
 - Integration Versions (if any): sentry-rails 4.0.0, sentry-sidekiq 4.0.0. We are able to produce these exceptions without the integrations so we do not believe they are the cause

**Raven Config**

These exceptions occur with no further configuration, but here's our application's Sentry initializer:

```ruby
Sentry.init do |config|
  config.dsn = ENV["RAVEN_DSN"]
  config.excluded_exceptions += [
    "ActionController::RoutingError",
    "ActionController::UnknownHttpMethod",
    "Mime::Type::InvalidMimeType",
    "Puma::HttpParserError",
    "Sidekiq::Limiter::OverLimit",
    "Rack::QueryParser::InvalidParameterError",
  ]

  if ENV["SENTRY_ENVIRONMENT"] == "staging"
    config.excluded_exceptions += ["PG::ConnectionBad", "PG::Error"]
  end

  config.environment = ENV["SENTRY_ENVIRONMENT"] ||
    ENV["HEROKU_APP_NAME"] ||
    ENV["RAILS_ENV"]
end

```

**Comment by st0012** [comment]
@geoffharcourt thanks for reporting. just to confirm: so this issue only happens with Rails 6.1?

**Comment by geoffharcourt** [comment]
@st0012 that's correct. We've been using `sentry-ruby` with `6.0.3.4` more or less since it was publicly announced without issue.

**Comment by st0012** [comment]
@geoffharcourt thanks! I suspect Rails 6.1 skips loading initializers for some core rake tasks (like `rake routes`), so the SDK is not initialized at all when running them, which then caused this issue. but I'll do more research on that, will get back to you in a few days.

**Comment by jiz4oh** [comment]
> @geoffharcourt thanks for reporting. just to confirm: so this issue only happens with Rails 6.1?

I use rails 5.2.0 and sentry-ruby 4.0.1. It's the same error.

**Comment by st0012** [comment]
@geoffharcourt just a fyi: in Rails 6.1 they have removed `rake routes` so we need to use `rails routes` for proper testing.
