### ISSUE TITLE
Events are created even DSN config absent

### ISSUE THREAD

**Issue by nicolas-brousse** [getsentry/sentry-ruby#1152]
**Describe the bug**
I upgraded to new Sentry clients on our Rails application. I really like the new approach and new features.

We use an ActiveJob to send Sentry events. And since we upgraded I notice that in development environment (without `SENTRY_DSN` present) jobs are created.

With previous client, we didn't have this behavior.

**To Reproduce**
Send Sentry event with an `ActiveJob`.

**Expected behavior**
Having Sentry not to try pushing event before `Sentry#send_event`. And so not creating useless jobs, since `Sentry#send_event` stop at its first line.

**Actual behavior**
All events and transactions are created and pushing to a job, even Sentry DSN not specified.

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: `sentry-ruby 4.0.1`
 - Integration Versions (if any):`sentry-rails 4.0.0` and `sentry-sidekiq 4.0.0`
 - Rails 6.0, Sidekiq 6.1.2

**Raven Config**

```ruby
Sentry.init do |config|
  config.traces_sample_rate = 0.5
  config.release = ENV["HEROKU_SLUG_COMMIT"]
  config.async = ->(event) { ErrorsTracker::SendEventJob.perform_later(event) }
  config.breadcrumbs_logger = %i[sentry_logger active_support_logger]
end
```

**Comment by st0012** [comment]
thanks for reporting! I've added #1156 to fix this issue 😄
