### ISSUE TITLE
sentry-sidekiq gem swallows exceptions, preventing worker retries

### ISSUE THREAD

**Issue by jackrr** [getsentry/sentry-ruby#1173]
**Describe the bug**

After installing the `sentry-sidekiq` gem, jobs that raise exceptions are not added to the retry queue.

**To Reproduce**

Add the `sentry-sidekiq` gem to a runtime using `sidekiq`. Raise some exception in your worker's `perform` method.

**Expected behavior**

The raised exception appears in sentry and the job is added to the retry queue.

**Actual behavior**

The raised exception appears in sentry, but the job is considered "processed" and not retried.

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: 4.1.1
 - Integration Versions (if any):
  - Rails 6.0.3.4
  - Sidekiq 6.1.2

**Sentry Config**

```ruby
Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.breadcrumbs_logger = [:active_support_logger, :sentry_logger]
  config.environment = ENV.fetch('SENTRY_ENV', Rails.env)
  config.release = ENV['BUILD_VERSION']

  # To activate performance monitoring, set one of these options.
  # We recommend adjusting the value in production:
  # config.traces_sample_rate = 0.5
  # or
  # config.traces_sampler = lambda do |context|
  #   true
  # end
end
```

I've gotten around the issue by monkey-patching `Sentry::Sidekiq::CleanupMiddleware` so that it re-raises the caught exception after capturing it on sentry as follows:

```ruby
module Sentry
  module Sidekiq
    class CleanupMiddleware
      def call(_worker, job, queue)
        return yield unless Sentry.initialized?

        Sentry.clone_hub_to_current_thread
        Sentry.with_scope do |scope|
          scope.set_extras(sidekiq: job.merge("queue" => queue))
          scope.set_transaction_name("Sidekiq/#{job["class"]}")

          begin
            yield
          rescue => ex
            Sentry.capture_exception(ex, hint: { background: false })
            # THIS IS THE PATCH
            raise ex
            # THIS IS THE PATCH
          end
        end
      end
    end
  end
end
```

I can open a PR to include the change if that's the right way forward, but wanted to double check here first to make sure there isn't something else I'm missing (such as a configuration flag or other "better practice" way to achieve my desired behavior).

**Comment by st0012** [comment]
@jackrr sorry, that's a bug. I think your fix is correct though 👍

**Comment by jackrr** [comment]
@st0012 I'd be happy to spend a moment opening a PR with the fix today, if that'd be helpful.

**Comment by st0012** [comment]
@jackrr of course, that'd be great 😄
