### ISSUE TITLE
Add a requirement-free version of sentry-ruby

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1201]
We're seeing users that are tied with older versions of `faraday`, which prevents them from using the `sentry-ruby` SDK. The reason we bumped the `faraday` requirement to `>= 1.0` was because earlier versions of it (before `0.17.3`) will cause warnings or even crash when used with Ruby 2.7 & 3.0.

But if the user uses Ruby 2.4~2.6, it's actually safe for them to use earlier versions of `faraday` like `0.15` or `0.16`. So we should provide an option for these usages as well.

### Solution

Add a `sentry-ruby-core` gem, which doesn't specify any version of faraday

```ruby
# sentry-ruby-core.gemspec
spec.add_dependency "faraday"
```

and then wrap sentry-ruby around it with `faraday >= 1.0`

```ruby
# sentry-ruby.gemspec
spec.add_dependency "sentry-ruby-core", Sentry::VERSION
spec.add_dependency "faraday", ">= 1.0"
```

**Comment by Drewzar** [comment]
Thanks for this!

Will updates becoming to `sentry-rails` and `sentry-sidekiq` that have the option to use the core version as well?

**Comment by st0012** [comment]
@Drewzar we'll make the change in the next release after we're sure `sentry-ruby 4.1.5` works without any issue 🙂

**Comment by st0012** [comment]
@Drewzar fyi both `sentry-rails` and `sentry-sidekiq` depend on `sentry-ruby-core` now 🙂
