### ISSUE TITLE
ActiveJob's callback chain will be halted when `Sentry.init` is not called beforehand

### ISSUE THREAD

**Issue by ayemos** [getsentry/sentry-ruby#1211]
**Describe the bug**

Loading `sentry-rails` without calling `Sentry.init` causes the callback chain of ActiveJob halted unexpectedly.

As I looked into the implementation, the callback override-ing in `ActiveJobExtensions` seems to prevent the callback calling the passed block when `Sentry.init` is not called beforehand (and `get_current_hub` is `nil`)
https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/active_job.rb#L14

**To Reproduce**

Made a sample rails app ([link](https://drive.google.com/file/d/1BFosBmRMiMcQQExoKQRm0p7FggrlnS9_/view?usp=sharing))  with `SampleJob` which should print `hello` when being called.

```
Loading development environment (Rails 6.1.1)
irb(main):001:0> SampleJob.perform_now
Performing SampleJob (Job ID: 2dee8912-af8e-487d-8598-ed798613cc13) from Async(default) enqueued at
Performed SampleJob (Job ID: 2dee8912-af8e-487d-8598-ed798613cc13) from Async(default) in 0.07ms
=> nil
irb(main):002:0> Sentry.init {}
=> #<Sentry::BackgroundWorker:0x00007fc293a5bc18 @max_queue=30, @number_of_threads=12, @executor=#<Concurrent::ThreadPoolExecutor:0x00007fc293a5bba0 @__Lock__=#<Thread::Mutex:0x00007fc293a5bb28>, @__Condition__=#<Thread::ConditionVariable:0x00007fc293a5bb00>, @auto_terminate=true, @min_length=0, @max_length=12, @idletime=60, @max_queue=30, @synchronous=false, @fallback_policy=:discard, @pool=[], @ready=[], @queue=[], @scheduled_task_count=0, @completed_task_count=0, @largest_length=0, @workers_counter=0, @ruby_pid=22693, @gc_interval=30, @next_gc_time=2818588.191721, @StopEvent=#<Concurrent::Event:0x00007fc293a5ba10 @__Lock__=#<Thread::Mutex:0x00007fc293a5b9c0>, @__Condition__=#<Thread::ConditionVariable:0x00007fc293a5b998>, @set=false, @iteration=0>, @StoppedEvent=#<Concurrent::Event:0x00007fc293a5b8f8 @__Lock__=#<Thread::Mutex:0x00007fc293a5b8a8>, @__Condition__=#<Thread::ConditionVariable:0x00007fc293a5b880>, @set=false, @iteration=0>>>
irb(main):003:0> SampleJob.perform_now
Performing SampleJob (Job ID: 334a51b8-e69f-4c46-8a9b-3c196a53f5ba) from Async(default) enqueued at
hello
Performed SampleJob (Job ID: 334a51b8-e69f-4c46-8a9b-3c196a53f5ba) from Async(default) in 0.32ms
=> 69
```

**Expected behavior**

I'm not sure the behavior shown above is 100% intended.

Instead, it should, in my opinion, work correctly without `Sentry.init` or maybe be clearly documented that `Sentry.init` is needed to be called in every situation.

**Actual behavior**

--

**Environment**
 - Ruby Version: 2.6.6
 - SDK Version: sentry-ruby 4.1.4, sentry-rails 4.1.4
 - Integration Versions (if any): Rails 6.1.1

**Raven Config**

This is not necessary but could be helpful.

```ruby
Raven.configure do |config|
  # the config you're using, without DSN and other sensitive data
end
```

**Comment by st0012** [comment]
thanks for reporting, it should be solved by #1217.
