### ISSUE TITLE
Rails / Rack integration reporting incorrect URL (500 page)

### ISSUE THREAD

**Issue by mcclymont** [getsentry/sentry-ruby#1219]
**Describe the bug**
When the rack middleware catches an unhandled exception in production, the reported URL relative path is always `/500`

In development, it works as expected with the correct URL.

This seems to be a regression since the last major version upgrade.

<img width="300" alt="Screen Shot 2021-01-20 at 15 48 07" src="https://user-images.githubusercontent.com/1817582/105128319-e7c8f300-5b36-11eb-82e0-d4049be29f19.png">

**To Reproduce**

Example repo: https://github.com/mcclymont/rails-sentry-url-bug

* Create a new blank rails project with `rails new my_api --api`
* Include the gems 'sentry-ruby' and 'sentry-rails' in the Gemfile
* Create config/initializers/sentry.rb
* Create a basic route and controller with route e.g. GET /testing.
* In the controller action, raise an error intentionally e.g. `raise 'testing sentry'`
* Navigate to /testing

**Expected behavior**
 The exception is raised and reported to Sentry with the correct request URL path: `http://localhost:3000/testing`

**Actual behavior**
When running with RAILS_ENV=production, the reported URL path is `http://localhost:3000/500`

**Environment**
 - Ruby Version: 2.7.1
 - SDK Version: sentry-ruby (4.1.4), sentry-rails (4.1.4)
 - Integration Versions (if any): Rails 6.0.3.4

**Raven Config**

```ruby
Sentry.init do |config|
  config.dsn = ENV.fetch('SENTRY_DSN')
  config.environment = 'dev'
  config.send_default_pii = true

  config.before_send = lambda do |event, _hint|
    puts event.request&.url
    event
  end
end
```

**Comment by oofoghlu** [comment]
I had encountered this same problem and while #1223 fixes the url in the report I still have the issue that the transaction name is incorrect when the exceptions app redirects to another controller.

e.g. with the redirect `match "/500", via: :all, to: "errors#server_error"` the reported transaction name is `ErrorsController#server_error` rather than the original controller requested like I would hope.

**Comment by st0012** [comment]
@oofoghlu thanks for reporting! I've added https://github.com/getsentry/sentry-ruby/pull/1230 to address that as well.

**Comment by oofoghlu** [comment]
@st0012 thanks for addressing this so swiftly! PR looks great!

**Comment by alaouy** [comment]
Hey @st0012, this issue is still present in the sentry-rails v4.4.0 running on Rails v5.2.6. is there an option to fix this behavior?

**Comment by st0012** [comment]
@alaouy there was a refactoring around the same piece of code in `4.4.0` that could be the cause. can you try `4.3.x` to see if the issue you see is a regression?

**Comment by st0012** [comment]
@BastienL can you open a new issue with steps to reproduce the problem? that'll help a lot, thanks 😄
