### ISSUE TITLE
Event is not compatible with ActiveJob 6+

### ISSUE THREAD

**Issue by sujh** [getsentry/sentry-ruby#1227]
**Describe the bug**

Trying to use `Sentry.capture_exception(error)` to capture  a StandardError and send it asynchronously ,  but it failed to enqueue and reported 

> async event sending failed: Unsupported argument type: StandardError. 

The failed reason can be found here: <https://github.com/rails/rails/blob/v6.0.3.4/activejob/lib/active_job/serializers.rb#L28>. It seems like ActiveJob 6 can't serialize an Exception object

**Expected behavior**
Event should be compatible with ActiveJob 6+

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: 4.1.4
 - Integration Versions (if any):
  - Rails 6.0.3.4, Sidekiq 6.1.2

**Sentry-ruby Config**

```ruby
    Sentry.init do |config|
      config.breadcrumbs_logger = [:active_support_logger]
      config.before_send = lambda do |event, hint|
        event.modules.clear
        event
      end
      config.async = lambda { |event, hint| SentryJob.perform_later(event, hint) }
    end
```

**Comment by st0012** [comment]
@sujh thanks for reporting this 🙂 

the issue is actually caused by the event hint, not the event itself. I have added #1231 to address it. and if you want to get around this issue while waiting for the new release, you can do something like

```ruby
config.async = lambda do |event, hint| 
  hint = JSON.parse(JSON.generate(hint))
  SentryJob.perform_later(event, hint)
end
```

**Comment by st0012** [comment]
@sujh forgot to mention, if you want to get rid of the modules, you can just use

```ruby
config.send_modules = false
```

to disable it 🙂

**Comment by sujh** [comment]
@st0012 thanks for your useful reply. It tooks me awhile to remove the modules info, because I couldn't find any info about modules in the README . It would be helpful to write some modules info in the README.
