### ISSUE TITLE
Raven.annotate_exception has no equivalent in sentry-ruby

### ISSUE THREAD

**Issue by fsateler** [getsentry/sentry-ruby#1239]
**Describe the bug**

When migrating from sentry-raven to sentry-ruby, there appears to be no equivalent to `Raven.annotate_exception`. It is not mentioned on the migration guide either. What is the new way to add extra info to an exception?

**Environment**
 - Ruby Version: 2.6
 - SDK Version: 4.1.4
 - Integration Versions (if any):
  - Rails 6.0

**Comment by st0012** [comment]
@fsateler because `annotate_exception` was a Ruby-only API, currently we don't support anything similar to it after we unify the APIs with other SDKs. would you mind providing me some use cases so I can find a replacement for it?

**Comment by fsateler** [comment]
The use case is being able to attach extra info about the exception, near the place where it was generated, but far from the place where it is handled. For example:

```ruby
class ProcessMultipleItemsJob < ApplicationJob
  def perform
     Item.find_each do |item|
        ProcessItem.call(item)
     end
  end
end

class ProcessItem
  def call item
    item_context = build_context(item)
    # do something
  rescue => e
    # Here we have important context infomation, but we don't want to actually handle the exception. 
    # we let the ActiveJob integration handle it
    Raven.annotate_exception(e, extra: { item_formula: item.formula, item_context: item_context })
   raise
  end
end
```

**Comment by kaspergrubbe** [comment]
@swistak35 If I remember correctly you also used `#annotate_exception` quite heavily in our setup, can you provide some examples too?

**Comment by swistak35** [comment]
@kaspergrubbe We have been using `Raven.extra_context` and `Raven.user_context` to add the context to the errors.

**Comment by st0012** [comment]
@fsateler thanks for the example. but I think this should work the same:

```ruby
  def call item
    item_context = build_context(item)
    # do something
  rescue => e
    Sentry.set_extra(item_formula: item.formula, item_context: item_context)
    raise
  end
```

**Comment by fsateler** [comment]
@st0012 that could work! But only in the case there are no nested scopes (otherwise if the error "escapes" the inner scope, the extra context would be lost). But I figure a regular rails app should not have nested scopes unless the app developer created one, right?

**Comment by st0012** [comment]
@fsateler sorry for the delay. I don't understand your question though, how can an error escape in the above code?

**Comment by fsateler** [comment]
@st0012 I mean for nested scopes:

```ruby
Sentry.with_scope do |outer_scope|
  Sentry.with_scope do |inner_scope|
    ProcessItem.new.call(item)
  end
rescue => e
  Sentry.capture_exception(e)
end
```

In this code, the extra information would be lost, since the context got added to the inner_scope, not the outer_scope. 

Thus mi question: on a plain vanilla rails app, there should be no nested scopes?

**Comment by st0012** [comment]
The SDK only wraps one layer of scope and makes sure the default capturing happen inside it. To give you an idea, it looks like:

```ruby
Sentry.with_scope do |scope|
  begin
    your_code
  rescue => e
    Sentry.capture_exception(e)
  end
end
```

so it shouldn't cause the problem you worry about. if it does, I'll make sure it's fixed 🙂

**Comment by madCode** [comment]
@st0012 any reason this deprecation isn't called out explicitly in the [Ruby Migration Guide](https://docs.sentry.io/platforms/ruby/migration/)?

**Comment by kaspergrubbe** [comment]
It also seem like the `#set_extras` mentioned in this thread is now deprecated:

> Additional Data is deprecated in favor of structured contexts.

> Sentry used to support adding unstructured "Additional Data" via set_extra.

https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/context/

Looking at the documentation just now it seems like breadcrumbs might have an interface that is more suitable in our case: https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/breadcrumbs/

(However, I am not sure of the difference between contexts and breadcrumbs)
