### ISSUE TITLE
Performance/tracing instrumentation for HTTP libraries/adapters

### ISSUE THREAD

**Issue by taylorthurlow** [getsentry/sentry-ruby#1241]
Currently the performance/tracing SDK doesn't support instrumentation of any HTTP libraries. I was told over discord that the priority of this feature is unclear but that it's worth opening an issue here.

I use Faraday personally, and I've been made aware that `sentry-ruby` relies on it as well, so it seems like it could be a good place to start. I'm completely oblivious to how the instrumentation works so I'm not sure if it matters but Faraday is more of a client wrapper on different HTTP adapters (`Net::HTTP` being the default), so maybe the choice is which adapter to instrument rather than which client library. 🤷 

Thanks for the hard work on the Ruby client and performance/tracing!

**Comment by st0012** [comment]
@taylorthurlow sorry for the long waiting. I've implemented https://github.com/getsentry/sentry-ruby/pull/1381 to record `Net::HTTP`'s requests and I'd like to hear your opinion on it 🙂
