### ISSUE TITLE
Controller actions transaction name (performance)

### ISSUE THREAD

**Issue by mbajur** [getsentry/sentry-ruby#1248]
Hello!
It's not technically a bug(report) but rather an edge case scenario but i will give it a shot anyway. 

From what i can see, transaction names in performance module are named after full path called. If end user visits `/blog/posts/3`, transaction name will be `/blog/posts/3`. I believe that makes the job done most of the times (even though, on other APM tools, i seen `Blog::Posts#show` name would be used instead) but in my case, i have a path that receives JWT token as an argument. Problem with that is the token is different pretty much for every single request even given it represents the same record in the database. That produces a separate performance entry for every single request instead every single record. You probably can imagine how useless it becomes thanks to that.

First of all - wouldn't it be a good idea to name transactions after `namespace/controller/action` rather than a URL path? 
Second of all - is that possible to rename the transaction manually during the runtime? So i could rename this specific action's transaction name by myself.

Thanks in advance!

**Comment by st0012** [comment]
@mbajur we do use "controller#action" as the transaction name whenever possible. those transactions should look like this

<img width="1302" alt="截圖 2021-01-29 下午5 10 09" src="https://user-images.githubusercontent.com/5079556/106255311-da0d1f00-6254-11eb-9137-f3245cd4e5f5.png">

can you provide more information about your application so I can help you debug this? like
- sentry-ruby & sentry-rails' version
- Rails version
- your Sentry config

**Comment by mbajur** [comment]
Oh, that's actually correct. I just realized i have both controller/action and full path entries in the performance tab, not sure what's the key in here.

- sentry-rails 4.0.1
- sentry-ruby 4.0.1
- rails 6.0.3
- ruby 2.7.0

Sentry config:
```
Sentry.init do |config|
  config.dsn = Figaro.env.sentry_dsn
  config.breadcrumbs_logger = [:active_support_logger]
  config.traces_sample_rate = 0.2

  if Figaro.env.forward_version_to_sentry
    config.release = "appname@v#{AppName::VERSION}"
  end
end
```

**Comment by st0012** [comment]
@mbajur thanks for the info 👍 

the main cause is that `4.0.1` was quite buggy 😅 
can you upgrade both of your `sentry-ruby` and `sentry-rails` to the latest versions? 

```ruby
gem "sentry-ruby", "~> 4.1.5"
gem "sentry-rails", "~> 4.1.6"
```

the new versions fixed tons of issues and should give you a much better experience 🙂

**Comment by mbajur** [comment]
Thank you! I have this version already on dev branch waiting for a release, will let you know here if it helped.

**Comment by st0012** [comment]
closing for now. feel free to reopen if you still see this issue after the upgrade 🙂
