### ISSUE TITLE
Question: How does sentry detect start/finish of a Rails req/res?

### ISSUE THREAD

**Issue by saurabhnanda** [getsentry/sentry-ruby#1271]
(Please let me know if this is not the right forum to ask such questions)

I'm trying to write my own Rails 3 instrumentation (legacy project!) using `sentry-ruby` and and using `sentry-rails` as a reference. I've looked throughout the source code of `sentry-rails` but couldn't find any calls to `start_transaction` or `transaction.finish`. How is `sentry-rails` hooking into the start/end of a req/res without this?

**Comment by st0012** [comment]
@saurabhnanda `sentry-rails` injects [this middleware](https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/capture_exceptions.rb) for capturing errors & start transactions. but you should check its [parent middleware](https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/rack/capture_exceptions.rb), which actually does most of the job.

**Comment by saurabhnanda** [comment]
Thank you for pointing me in the right direction. A related question: is the following way of ignoring certain transactions optimal?

```ruby
      def finish_span(span, status_code)
        if @assets_regex.nil? || !span.name.match?(@assets_regex)
          span.set_http_status(status_code)
          span.finish
        end
      end
```

Will this do all the hard work of tracing the transaction and then throw it away? 

Also, is this how `traces_sample_rate` works? Does tt records everything, but doesn't send it to the Sentry server at the end?

**Comment by st0012** [comment]
@saurabhnanda 

>  is the following way of ignoring certain transactions optimal?

no, it's not optimal. I should improve this in the future.

> Will this do all the hard work of tracing the transaction and then throw it away?

not likely. the requests that match the condition shouldn't trigger any of those tracing events because they will be returned early by assets-related middleware. so I don't concern about wasting resources too much.

> Also, is this how traces_sample_rate works? Does tt records everything, but doesn't send it to the Sentry server at the end?

the tracing sampling is done right after the transaction starts, which would be the start of a request in a web app. and if a transaction is not sampled, the SDK doesn't record tracing events for it.

**Comment by st0012** [comment]
closing now, let me know if you have other questions and I'll reopen it 🙂
