### ISSUE TITLE
Either set_context is Broken, or the Documentation Is

### ISSUE THREAD

**Issue by jherdman** [getsentry/sentry-ruby#1293]
**Describe the bug**

See title

**To Reproduce**

```ruby
# From docs

Sentry.configure_scope do |scope|
  scope.set_contexts('character.name' => 'Mighty Fighter')
end

Sentry.capture _message "YO!"
```

**Expected behavior**

Extra context is provided

**Actual behavior**

<img width="467" alt="Screen Shot 2021-02-17 at 3 50 21 PM" src="https://user-images.githubusercontent.com/3300/108266253-decc4100-7137-11eb-94fc-0ee30badd7c5.png">

sentry-ruby should be giving me more guidance on what context should look like.

**Environment**
 - Ruby Version:  ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
 - SDK Version: sentry-ruby-4.1.5
 - Integration Versions (if any): sidekiq, rails
  - e.g. Rails 6.0, Sidekiq 6.1.2

**Comment by st0012** [comment]
thanks for reporting this, I've fixed the document 🙂

**Comment by jherdman** [comment]
Has the documentation been updated? If so...

<img width="776" alt="Screen Shot 2021-03-04 at 9 12 43 AM" src="https://user-images.githubusercontent.com/3300/110000514-62159700-7ce1-11eb-96a9-674f843a855e.png">

This may need fixing.

**Comment by st0012** [comment]
@jherdman sorry, I've made another fix for it

<img width="771" alt="set-context example" src="https://user-images.githubusercontent.com/5079556/111900868-d38a6f00-8a6f-11eb-8baf-1c56362007a4.png">

**Comment by rromanchuk** [comment]
fwiw,  i did like the idea of being able to use a keypath_string => Hash.  Especially in the case when enriching/appending context. In those enriching cases, i usually already have the `Hash`, and it's the keypath that matters. When i'm yielding that block for enrichment reasons it's less of a gather and organize exercise. 

Just noticed it when was trying to remove all the `set_extras`, where the simple one liner is natural   `set_extras("sns.ses.error", hash_already_prepared_in_local_scope)` vs this awkward chunky boy

```ruby
Sentry.configure_scope do |scope|
  scope.set_context(
    :sns,
    {
      ses: {
        error: hash_already_prepared_in_local_scope
      }
    }
  )
end
```

PSA: the signature on tags might end up misleading people too. https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/tags/

`Sentry.set_tags('page.locale': 'de-at')` This is implying a nested data structure for tags.  Also, this tag is no where in the following image, which might be trying to show you the defaults. 


> Some tags are automatically set by Sentry. We strongly recommend against overwriting those tags. Instead, name your tags with your organization's nomenclature.

This was a bit frustrating too, do not overwrite default keys, without any reference to what those keys are, unless thats the purpose of the screenshot of tags in the UI. I'll check out the specs and try to offer a pr that makes it a bit more clear.

**Comment by rromanchuk** [comment]
Also, In the context of a base controller, in a before_action to setup the context for the request, i feel like i might be using the wrong setter. I guess it better conveys this is structured data that follows a spec, and not a random of hash the developer dumped 

```ruby
def set_sentry_context
      Sentry.set_user(
        {
          id: current_user&.id,
          email: current_user&.email,
          username: current_user&.name,
          ip_address: client_ip
        }
      )


      Sentry.configure_scope do |scope|
        scope.set_context(
          :culture,
          {
            locale: locale,
            timezone: time_zone
          }
        )

        scope.set_context(
          :browser,
          {
            name: locale
          }
        )


        scope.set_context(
          :app,
          {
            app_version: active_version,
            app_build: active_build
          }
        )

        scope.set_context(
          :runtime,
          {
            version: correlation.version
          }
        )
      end

    end
```
