### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by bblack** [getsentry/sentry-ruby#1315]
**Describe the bug**

Occasionally, we have this error occur when we call Raven.capture_exception:

```
NoMethodError: undefined method `map' for nil:NilClass
  from raven/configuration.rb:317:in `error_messages'
  from raven/instance.rb:107:in `capture_type'
```

(Strangely, there's nothing in the backtrace between that and the line in our app that calls `Raven.capture_exception`—not even capture_exception itself.)

My suspicion is that this is a thread-safety issue: this error is what would happen if `@errors` were an empty array when that first line of `error_messages` is executed, and our app runs a large number of threads. We've seen it infrequently but repeatedly.

**To Reproduce**

```rb
100.times do
  Thread.new do
    # This string is redacted, but should match the message in the proc passed to `config.should_capture`; 
    # see config below
    Raven.capture_exception(StandardError.new("<redacted>"))
  end
end
```

**Expected behavior**

In each of 100 threads, the exception is reported, and the function returns.

**Actual behavior**

In a couple of threads, capture_exception raises a new error.

**Environment**
 - Ruby Version: JRuby 9.2.11.1
 - SDK Version: 2.13.0

**Raven Config**

```rb
Raven.configure do |config|
  config.dsn = 'https://<redacted>:<redacted>@app.getsentry.com/<redacted>'
  config.excluded_exceptions = ['<redacted>']
  config.should_capture = Proc.new do |e|
    if e && e.respond_to?(:message) && e.message&.include?("<redacted>")
      next false
    end

    true
  end
  config.environments = ['staging', 'production']
end
```

**Comment by st0012** [comment]
@bblack I haven't seen any similar issues before. can you try `sentry-raven` `3.x` versions and see if this still happens? or if you could [migrate](https://docs.sentry.io/platforms/ruby/migration/) to the new `sentry-ruby` SDK that should also help 🙂

**Comment by bblack** [comment]
> I haven't seen any similar issues before.

For me, the issue is quite easy to reproduce. Just `require raven`, run the configure block above (replacing the dsn with some valid url, even if if doesn't actually include valid credentials or a valid project id), then the `100.times do` block. My guess is that JRuby is necessary here to reproduce the error since it's a thread-safety issue which would likely not happen on MRI due to GIL.

> can you try sentry-raven 3.x versions and see if this still happens? 

I just tried with sentry-raven 3.1.2 and the issue persists.

> or if you could migrate to the new sentry-ruby SDK that should also help 🙂

I will try and report back.

**Comment by bblack** [comment]
> or if you could migrate to the new sentry-ruby SDK that should also help 🙂

in analogous code, i was **not** able to reproduce on sentry-ruby 4.5.0:

```rb
require 'sentry-ruby'

Sentry.init do |config|
  config.dsn = 'https://foo:foo@app.getsentry.com/foo'
  config.excluded_exceptions = ['<redacted>']
  config.before_send = Proc.new do |e|
    if e && e.respond_to?(:message) && e.message&.include?("<redacted>")
      next nil
    end

    e
  end
  config.enabled_environments = ['staging', 'production']
end

100.times do
  Thread.new do
    # This string is redacted, but should match the message in the proc passed to `config.should_capture`; 
    # see config below
    Sentry.capture_exception(StandardError.new("<redacted>"))
  end
end
```

**Comment by st0012** [comment]
@bblack thanks for the thorough experimentation and analysis 👍 

yeah I believe there could be concurrency issue caused by the singleton pattern `sentry-raven` uses. but because fixing it requires changing the SDK structure while `sentry-raven` has entered maintenance mode, we don't plan to fix it at the moment.

so my recommendation would be migrating to the new SDK to avoid such issue. let me know if there's anything I can do to help you migrate 🙂
