### ISSUE TITLE
Does Sentry work seamlessly with Roda

### ISSUE THREAD

**Issue by misner** [getsentry/sentry-ruby#1316]
Is it possible and is there any caveats in monitoring a ruby on Roda app ? 

For Rails users, I see they must add both sentry-ruby and sentry-rails. Does that mean that if you use Roda isntead of Rails, you'll miss some tracking/monitoring that is only on the sentry-rails part ?

**Comment by st0012** [comment]
yes. `sentry-rails` provides deep integration with Rails, like injecting middlewares automatically and listens to framework instrumentation for breadcrumbs and performance monitoring. but the middleware (`Sentry::Rack::CaptureExceptions`) and breadcrumb/performance monitoring feature is defined in `sentry-ruby`. so for roda users they can still manually collect the information to do what `sentry-rails` provides.

**Comment by misner** [comment]
thanks
