### ISSUE TITLE
Raven 3.1.1 configured not to capture errors: No project_id specified

### ISSUE THREAD

**Issue by rkorzeniec** [getsentry/sentry-ruby#1325]
**Describe the bug**
The `sentry-raven` gem keeps showing info even when the raven is disabled for that ENV, as well as with DSN set.
```
I, [2021-03-11T06:33:37.073037 #20370]  INFO -- sentry: ** [Raven] Raven 3.1.1 configured not to capture errors: No project_id specified
```

While in the code (`lib/raven/configuration.rb:77`) it says the following:
```
# Project ID number to send to the Sentry server
# If you provide a DSN, this will be set automatically.
attr_accessor :project_id
```

**To Reproduce**
1. configure the app
2. launch the rails server

**Expected behavior**
No raven logs for disabled ENV for the `project_id`

**Actual behavior**
Info log for the `project_id`
```
I, [2021-03-11T06:33:37.073037 #20370]  INFO -- sentry: ** [Raven] Raven 3.1.1 configured not to capture errors: No project_id specified
```

**Environment**
 - Ruby Version:  2.7.2
 - SDK Version: 3.1.1
 - Integration Versions (if any):
  - Rails: 6.1.3
  - delayed_job_active_record: 4.1.5

**Raven Config**

```ruby
::Raven.configure do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
  config.environments = %w[production]
  config.async = ->(event) { SentryJob.perform_later(event) }
end
```

**Comment by st0012** [comment]
@rkorzeniec I think the newer `sentry-ruby` SDK has fixed the issue. but because `sentry-raven` has entered maintenance mode and this isn't a critical issue, I won't port the solution to it. so I recommend you to upgrade the SDK follow the [migration guideline](https://docs.sentry.io/platforms/ruby/migration/) 🙂

**Comment by proud-muraoka** [comment]
sentry-raven から sentry-ruby に移行する必要があるってことですかね
