### ISSUE TITLE
Transaction exclusion from path and host

### ISSUE THREAD

**Issue by benebrice** [getsentry/sentry-ruby#1333]
**Describe the idea**

Currently we can exclude error type but not transactions. This means, even with a low value for `traces_sample_rate`, we'll have recorded requests that should not.

**Why do you think it's beneficial to most of the users**

Most of production application have healthcheck that requires app to unlock loadbalancers' traffic. 

Healthcheck on server itself does not mean Rails server is up, that's why endpoint might be the Rails app directly. 

To be able to exclude path/host could solve this issue.

**Possible implementation**

Here is my proposition: https://github.com/getsentry/sentry-ruby/pull/1332

**Comment by st0012** [comment]
@benebrice thanks for the proposal, this is something we're planning to do 🙂 

in fact, you can already sample transactions with the request path, like:

```ruby
  config.traces_sampler = lambda do |context|
    transaction_context = context[:transaction_context]

    # rails.request or rack.request
    if transaction_context[:op].match?(/request/) && transaction_context[:name].match?(/health_check/)
      false
    else
      0.5
    end
  end
```

in the future, we'll also provide a way to sample transactions with more information like response status or host 😄

**Comment by benebrice** [comment]
Thanks for your reply @st0012 !

I've contacted support before implementing it. They told me this feature does not exist.. Your way is easier than mine. I'll keep and use it obviously. 
Should I close this issue?

**Comment by st0012** [comment]
@benebrice you can try it first to see if this really works for you 🙂 if I see no further questions in the next few days I'll assume it works and I'll close it 😉

**Comment by benebrice** [comment]
I've already tested it. Works like a charm. 👌🏻

**Comment by st0012** [comment]
aha I'll close it now then 😄
