### ISSUE TITLE
sentry-rails forces Sentry::BackgroundWorker to fail when ActiveRecord is not present

### ISSUE THREAD

**Issue by JonathanTron** [getsentry/sentry-ruby#1342]
**Describe the bug**

I don't use ActiveRecord but Sequel in my Rails apps and after switching from the old sentry-raven to the new sentry-ruby/sentry-rails no errors where reported, after fiddling a little bit and making sure I configured sentry to be synchronous, I discovered that it fact it threw an exception in sentry-rails `Sentry::BackgroundWorker` because I don't have `ActiveRecord` in my projects.

**To Reproduce**

1. Create a new rails project
2. Remove the `require "active_record/railties"` from `config/application.rb`
3. Install sentry-ruby/sentry-rails and configure it to report errors synchronously
4. in a `rails console` trigger an exception: `Sentry.capture_message("test message")`

**Expected behavior**

`Sentry::BackgroundWorker#perform` should only try to acquire an AR connection if AR is defined.

**Actual behavior**

**Environment**
 - Ruby Version: doesn't matter
 - SDK Version: 4.3.0
 - Integration Versions (if any):
  - Rails 5.2+

**Comment by JonathanTron** [comment]
Thanks!

**Comment by st0012** [comment]
@JonathanTron fyi it’s been released in 4.3.1 🙂
