### ISSUE TITLE
sentry-rails 4.3.0 not sending transactions

### ISSUE THREAD

**Issue by gustavoalb** [getsentry/sentry-ruby#1346]
using sentry-rails 4.2.2, everything works as expected.
when updating sentry-rails to 4.3.0, none of the transactions and exceptions go to sentry.

stack: Ruby 2.6.5, Rails 5.1.4, Sentry-rails and sentry-ruby 4.3.0

Sentry config is the one from guide, only with my dsn there.

**Comment by st0012** [comment]
does your application replace the ORM with a  non-activerecord one?

**Comment by gustavoalb** [comment]
Yes, Mongoid.

**Comment by st0012** [comment]
I see, thanks. I think this is the same issue as https://github.com/getsentry/sentry-ruby/issues/1342
