### ISSUE TITLE
What is the difference between sentry-ruby and sentry-ruby-core?

### ISSUE THREAD

**Issue by kaito0228** [getsentry/sentry-ruby#1349]
When I install it in my Ruby on Rails app, it says you need to include the following two, but if you include `sentry-ruby-rails`, it will include the dependency sentry-ruby-core.
```ruby
gem "sentry-ruby"
gem "sentry-rails"
```
For Ruby on Rails apps, why not just put sentry-rails in the Gemfile?
Please let me know if there is any difference.

**Comment by st0012** [comment]
`sentry-ruby` specifies version requirements on the SDK's 2 core dependencies: `faraday` and `concurrent-ruby`. so if you can safely install `sentry-ruby`, those 2 dependencies should work well with the SDk. if they don't, we'll fix it.

on the other hand, `sentry-ruby-core` doesn't specify the version requirements at all and you can use whatever version of the dependencies you want. this provides more flexibility to our users, but it also means that you could end up using a version of `faraday` that doesn't work with the SDK. for example, if you use `faraday 0.15.0` with `Ruby 3.0.0`, it'll just break.

**Comment by kaito0228** [comment]
I understood.
To use it safely, it's better to use `sentry-ruby` and `sentry-rails` together.
Thank you very much!
