### ISSUE TITLE
Timing out on getsentry.com (Europe Region)

### ISSUE THREAD

**Issue by troelskn** [getsentry/sentry-ruby#135]
Hi,

I've signed up at getsentry.com and installed the gem from source, e.g. in `Gemfile` I have:

``` ruby
gem 'sentry-raven', :git => "https://github.com/getsentry/raven-ruby.git"
```

I run the test command `bundle exec rake raven:test` and get the following error:

```
I, [2013-10-11T22:28:24.700397 #7352]  INFO -- : ** [Raven] Raven 0.6.0 ready to catch errors
Client configuration:
-> server: https://app.getsentry.com
-> project_id: 12345
-> public_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-> secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Sending a test event:
-> ** [Raven] Unable to record event with remote Sentry server (Faraday::Error::TimeoutError - execution expired)

An error occurred while attempting to send the event.
```

It happens pretty fast, so I don't think there is an actual timeout happening.

Any ideas?

**Comment by rastkojokic** [comment]
I can report the same issue... Yesterday I was not experiencing any problems while sending data to Sentry... Today I get the same error as @troelskn .

```
** [Raven] Raven HTTP Transport connecting to https://app.getsentry.com
** [Raven] Unable to record event with remote Sentry server (Faraday::ConnectionFailed - execution expired)
...
```


Any ideas what is going on?

**Comment by dcramer** [comment]
@rastkojokic It's really hard to say. It's sluggish networking from [somewhere], but I think its out of our control as we dont have any POPs yet (our servers are all in Texas). Definitely nothing thats different on our end as far as I can see. You may consider increasing the timeout (or ideally using the async stuff).

We may prioritize rolling out our local agent which will help alleviate any of these concerns

**Comment by IntractableQuery** [comment]
I just signed up for Sentry and was having the same timeouts when attempting rake raven:test

Switching from HTTPS to HTTP did not help.

I saw you expose faraday's timeouts (in seconds), e.g.

```ruby
    config.timeout = 10
    config.open_timeout = 10
```

In this case, it was open_timeout that fixed the problem.  I turned on async event delivery per the Advanced Configuration instructions, so hopefully this avoids locking up web request threads if I really am hitting unusually long open attempts.

**Comment by perlun** [comment]
@IntractableQuery 

> I saw you expose faraday's timeouts (in seconds), e.g.

How can these be tweaked, do you have a more exhaustive example? I am seeing intermittent issues like this, on a customer server running in Portugal.

**Comment by perlun** [comment]
For others reading this wondering like me how to tweak the settings, here is a full example:

```ruby
Raven.configure do |config|
  # The default timeouts are too short on slow networks.
  config.timeout = 10
  config.open_timeout = 10
end

```
