### ISSUE TITLE
before_send Problems with Skipping Exceptions

### ISSUE THREAD

**Issue by westonganger** [getsentry/sentry-ruby#1359]
It was quite difficult to locate the documentation on how to skip exceptions based on a Proc. This should be highlighted better.

Finally after finding out how to do this, it doesn't ever send the event when `before_send` is defined.

```ruby

ignored_backtrace_matches = [
  "/db/migrate/",
].freeze

Sentry.init do |config|

  ### NOT WORKING - SKIPS ALL ERRORS REGARDLESS OF MATCH
  config.before_send = lambda do |event, hint|
    if event.exception.backtrace.any?{|line| ignored_backtrace_matches.any?{|x| line.include?(x) } }
      next nil ### THIS SHOULD SKIP SENDING THE ERROR
    end

    event
  end

end
```

Please advise if I am doing something wrong here.

sentry-rails 4.2.2
sentry-ruby 4.2.2

**Comment by westonganger** [comment]
Hmm this may have been a delay in the Event Processing

**Comment by st0012** [comment]
@westonganger this is because the SDK by default sends events with its own background worker. you can use 

```ruby
config.background_worker_threads = 0
```

to disable the worker. then you should see the `before_send` being called synchronously and showing the exceptions when something gets wrong.

**Comment by westonganger** [comment]
Ok this should be also be documented. I should note I am also using `sentry-sidekiq 4.2.1` if any difference in behaviours.

**Comment by st0012** [comment]
@westonganger did you figure out how to skip exceptions?
