### ISSUE TITLE
[Tracing] Transaction module doesn't respect logger config

### ISSUE THREAD

**Issue by d-kononov** [getsentry/sentry-ruby#1361]
**Describe the bug**
Tracing doesn't respect logger config.

**To Reproduce**
Current config:
```
Sentry.init do |config|
  config.breadcrumbs_logger = [:active_support_logger]
  config.release = ENV.fetch('APP_VERSION', 'unknown')
  config.excluded_exceptions = [
    'SignalException'
  ]
  config.logger = Sentry::Logger.new(STDOUT)
  config.logger.level = Sentry::Logger::ERROR

  return if Rails.env.development? || Rails.env.test?
  config.traces_sampler = lambda do |sampling_context|
    transaction = sampling_context[:transaction_context]
    !transaction[:name].empty? && transaction[:name].include?('health_check') ? 0 : 0.7
  end
end
```

**Expected behavior**
`Transaction` module should respect `config.logger` and `config.logger.level`

**Actual behavior**
There are a lot of debug logs produced by `Transaction` module with config given in upper section.
https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/transaction.rb#L118

**Environment**
 - Ruby Version: 2.7.1
 - SDK Version: 4.3.2
 - Integration Versions (if any): Rails 6.0.3.2

**Comment by st0012** [comment]
the `active_support_logger` doesn't capture data from a logger. it logs data from [ActiveSupport's instrumentation](https://guides.rubyonrails.org/active_support_instrumentation.html), which doesn't have a log as log level. 

if you're using `sentry-ruby 4.3.1`, you can use [`config.before_breadcrumb`](https://guides.rubyonrails.org/active_support_instrumentation.html) to filter out the data you want to exclude.

**Comment by st0012** [comment]
sorry that I misread your description 😬 I'll investigate the cause

**Comment by d-kononov** [comment]
Thanks!
