### ISSUE TITLE
[Plan] New Integrations 

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1369]
- `sentry-resque`
- `sentry-faraday`
  - this includes a new `breadcrumb logger` and `tracing subscriber`

**Comment by pam-** [comment]
👋 any updates on the sentry-resque feature?

**Comment by st0012** [comment]
@pam- I'll start working on that soon 🙂

**Comment by st0012** [comment]
@pam- `sentry-resque` has been released with `4.6.0` 😄

**Comment by st0012** [comment]
also, because http tracing & breadcrumb has been supported natively in `sentry-ruby`, I think `sentry-faraday` is not at high priority anymore. going to close this now.

**Comment by pam-** [comment]
@st0012 thank you so much!!!
