### ISSUE TITLE
ActiveRecord breadcrumbs aren't emitted inside graphql-ruby queries (Transactions lost when switching to different fibres)

### ISSUE THREAD

**Issue by bubba** [getsentry/sentry-ruby#1374]
**Describe the bug**
I'm trying to integrate performance monitoring for a GraphQL API server that uses graphql-ruby on rails. Breadcrumbs for ActiveRecord queries are emitted fine up until `Schema.execute`, at which point no more breadcrumbs are logged:

```ruby
class GraphQLController < ApplicationController
  def execute
    scope = Sentry.get_current_scope
    p scope.get_transaction # returns a transaction
    result = Schema.execute(params[:query], variables: prepare_variables(params[:variables]), operation_name: params[:operation_name])
    p scope.get_transaction # returns the same transaction
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end
# more stuff...
end
```

The weird thing is is that inside my GraphQL schema class, if I log the scope and transaction, the scope is different and the transaction is nil:

```ruby
# somewhere where Schema.execute calls
def foo
  p Sentry.get_current_scope # a different scope from the one inside my controller
  p Sentry.get_current_scope.get_transaction # nil!
end
```

This is why I believe the activerecord subscriber isn't emitting any breadcrumbs. And I believe this is happening because graphql-ruby does this execution on different fibres (same thread though). Thus the hub ends up getting cloned:

https://github.com/getsentry/sentry-ruby/blob/c7be1f3fb367a60246ff893eb17421cd6295180b/sentry-ruby/lib/sentry-ruby.rb#L89-L96

But once it's cloned the transaction is lost. 

**To Reproduce**

Create a new rails project, install graphql-ruby, try getting the current transaction from inside your schema/types. I think it might be possible to make a smaller test case by doing something with fibres yourself.

**Expected behavior**

`get_current_scope` and `get_current_transaction` return the same scope and transaction as the originating fibre/inside the action controller, and any activerecord queries are added as breadcrumbs.

**Actual behavior**
`get_current_scope` returns a different scope and `get_current_transaction` returns nil, and no activerecord queries are added to sentry as breadcrumbs

**Environment**
 - Ruby Version: 3
 - SDK Version:
   - sentry-ruby 4.3.1
   - sentry-rails 4.3.3
 - Integration Versions (if any):
  - Rails 6.1.3.1
  - graphql-ruby 1.12.6
  - 

**Raven Config**

This is not necessary but could be helpful.

```ruby
Sentry.init do |config|
  config.dsn = 'blah'
  config.breadcrumbs_logger = [:active_support_logger]
  config.traces_sample_rate = 0.2
end

```

**Comment by bubba** [comment]
It does indeed occur whenever any activerecord query is run from inside a fiber. I've attached the smallest case I can reproduce. Visiting `localhost:3000/bar/bar` should send the events to sentry

```ruby
class BarController < ApplicationController
  def bar
    Bar.create! name: '0' # gets breadcrumbed
    fiber = Fiber.new do
      Bar.create! name: '1' # doesn't get breadcrumbed
      Fiber.yield 1
      Bar.create! name: '2' # doesn't get breadcrumbed
      2
    end

    puts fiber.resume
    puts fiber.resume
  end
end

```

[sentry-test.zip](https://github.com/getsentry/sentry-ruby/files/6236218/sentry-test.zip)

**Comment by bubba** [comment]
Tested it locally and it works, many thanks!

**Comment by st0012** [comment]
@bubba np, your detailed issue report definitely helped a lot 🙂
