### ISSUE TITLE
How to Prevent Sending Exceptions for Rails console or db:migrate

### ISSUE THREAD

**Issue by westonganger** [getsentry/sentry-ruby#1378]
I do not want the exceptions from my Rails console sessions or db:migrate to send to sentry. Is there some way to disable this.

**Comment by helmiItsavirus** [comment]
@westonganger did you activate sentry on the development environment?

**Comment by westonganger** [comment]
No it is disabled in development. This is not a development environment issue.

**Comment by westonganger** [comment]
I am also recieving errors on server when running tasks that dont exist. IE. Typos:

```ruby
bundle exec rails consolee
```

RuntimeError: Don't know how to build task 'consolee'

Again I dont want to send error notifications while I am performing server tasks

**Comment by st0012** [comment]
the SDK integrates with rake and intercepts exceptions raised during a rake task. I can add an option to disable the integration all together, but it won't be practical to introduce something like "don't capture this exception only during rake tasks". do you think that'll solve your problem?

**Comment by westonganger** [comment]
Yes please add option to disable the rake integration. Would this also remove the notifications during `rails console` sessions?

**Comment by st0012** [comment]
I don't think the SDK captures errors from the console. At least not in an intentional way and I can't reproduce this behavior with my apps. Can you check the event's stacktrace and point out what captures the error?

**Comment by westonganger** [comment]
Hmm it appears you are correct about the `rails:console` I guess I was incorrect about that one.

**Comment by st0012** [comment]
@westonganger it's been shipped in `v4.5.0` 😄

**Comment by MaicolBen** [comment]
What about `capture_message` ? How can we skip it? In the past it was possible to do `Raven.configuration.environments = %w[ignore_on_console] `
