### ISSUE TITLE
how to filter some api in sentry performance

### ISSUE THREAD

**Issue by RIP-GitHub** [getsentry/sentry-ruby#1388]
set sentry in my rails
![image](https://user-images.githubusercontent.com/29975251/114017926-3d43af00-989f-11eb-8039-bbff14cbfa3d.png)
health check api use too much of my performance
![image](https://user-images.githubusercontent.com/29975251/114018136-80058700-989f-11eb-8505-e2e47468c9c3.png)
What can I do without monitoring the health check API

**Comment by st0012** [comment]
can you try this?

```ruby
  config.traces_sampler = lambda do |context|
    transaction_context = context[:transaction_context]

    # rails.request or rack.request
    if transaction_context[:op].match?(/request/) && transaction_context[:name].match?(/health_check/)
      false
    else
      0.5
    end
  end
```

**Comment by st0012** [comment]
closing for now. let me know if the code above doesn't work 🙂
