### ISSUE TITLE
Make `hub` a required argument in Transaction's constructor

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1393]
This issue is more about the general design principle on all Sentry SDKs instead of just `sentry-ruby`.  I want to discuss the necessity of falling back to `Sentry.get_current_hub` when the `hub` is not provided.

In `sentry-python`, it's done in `Transaction.finish`:

https://github.com/getsentry/sentry-python/blob/19fa43fec5a20b3561a16970ce395c93ac1be57d/sentry_sdk/tracing.py#L409-L417

In `sentry-javascript`, it looks to be done in the constructor?

https://github.com/getsentry/sentry-javascript/blob/fbdc8753ab5e54fb8c83101de78a805ec7335522/packages/tracing/src/transaction.ts#L22-L46

And currently, `sentry-ruby` does it like this

```ruby
def initialize(name: nil, parent_sampled: nil, hub: Sentry.get_current_hub, **options)
```

Shouldn't we make the `hub` argument a hard requirement when initializing a `Transaction` object? Which means, we should never need to fallback to the current active hub. 

I think we'd agree that a `Transaction` object should never be initialized manually by the user, which is also stated in `sentry-javascript`'s comment:

```javascript
   * This constructor should never be called manually. Those instrumenting tracing should use
   * `Sentry.startTransaction()`, and internal methods should use `hub.startTransaction()`.
```

If that's the case, `hub.startTransaction()` should always be able to provide a `hub` to the transaction, and thus never need to fallback to `getCurrentHub()`.

So what I'm proposing are:

1. Stop making the `hub` argument optional for the `Transaction` constructor.
2. Remove all the fallback logic from the constructor or `Transaction.finish`. Because it must present and must be a `Hub` instance.

Wdyt?

**Comment by rhcarvalho** [comment]
> In `sentry-python`, it's done in `Transaction.finish`

There yes, and also done in multiple places:

- [`start_transaction`](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/api.py#L209-L214) & [`hub.start_transaction`](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/hub.py#L479-L512)
- Every place where `hub` is used: look for `self.hub` in [tracing.py](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/tracing.py), you'll find always `self.hub or sentry_sdk.Hub.current`, except in `__init__` (but we know from `start_transaction` the `hub` keyword argument already defaulted to the current hub)

AFAICT this defaulting in many places is more of how the code evolved than explicit design.

> So what I'm proposing are:
> 
> 1. Stop making the `hub` argument optional for the `Transaction` constructor.
> 2. Remove all the fallback logic from the constructor or `Transaction.finish`. Because it must present and must be a `Hub` instance.
> 
> Wdyt?

I think this is perfectly fine. Similarly, the `finish` method or any other method do not need to take `hub` as argument, the `hub` reference should not change during the lifetime of a transaction.

This level of implementation detail is often left out of the spec and SDKs end up doing what makes sense in each platform, would be fine to document that proposal in https://develop.sentry.io.

**Comment by rhcarvalho** [comment]
The only general concern is the risk of breaking existing user code with SDK changes. (Removing arguments is a breaking change, making an optional argument required is a breaking change, and so on)

**Comment by st0012** [comment]
@rhcarvalho thanks for the valuable insight! 

I don't consider requiring the `hub` argument a breaking change, as the constructor is never designed to be called directly (in the Ruby case). I'll think more on `Transaction#finish` though.
