### ISSUE TITLE
How to connect sentry-ruby/rails with frontend?

### ISSUE THREAD

**Issue by oliverguenther** [getsentry/sentry-ruby#1411]
I saw that there's an integration guide for the JavaScript SDK on how to connect a backend service through the use of a meta `sentry-trace` object.

How would I use this with the Ruby/Rails SDK? There's `Sentry.get_current_scope.get_transaction` with `#parent_span_id`, `#span_id` and `#trace_id`. The first one seems to be always nil in a response (since it's the highest transaction probably), and the other two work, but don't seem to connect the requests correctly in the performance module.

Any pointers here that I'm missing? I would gladly then send a PR to the docs to describe this part.

**Comment by st0012** [comment]
The connection should start from the frontend and ends in the backend. So you don't need to send anything in the response, you receive a header called `HTTP_SENTRY_TRACE` from the frontend. If the frontend request contains the `HTTP_SENTRY_TRACE` header, the SDK should automatically connect the 2 traces together. 

The header's value would look like this:

```
"d298e6b033f84659928a2267c3879aaa-2a35b8e9a1b974f4-1"
"#{external_transaction.trace_id}-#{external_transaction.span_id}-#{sampled}"
```

**Comment by rhcarvalho** [comment]
Hi @oliverguenther, I imagine you're reading https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload, is that correct?

In the Ruby SDK, use the [`Span.to_sentry_trace`](https://github.com/getsentry/sentry-ruby/blob/2ccfcf3f93057f4f0a3c98dc5e3ace3868dca509/sentry-ruby/lib/sentry/span.rb#L55) method to generate a meta tag like:

```erb
<meta name="sentry-trace" content="<%= span.to_sentry_trace %>" />
```

And to get the current span in the controller:

```ruby
Sentry.get_current_scope.span
```

**Comment by oliverguenther** [comment]
Thanks to both of you. The latter was what I'm looking for. It's now reusing the backend-provided span with the subsequent API requests. Is there any documentation to allow custom routing events to break this span?

**Comment by rhcarvalho** [comment]
> Is there any documentation to allow custom routing events to break this span?

Sorry, I'm not sure I follow. Do you mean you want some of the frontend requests to continue the trace and some to start a new one?

**Comment by oliverguenther** [comment]
Yes, exactly that. We have a hybrid application where some requests start in the backend and then continue to load some XHR from the frontend. But from there, you may have pages with a SPA-like frontend that will do its own navigation, and I'd like to separate from the first request span once a frontend navigation has been performed. Does that make sense?

I'm currently looking into sentry-docs to extend your information to it, but the way the platform-specific content is included, it looks like this file here is the only place I could add it to: https://github.com/getsentry/sentry-docs/blob/32223a1b9e3274f03639d09f03d0ff6a6412d20d/src/includes/performance/configure-sample-rate/ruby.mdx#L15-L16

**Comment by rhcarvalho** [comment]
@oliverguenther yes, it makes sense. Fortunately, that's already the behavior the SDK implements by default. We only read the `meta` tag for the first, `pageload`, transaction. Subsequent `navigation` transactions ignore the `meta` tag and start a new trace.

https://github.com/getsentry/sentry-javascript/blob/3eb9e059d08339e542985e8a97eb563ad0812e28/packages/tracing/src/browser/browsertracing.ts#L194

---

Thanks for having a go at improving the docs!

https://docs.sentry.io/platforms/ruby/performance/#connecting-services links to https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload which is common content for all platforms.

Probably the source of confusion here is that `span.toTraceparent()` was an old method name before `span.to_sentry_trace` existed. In Ruby we never had to implement the old name.

Would having both names there as possible method names depending on SDK have helped you?

**Comment by oliverguenther** [comment]
Hi @rhcarvalho , yes having both names would have made it a bit easier. However I still needed to look at the SDK code to find out available methods. As you wrote, the connecting-services page is generic, so that's not the correct place to add ruby-specific code. I'm wondering if the docs need another (optional) Include at the connecting-services page to allow to specify the correct command for each SDK?

BTW: Even with the to_sentry_trace enabled and it correctly using that in the header values, I'm not seeing the transaction connected to a single trace in the performance tab of sentry. You are probably not the right contact for that question, but is there any additional configuration needed to "merge" these in the sentry UI?

**Comment by rhcarvalho** [comment]
Hi @oliverguenther, this almost got lost in all my notifications, sorry for the delay.

Since the original issue seems to be solved, I'd suggest we follow up with 2 new tracking issues.

1. For the docs change, could you please open an issue in https://github.com/getsentry/sentry-docs/issues? Then we could get some eyes from the docs team regarding how to work with the current structure or make an improvement.

2. For not seeing the traces connected, either there's a bug in the SDK or something in the UI. We could start with validating the former. Could you please open a new issue here with some code or steps for reproducing it? @st0012 could you help validate that front-end + back-end trace is working fine with the Ruby SDK?

Thanks!

**Comment by st0012** [comment]
@rhcarvalho ok, I'll try to make a distributed tracing setup in our example Rails app and see how that goes.

**Comment by st0012** [comment]
@rhcarvalho I don't write JS that often so I figure it'll be easier to test the `sentry-trace` header capturing with 2 Ruby apps. Here's the PR: https://github.com/getsentry/sentry-ruby/pull/1444

And here's the result 

<img width="70%" alt="connect sentry trace" src="https://user-images.githubusercontent.com/5079556/118290767-604e2800-b509-11eb-9bf9-0d38964320ae.png">

I think it proves that the mechanism worker? Let me know if I missed anything.
