### ISSUE TITLE
Is it possible to loosen the version requirement on faraday?

### ISSUE THREAD

**Issue by cstyles** [getsentry/sentry-ruby#1424]
In #946 (included in the v3.0.0 release), the version of faraday that this gem depends on was bumped to `~> 1.0`. So in order to upgrade our app to the 3.x release series of this gem, we'd also have to upgrade the version of faraday that our app depends on. Unfortunately, we have a number of other gems that require a pre-1.0 version of faraday. I've seen other gems (e.g., [twilio-ruby](https://github.com/twilio/twilio-ruby/blob/3ee9e8fcc479e69b36262ab8e0ddbf670644025c/twilio-ruby.gemspec#L29), [restforce](https://github.com/restforce/restforce/blob/984ba8c42994bde89c6a646f83242f2f48690a42/restforce.gemspec#L27)) use a looser constraint by allowing versions between 0.9 and 2.0. Can we do something similar here? Or does this gem depend on something in faraday 1.x that makes that idea a nonstarter?

**Comment by st0012** [comment]
We won't update `sentry-raven` anymore except for very critical issues (like a security issue). So I recommend you to migrate  to the new SDK. All the extra features/bug fixes aside, the `sentry-ruby-core` gem has a no requirement and can potentially fit your app in this condition. Here's the [migration guide](https://docs.sentry.io/platforms/ruby/migration/).

**Comment by cstyles** [comment]
Sorry, I'm a little confused. Both the old `sentry-raven` and the new `sentry-ruby`gems require version >= 1.0 of `faraday`, right? So if I try to migrate from `sentry-raven` to `sentry-ruby` (which _is_ what I'm trying to do), I'll need to upgrade `faraday` to 1.x as well which isn't compatible with our other dependencies. There are newer versions of those gems that support version >= 1.0 of `faraday` but that means we'll have to update all of them (plus `sentry-raven` _and_ `faraday`) in one go which makes for a very large surface area for bugs to crop up. Ideally I could update each one individually and then, once we've verified that no bugs have been introduced, we could update `faraday` separately.

Again, loosening the version constraint to support 0.9.x only works if you're sure that `sentry-ruby` doesn't rely on anything in the 1.x series of `faraday`. Do you know if that's the case?

**Comment by st0012** [comment]
Sorry I should've stated this clearer, we have a gem called [sentry-ruby-core](https://rubygems.org/gems/sentry-ruby-core) that has no dependency version requirements.  `sentry-ruby` is a wrapper around it with version requirements.
