### ISSUE TITLE
Sentry events being sent from development

### ISSUE THREAD

**Issue by phiggins** [getsentry/sentry-ruby#143]
I noticed that in some scenarios I was seeing exceptions in a rails app in my local development environment triggering events being sent to the server. I first noticed this with a DelayedJob runner, but I am also able to repro this in a pry rails console:

```
$ rails c
** [Raven] Raven 0.6.0 ready to catch errors
Loading development environment (Rails 3.2.14)
[1] pry(main)> Raven.configuration.current_environment
=> "default"
[2] pry(main)> Raven.configuration.send_in_current_environment?
=> true
[3] pry(main)> Rails.env
=> "development"
```

I was able to workaround this by adding a line like this to the raven initializer:

```
require 'raven'                                                                  

Raven.configure do |config|                                                      
  # other stuff

  # Workaround a bug where this was being set to "default" instead of "development" in some scenarios.
  config.current_environment = Rails.env                                        
end   
```

I'm fine with the workaround, but I thought I would report this so it can hopefully be fixed in an upcoming version or help people who stumble across the same thing.

**Comment by dwickwire** [comment]
In case anyone else stumbles here like I did, the way to do this is by defining the environments you wish to use Raven with. 

Per the [docs](https://docs.getsentry.com/hosted/clients/ruby/integrations/rails/):
```
Raven.configure do |config|
  config.dsn = 'https://<key>:<secret>@app.getsentry.com/<project>'
  config.environments = ['staging', 'production']
end
```

**Comment by nateberkopec** [comment]
@dwickwire or, just use the `SENTRY_DSN` environment variable. If `SENTRY_DSN` is not set, Sentry won't start. 

If you're using `config.dsn`, you *must* use `config.environments` too, though.

**Comment by chevinbrown** [comment]
I strongly recommend that this is added to the documentation on the readme--especially since most people copy+pasta that.

**Comment by nateberkopec** [comment]
@chevinbrown https://github.com/getsentry/raven-ruby/blob/master/README.md#raven-only-runs-when-sentry_dsn-is-set

**Comment by chevinbrown** [comment]
I get it, it just doesn't seem conventional compared to how other reporting gems work. Just my 2 cents.

**Comment by skyeagle** [comment]
@nateberkopec having the code below still will trigger sending an error to Sentry even it's a blank value.

```ruby
Raven.configure do |config|
  config.dsn = ENV['SENTRY_DSN']
end
```

The only way to fix it is addding:

```ruby
  config.environments = %w(staging production)
```

It makes sense to add that documentation. thanks!

**Comment by ajsharp** [comment]
FWIW, this is not currently on the rails docs page: https://docs.sentry.io/clients/ruby/integrations/rails/

**Comment by ordinz** [comment]
```
  unless Rails.env.development?
    config.dsn = 'https://79a23988f0d24103a2d9760d3308331f@o1364576.ingest.sentry.io/6659028'
  end
```

**Comment by ordinz** [comment]
```ruby
  unless Rails.env.development?
    config.dsn = 'https://...@....ingest.sentry.io/....'
  end
```
