### ISSUE TITLE
How to pass information about authenticated user globally from Rails to Sentry?

### ISSUE THREAD

**Issue by mishrarohit** [getsentry/sentry-ruby#144]
From the README, the only mention of adding a global setting is [Global Tags.](https://github.com/getsentry/raven-ruby#tags) Tags seem unsuitable for passing information about `current_user`

I see mention of `user_context` in #68 and of `Sentry User Interfaces` in #10 . I am not able to figure out how to use either to pass information about a logged in user. Ideally, I would only like to pass the user id and not the whole user object which will require a separate Sentry Sanitizer as discussed in #39.

**Comment by owenstrevor** [comment]
Best answer is here in the official integrations guide: https://docs.sentry.io/clients/ruby/integrations/rails/

**Comment by woodardj** [comment]
Sentry docs have been reorganized, updated link: https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/identify-user/
