### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::ParameterFilter

### ISSUE THREAD

**Issue by cweilemann** [getsentry/sentry-ruby#1443]
**Describe the bug**
I've upgraded from `sentry-raven` to `sentry-ruby` (and `sentry-rails`/`sentry-sidekiq`), adjusted my config, and am now running into a `NameError: uninitialized constant ActiveSupport::ParameterFilter` exception on deployment.

**To Reproduce**
Upgrade from `sentry-raven` to the latest `sentry-ruby` (and `sentry-rails`/`sentry-sidekiq`), add create the attached /config/initializers/sentry.rb

**Expected behavior**
A successful deployment.

**Actual behavior**
```ruby
NameError: uninitialized constant ActiveSupport::ParameterFilter
/tmp/build_cca8055e/config/initializers/sentry.rb:16:in `block in <top (required)>'
```

**Environment**
 - Ruby Version: Ruby 2.6.6.
 - SDK Version: 4.4.2
 - Integration Versions (if any): Rails 5.2.6, Sidekiq 6.1.2

**Raven Config**

```ruby
Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]
  config.enabled_environments = %w[production]
  config.excluded_exceptions += ['ActionController::RoutingError', 'ActiveRecord::RecordNotFound']
  config.send_default_pii = true

  # To activate performance monitoring, set one of these options.
  # We recommend adjusting the value in production:
  config.traces_sample_rate = 0.5
  # or
  config.traces_sampler = lambda do |context|
    true
  end

  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, hint|
    # use Rails' parameter filter to sanitize the event
    filter.filter(event.to_hash)
  end

  config.async = lambda do |event, hint|
    Sentry::SendEventJob.perform_later(event, hint)
  end

  config.background_worker_threads = 2
end
```

**Comment by st0012** [comment]
Because you're using `Rails 5.2`, you should change `ActiveSupport::ParameterFilter` to `ActionDispatch::Http::ParameterFilter` in your `before_send` callback.

**Comment by cweilemann** [comment]
Thanks @st0012. This is what happens when I'm not regularly writing code any more. 🙄

**Comment by st0012** [comment]
@cweilemann no problem. I've also made it more clear in the document 🙂 
https://github.com/getsentry/sentry-docs/pull/3581
