### ISSUE TITLE
Release gems in batch

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1449]
## Current Workflow & Problems

Currently, all gems are all prepared and released individually. It's great for releasing patch version individually, but it also makes releasing minor versions complicated. Here's the general workflow:

1. Prepare `sentry-ruby`'s release
2. Wait for `sentry-ruby` to be published
3. Update integration gems' (like `sentry-rails`) `sentry-ruby-core` dependency version.
  - We can't do this before the release branch of `sentry-ruby` is merged to master.
4. Prepare integration gems' release individually
5. Wait for them to be published individually

Also, we can't have a shared changelog under the current releasing structure due to potential version collision.

## New Workflow

Definition of the new workflow:

- All gems (except `sentry-raven`) will always be released under the same version.
  - For example, to release `sentry-sidekiq` to `4.4.4`, other `sentry-*` gems will also be bumped and released with version `4.4.4`, regardless they have change or not.
- `sentry-raven` will still be released solely.
- New gems will firstly be released individually before joining the batch releasing process.

And the new release process will be:

1. Prepare batch release
2. Publish all of them at once 🙂

**Comment by st0012** [comment]
cc @HazAT @BYK

**Comment by HazAT** [comment]
Cool stuff, also we should have one changelog in release with different sections like we have in JS monorepo https://github.com/getsentry/sentry-javascript/releases/tag/6.4.1

So our users always can look at the release and changelog to understand what changed.
This will bring us a large step closer to making things easier for our users to version.

(The only downside is potential no-op releases for packages which is something we def. can live with)

**Comment by st0012** [comment]
@HazAT yeah that's part of the main drive behind this decision 😄

**Comment by st0012** [comment]
This is now completed with the help from @BYK 😉
