### ISSUE TITLE
How to use `config.before_send` to modify exception message

### ISSUE THREAD

**Issue by pk121** [getsentry/sentry-ruby#1489]
I'm using `sentry-raven` ruby client v2.13.0
I want to modify exception messages before forwarding to sentry.
Sometimes the exception messages are too large and exceed sentry request payload limit. I want to catch exceptions before reaching sentry and truncate the messages if the size exceeds some amount.
I read about `config.before_send` but I'm not sure how to use `event` or `hint` to modify the exception `message`. Kindly help on this. Thanks.

**Comment by st0012** [comment]
can you try this?
```ruby
config.before_send = lambda do |event, hint|
  event[:exception].values.each do |exception|
    exception.value = (exception.value || "").byteslice(0..8096)
  end
  event
end

**Comment by pk121** [comment]
Thanks Stan, that worked smooth.
We're a bit behind on our ruby upgrades, we're still using ruby 2.3. As soon as we upgrade to newer version, will make sure to switch to the new client :)

**Comment by st0012** [comment]
@pk121 I'm glad that it works! I'm closing this then.
