### ISSUE TITLE
sentry-resque does not have resque as a dependency

### ISSUE THREAD

**Issue by mensfeld** [getsentry/sentry-ruby#1502]
**Describe the bug**

```
cannot load such file -- resque
```

**To Reproduce**

```
gem install sentry-resque --no-doc
ruby -e 'require "sentry-resque"'
```

**Expected behavior**

I would expect it not to fail.

**Actual behavior**

```
.rbenv/versions/2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:148:in `require': cannot load such file -- resque (LoadError)
```

**Environment**
 - Ruby Version: 2.7.3
 - SDK Version: NA
 - Integration Versions (if any): None
  - e.g. Rails 6.0, Sidekiq 6.1.2

**Sentry Config**

None

**Comment by st0012** [comment]
Yeah I think it's better to declare the dependency, thanks. But just curious, why did you require `sentry-resque` without having `resque` installed?

**Comment by mensfeld** [comment]
I'm a security researcher and creator of https://diffend.io - we use a lot of automation to check security and quality of packages and it popped out :)

**Comment by st0012** [comment]
@mensfeld I see. I've added a PR to fix it. Thanks again 👍
