### ISSUE TITLE
`Sentry.capture_message` can't send a message from Rake

### ISSUE THREAD

**Issue by y-yagi** [getsentry/sentry-ruby#1508]
**Describe the bug**

`Sentry.capture_message` can't send a message from Rake.

This is a similar to #1324. I think message doesn't send because of process exit before send a message. A exception can be sent because `sentry-ruby` override `display_error_message` and specify `background: false` inside it.   
https://github.com/getsentry/sentry-ruby/blob/bae8c5be5a8d34ed9cade27c7d18c13bac86c521/sentry-ruby/lib/sentry/rake.rb#L7-L12

So I think this only happens in case of Sentry.capture_message` used.

**To Reproduce**

Add a following rake task and run it.

```rake 
namespace :dummy do
  desc 'Send a message Sentry'
  task test_sentry: :environment do
    Sentry.capture_message("Raise an exception for Sentry from Rake")
  end
end
```

```bash
$ bin/rails dummy:test_sentry
```

**Expected behavior**

Message send our sentry project.

**Actual behavior**

No message is being logged.

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: 4.6.1
 - Rails 6.0.3.7

**Comment by st0012** [comment]
@y-yagi thanks for reporting this. I'll fix it this week.

**Comment by st0012** [comment]
@y-yagi I've added #1509 for the issue.
