### ISSUE TITLE
Conflict with scout_apm gem

### ISSUE THREAD

**Issue by Riddlerrr** [getsentry/sentry-ruby#1516]
After upgrade sentry-* gems from sentry 4.3.4 => 4.6.2 it starts conflict with `scout_apm` gem.

It goes to infinity loop on any Net::HTTP call from application:

Trace output:
```
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/tracer.rb:34:in `instrument'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/tracer.rb:44:in `instrument'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.6.2/lib/sentry/net/http.rb:38:in `request'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/tracer.rb:34:in `instrument'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/tracer.rb:44:in `instrument'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.6.2/lib/sentry/net/http.rb:38:in `request'
Jul 25 20:10:59   /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
...
```

Disabling one of those gems fix the issue.
I tried to upgrade both gems to the latest versions but it didn't help.

My guessing it was broken in https://github.com/getsentry/sentry-ruby/commit/e4b6d66612d9ce601596c23a5dd0d035c559d980

With 4.3.4 sentry version it was work fine

**To Reproduce**

Gemfile:
```
gem 'sentry-rails', '~> 4.6'
gem 'sentry-ruby', '~> 4.6'

gem 'scout_apm'
```

- set required ENVs for both gems
- Do any Net::HTTP request from the app

**Expected behavior**

Send logs to both gems

**Actual behavior**

Stuck in infinite loop

**Environment**
 - Ruby Version: 2.7.1

**Sentry Config**

Default config

**Comment by st0012** [comment]
This is due to the conflict between the approaches `sentry-ruby` and `scout_apm` use to patch `Net::HTTP`. The original issue: https://github.com/getsentry/sentry-ruby/issues/1427

The latest update is that `scout_apm` said they'll switch to the same `prepend` approach to avoid the conflict: https://github.com/scoutapp/scout_apm_ruby/pull/402#issuecomment-846480983

**Comment by Riddlerrr** [comment]
@st0012 Thanks for details! I've closing the issue in favour to #1427
