### ISSUE TITLE
question/docs: Active support instrumentation explanation?

### ISSUE THREAD

**Issue by josh-m-sharpe** [getsentry/sentry-ruby#1518]
the sentry-rails docs state:

```
  # this gem also provides a new breadcrumb logger that accepts instrumentations from ActiveSupport
  # it's not activated by default, but you can enable it with
  config.breadcrumbs_logger = [:active_support_logger]
```

I'm not sure what that means.  What are 'instrumentation from ActiveSupport' ?

**Comment by st0012** [comment]
ActiveSupport instrumentation: https://guides.rubyonrails.org/active_support_instrumentation.html

**Comment by st0012** [comment]
I've added the link to document as well. closing this.
