### ISSUE TITLE
docs inconsistency: inspect_exception_causes_for_exclusion default value

### ISSUE THREAD

**Issue by josh-m-sharpe** [getsentry/sentry-ruby#1519]
https://docs.sentry.io/platforms/ruby/configuration/options/ (see inspect_exception_causes_for_exclusion) -> says false

https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/configuration.rb#L92 -> says false

appears to actually be true?

https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/configuration.rb#L195

2.6.8 :006 > Sentry.configuration.inspect_exception_causes_for_exclusion
 => true

**Comment by st0012** [comment]
Sorry for the confusion. It's been changed to default since `4.2.0`. I'll update docs.
