### ISSUE TITLE
Allow configuring breadcrumbs log level

### ISSUE THREAD

**Issue by kostyanf14** [getsentry/sentry-ruby#1526]
**Describe the idea**

Currently, sentry-ruby allows configuring only breadcrumbs buffer size. I suggest adding the ability to configure breadcrumbs log level to filter what crumbs are recorded.

**Why do you think it's beneficial to most of the users**

For example, some project has a lot of debug logs that are used during development but are disabled in production. I think that it's better to skip these debug logs from breadcrumbs. This would allow having real info/warning logs in breadcrumbs w/o unnecessary debug log and w/o increasing breadcrumbs log buffer size.

**Possible implementation**

PR https://github.com/getsentry/sentry-ruby/pull/1525

**Comment by st0012** [comment]
I see. Thanks for proposing this 👍 

However, currently only `sentry_logger` captures logs from Ruby loggers. Other breadcrumb loggers like `http_logger` and `sentry-rails`'s `active_support_logger` don't have the level concept. So I don't think adding a global config option is the best solution here.

I think you can already use the `config.before_breadcrumb` for this. For example:

```ruby
config.before_breadcrumb = lambda do |breadcrumb, _hint|
  if breadcrumb.level == "debug"
    nil
  else
    breadcrumb
  end
end
```

I'm also considering adding the `severity` info to the hint, so it'd be possible to further simplify it to:

```ruby
config.before_breadcrumb = lambda do |breadcrumb, hint|
  if severity = hint[:severity] && severity <= 1 # debug & info
    nil
  else
    breadcrumb
  end    
end
```

But for skipping debug breadcrumbs, I think the first example should do the job.

**Comment by kostyanf14** [comment]
Thanks for your idea. I will use your solution. 

You are right, that only `sentry_logger` has the level concept, but from my point of view, this option can be used with custom breadcrumbs.

Anyway, feel free to close this issue and corresponding PR, if think that the global config option is redundant. Or leave it for the future, when other breadcrumb loggers have the level concept.

**Comment by st0012** [comment]
I don't think the config will be needed in the near future. So I'm closing this and the PR.

Thanks again for raising this use case though. I also opened https://github.com/getsentry/sentry-ruby/pull/1527 to add more hint for `sentry_logger`'s users 🙂
