### ISSUE TITLE
Sentry.start_transaction with name not work correctly

### ISSUE THREAD

**Issue by elct9620** [getsentry/sentry-ruby#1540]
**Describe the bug**

When using `Sentry.start_transaction` with name, the Sentry receives `<unlabeled transaction>` instead of configured name.

**To Reproduce**

```ruby
transaction = Sentry.start_transaction(name: "GameServer#command", op: "execute_command")
# Do something
transaction.finish
```

**Expected behavior**

![截圖 2021-08-18 下午10 06 15](https://user-images.githubusercontent.com/887984/129912894-cfacee2e-79cb-4dcd-b9ca-d08cd5ef7a1c.png)

Above result should use `Sentry.get_current_scope.set_transaction_name` to generate it.

```ruby
Sentry.get_current_scope.set_transaction_name("GameServer#command")
transaction = Sentry.start_transaction(op: "execute_command")
# Do something
transaction.finish
```

According to the source code, the Scope keeps a `transaction_names` array as the Sentry event `transaction` name, but the `Sentry::Transaction#name` is correctly configured but not used in Sentry event.

**Actual behavior**

![截圖 2021-08-18 下午10 06 12](https://user-images.githubusercontent.com/887984/129912883-129d0a94-8d5f-4776-a0c6-7f04d9802dfc.png)

**Environment**
 - Ruby Version:  2.7.3
 - SDK Version: 4.6.5
 - Integration Versions (if any): N/A

**Sentry Config**

This is not necessary but could be helpful.

```ruby
Sentry.init do |config|
  config.breadcrumbs_logger = [:sentry_logger, :http_logger]
  config.traces_sample_rate = ENV.fetch('SENTRY_SAMPLE_RATE', 1).to_f
end
```

**Comment by st0012** [comment]
@elct9620 thanks for catching this issue 👍 I've opened #1546 to address it 🙂
