### ISSUE TITLE
Implicit dependency of sentry-rails in sentry-resque

### ISSUE THREAD

**Issue by adi-pen** [getsentry/sentry-ruby#1541]
**Describe the bug**

https://github.com/getsentry/sentry-ruby/blob/a50bf1fe517c8882600445dd3ecd664b961ac160/sentry-resque/lib/sentry-resque.rb#L19

This line in `sentry-resque` results in ```undefined method `rails' for #<Sentry::Configuration:*``` in rails applications that do not use `sentry-rails`.

**To Reproduce**

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org' do
    gem 'rails'
    gem 'sentry-resque'
    # gem 'sentry-rails'
  end
end

require "resque"
require "sentry-resque"

require "rails"
require "action_dispatch"

class TestApp < Rails::Application
  Sentry.init do |config|
    config.breadcrumbs_logger = [:sentry_logger]
    config.dsn = 'https://aaaa@xxxx.ingest.sentry.io/123456'
  end
end

TestApp.initialize!
```

**Expected behavior**

It should not result in `NoMethodError`.

**Actual behavior**

```
undefined method `rails' for #<Sentry::Configuration:0x00007f9397b2ae08> (NoMethodError)
```

**Comment by st0012** [comment]
@adi-pen just curious, why do you use `sentry-resque` to integrate Sentry with your Resque but not `sentry-rails` for your Rails app?

**Comment by adi-pen** [comment]
@st0012 We switched from [resque-sentry](https://github.com/gocardless/resque-sentry) to sentry-resque and ran into this NoMethodError.  The existing logic within the rails app is acting as a substitute for sentry-rails at the moment and it'll change in the near future.

**Comment by st0012** [comment]
ah I see. thanks for explaining 👍
I’ll fix it 🙂
