### ISSUE TITLE
report_after_job_retries does not report errors for jobs with 0 retries

### ISSUE THREAD

**Issue by TAGraves** [getsentry/sentry-ruby#1556]
**Describe the bug**
I was excited to see the `report_after_job_retries` feature get released in sentry-sidekiq this morning. Unfortunately we have many jobs configured with `sidekiq_options retry: 0` and failures in these jobs do not appear to be sent to Sentry. Thankfully the fix looks pretty simple so I will open a PR with an attempt at fixing it.

**To Reproduce**
Set `config.sidekiq.report_after_job_retries = true` and then configure a job that will fail with `sidekiq_options retry: 0`. Enqueue that job and observe that it ends up in the Sidekiq dead queue and does not report the error to Sentry.

**Expected behavior**
The error should be reported to Sentry.

**Actual behavior**
The error is not reported to Sentry.

**Environment**
 - Ruby Version: 3.0.2
 - SDK Version: 4.7
 - Integration Versions (if any): Sidekiq 6.2.2

**Sentry Config**

```ruby
Sentry.init do |config|
  config.sidekiq.report_after_job_retries = true
end
```

**Comment by st0012** [comment]
@TAGraves your fix has been released now. thanks again 🙂
