### ISSUE TITLE
Rails integration: trace Active Storage events

### ISSUE THREAD

**Issue by georgeclaghorn** [getsentry/sentry-ruby#1558]
Rails’s [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html) component generates the following `ActiveSupport::Notifications` events:

* `service_upload.active_storage`
* `service_download.active_storage`
* `service_streaming_download.active_storage`
* `service_download_chunk.active_storage`
* `service_delete.active_storage`
* `service_delete_prefixed.active_storage`
* `service_exist.active_storage`
* `service_url.active_storage`
* `service_mirror.active_storage`
* `service_update_metadata.active_storage`
* `preview.active_storage`
* `analyze.active_storage`

More on these events is available [here](https://edgeguides.rubyonrails.org/active_support_instrumentation.html#active-storage). All are worth tracing, except maybe `service_url`, as they’re likely to be responsible for a significant portion of runtime in transactions where they occur. For example, here’s a request in Sentry where uploading to S3 takes the majority of the total duration but isn’t represented:

![Sentry performance tab screenshot](https://user-images.githubusercontent.com/94129/131759875-0b6760fb-da4e-48d8-ae8e-653ff2011b57.png)

I think this should be relatively straightforward using the existing subscriber system in `sentry-rails`.

**Comment by st0012** [comment]
@georgeclaghorn thanks for the suggestion. I'll add it in version `4.8.0` 🙂

**Comment by st0012** [comment]
@georgeclaghorn I've implemented the feature in https://github.com/getsentry/sentry-ruby/pull/1588. But because I can only test it against the simple example app locally, it'd be great if you can also test this branch (even just locally) before I merge it 🙂
