### ISSUE TITLE
Exceptions from ActiveJob with Resque backend are not captured on Sentry

### ISSUE THREAD

**Issue by tsrivishnu** [getsentry/sentry-ruby#1559]
**Describe the bug**

Exceptions from ActiveJob jobs are not sent to Sentry. The jobs simply fail and no errors are sent to Sentry. 

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2265280/131824846-dc24d011-1116-46b0-b233-cd84eafd25b5.png">

I'm not sure if I'm missing any configuration options for this to work correctly.

**To Reproduce**

```ruby
Rails.application.config.active_job.queue_adapter = :resque

class ApplicationJob < ActiveJob::Base
end

class MyJob < ApplicationJob
  def perform
    raise "foo"
  end
end

MyJob.perform_later
```

```console
$ bundle exec rake environment resque:work QUEUE=*
```

**Expected behavior**

`foo` RuntimeError is captured and sent to Sentry

**Actual behavior**

`foo` RuntimeError is not captured and not sent to Sentry

**Environment**
 - Ruby Version: 2.7.1
 - SDK Version: 4.7.1
 - Integration Versions (if any):
   - Rails 6.1.3.2, 
   - Resque 2.0.0,
   - sentry-rails 4.7.1

**Sentry Config**

```ruby
Sentry.init do |config|
  config.dsn = "..."
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # Sent events only for the below environments
  config.enabled_environments = %w[ development staging production ]

  config.background_worker_threads = 0

  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, _hint|
    filter.filter(event.to_hash)
  end
end
```

**Comment by tsrivishnu** [comment]
Explicitly sending a message works both from rails console or from with the job's `perform` method. 

I will try to reproduce in a sample app and push that.

**Comment by tsrivishnu** [comment]
Here is the test app: https://github.com/tsrivishnu/rails-sentry-resque-active-job-test. I included instructions to run it in docker with docker-compose. 

Let me know if you face any issues.

Correction to my previous comment.
Manually sending message with `Sentry.capture_message` works from console but not from the job's `perform` method.

**Comment by st0012** [comment]
@tsrivishnu ok it's because resque worker doesn't contain either `RAILS_ENV` or `RACK_ENV`, so the SDK uses a default `"default"` environment (inherited from the old SDK). and because it's not in your `enabled_environments`, event capturing is disabled.

I think you can make it work by adding `default` to the list.

I'll make a PR to change the default environment to `'development'`.

**Comment by tsrivishnu** [comment]
@st0012 Thank you. I confirm that it works after adding `default` to the `enabled_environments` list or passing `RAILS_ENV=development` to the Resque worker. 👍🏽 

Feel free to close this issue or keep it open for you to track the PR to change the default environment to 'development'.
