### ISSUE TITLE
Confusing report_after_job_retries

### ISSUE THREAD

**Issue by Math3v** [getsentry/sentry-ruby#1560]
Hello guys 👋 

I recently came accross the `report_after_job_retries` configuration option that is available for both Sidekiq and DelayedJob.

I have two things:

1. IMHO it's only documented for the [DelayedJob](https://docs.sentry.io/platforms/ruby/guides/rack/configuration/integration_options/#sentry-delayed_job) and I could not find it in [Sidekiq's configuration docs](https://docs.sentry.io/platforms/ruby/guides/sidekiq/configuration/options/). 
2. I find the configuration name a bit confusing and wanted to double-check. 🙏  The name suggest: "Report after [every] job retries", so I'd assume if we set it to `true`, we will get a message for every failure while according to the [implementation](https://github.com/getsentry/sentry-ruby/blob/master/sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb#L16) it's the other way around. 🤔

**Comment by st0012** [comment]
@Math3v it means "report after all retries". the SDK by default reports every single exception. this options is to report only the last failure.

as for the missing document, I'll update that shortly.
