### ISSUE TITLE
Cannot initialize with `report_after_job_retries`

### ISSUE THREAD

**Issue by Math3v** [getsentry/sentry-ruby#1562]
**Describe the bug**
Sentry's is failing to initialize when passing the report_after_job_retries option for Sidekiq integration.

**To Reproduce**
See init below. Fails with:
```
/app/config/initializers/sentry.rb:15:in `block in <main>': undefined method `sidekiq' for #<Sentry::Configuration:0x0000558a1bcdd020> (NoMethodError)
```

**Environment**
 - Ruby Version:  2.7.x
 - SDK Version: 4.6.5
 - Integration Versions (if any):
Sidekiq 4.6.4

**Sentry Config**

```ruby
Sentry.init do |config|
  config.sidekiq.report_after_job_retries = true
end
```

Am I misunderstanding how to set this configuration option correctly? 🙏

**Comment by st0012** [comment]
It’s only available after 4.7.0 🙂
