### ISSUE TITLE
No transport_failure_callback replacement in Sentry-Ruby

### ISSUE THREAD

**Issue by pyromaniac** [getsentry/sentry-ruby#1583]
Hello, I'm migrating to sentry-ruby and didn't find any substitute for the `transport_failure_callback` option. I checked the code and the only thing it does - raises `Sentry::ExternalError`.

I see 2 potential solutions here:
1. Either provide similar callback under `transport` config option.
2. Or report the problem with the logger in a `fatal` level so we could log it somewhere.

For now I'm trying to do something like:

```
  transport = Class.new(Sentry::HTTPTransport) do
    def send_data(data)
      super
    rescue Sentry::ExternalError => e
      LogStasher.fatal("[Sentry] Transport failure", data: data.pretty_inspect, error: e)
    end
  end
  config.transport.transport_class = transport
```

But it fails with an exception ```gems/sentry-ruby-core-4.7.3/lib/sentry/transport/http_transport.rb:121:in `set_conn': undefined method `server' for nil:NilClass (NoMethodError)``` and looks generally fragile.

**Comment by st0012** [comment]
@pyromaniac We removed the option universally (cross all SDKs) because it's not helpful to most users and was misused from time to time. However, if you still want to capture external failures, using your customized Transport class is the recommended way. I think you can avoid the error by placing the code like this:

```rb
transport = Class.new(Sentry::HTTPTransport) do
  def send_data(data)
    super
  rescue Sentry::ExternalError => e
    LogStasher.fatal("[Sentry] Transport failure", data: data.pretty_inspect, error: e)
  end
end

Sentry.init do |config|
  # ...
end
```

**Comment by pyromaniac** [comment]
Hey @st0012 . Thanks for the explanation. Unfortunately, the suggested approach doesn't work as well. Fails with the same exception.

**Comment by st0012** [comment]
@pyromaniac I tested it in my app and it worked 🤔 
would you mind sharing your Sentry config?

**Comment by pyromaniac** [comment]
Sure, so far it is:

`config/initializers/sentry.rb`

```ruby
Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"] if ENV["SENTRY_DSN"].present? # This is unnecessary but left for explicitness
  config.traces_sample_rate = Float(ENV["SENTRY_TRACES_SAMPLE_RATE"]) if ENV["SENTRY_TRACES_SAMPLE_RATE"].present?
  config.send_default_pii = true # Send request body as well

  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, _hint|
    filter.filter(event.to_hash)
  end
end
```

**Comment by basherru** [comment]
@pyromaniac This is being caused by an empty dsn, you may always set the dsn and use `enabled_environments` to limit the environments.

**Comment by pyromaniac** [comment]
Ah, I see, so `config.transport.transport_class = transport if config.dsn` might work as well, right?
