### ISSUE TITLE
Configuring Tracing for Sidekiq

### ISSUE THREAD

**Issue by choxi** [getsentry/sentry-ruby#1586]
What is the recommended way to pass a trace ID from Rails to a Sidekiq worker? I have this configuration:

```ruby
# config/initializers/sentry.rb

Sentry.init do |config|
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # Ignore 404s
  config.excluded_exceptions += ['ActionController::RoutingError']

  config.traces_sample_rate = 1.0
end
```

and

```ruby
# Gemfile
gem "sentry-rails"
gem "sentry-sidekiq"
```

When I queue a Sidekiq job:

```ruby
class PostsController < ApplicationController
  def create
    # How do I pass the trace_id to the worker?
    PostsWorker.perform_async(post_id, trace_id)
  end
end

class PostsWorker
  include Sidekiq::Worker
  
  def perform(post_id, trace_id)
    # How do I set the trace_id in the worker?
    Sentry.set_trace_id(trace_id)
  end
end
```

It currently starts a separate trace for the controller and the worker, but I'd like the worker to belong to the same trace as the request. Is there a way to do this?

**Comment by st0012** [comment]
@choxi currently it's not possible without adding your own Sidekiq client middleware. but I think this is something we should support natively. so I'll implement it in a future release 🙂

**Comment by choxi** [comment]
@st0012 it's working, thank you!

**Comment by choxi** [comment]
One related question: if our frontend is sending `sentry-trace` headers, will the backend always capture those even if it goes over the sample rate? Is there a way to make sure we always capture the full trace when the sample rate is < 1?
