### ISSUE TITLE
Sentry Tunnel Rails Engine

### ISSUE THREAD

**Issue by robguthrie** [getsentry/sentry-ruby#1597]
I'm starting to notice that clients are blocking the sentry requests from their browser. :(

I looked into your documentation and see that you recommend a tunnel. 

I'm not sure how to translate the PHP example into a Rails example, Do you have some example code for implementing a sentry tunnel into Rails?

I figure it could be a good use case for a rails engine that users of the sentry-rails gem could include easily.

**Comment by sl0thentr0py** [comment]
Hey @robguthrie, sorry it took a while to get my hands free and test it out but I've added a rails tunneling example in our docs now. They will take a while to get merged/go online but you can check out the code sample [here](https://github.com/getsentry/sentry-docs/pull/4361/files#diff-23d8ab7811d8d020edb23c1bc636a0d8a2573c73925b24cea677972bb51a05bf).

**Comment by robguthrie** [comment]
oh that was quick! Thank you. That has made my day!

**Comment by sl0thentr0py** [comment]
closing this now, pls reopen if you need more help

**Comment by robguthrie** [comment]
@sl0thentr0py just wanted to say thanks again. I'm running a tunnel based off that example and it works well.

**Comment by wilg** [comment]
I had a couple of issues with the documented sentry tunnel code. Primarily it would throw an exception when attempting to proxy replay sessions, because Rails mangles the body. Replacing `request.body.read` with `request.raw_post` fixed that. I also made sure to return a 500 status if the tunnel fails, otherwise things like the feedback controller will appear to work but swallow errors.

Here is my current controller: 

```rb
class SentryTunnelController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:sentry_tunnel]

  SENTRY_HOST = "oxxxxxxxxxxxxxxxxxxxx.ingest.us.sentry.io"
  SENTRY_PROJECT_IDS = ["xxxxxxxxxxxxxxxxxxxx"]

  def sentry_tunnel
    envelope = request.raw_post
    piece = envelope.split("\n").first

    raise "Invalid sentry envelope" if piece.nil?

    header = JSON.parse(piece)
    dsn = URI.parse(header["dsn"])
    project_id = dsn.path.tr("/", "")

    raise "Invalid sentry hostname: #{dsn.hostname}" if dsn.hostname != SENTRY_HOST
    raise "Invalid sentry project id: #{project_id}" unless SENTRY_PROJECT_IDS.include?(project_id)

    upstream_sentry_url = "https://#{SENTRY_HOST}/api/#{project_id}/envelope/"
    Net::HTTP.post(URI(upstream_sentry_url), envelope)

    head :ok
  rescue => e
    Rails.logger.error("error tunneling to sentry")
    Rails.logger.error(e)
    Sentry.capture_exception(e)
    render plain: e.message, status: :internal_server_error
  end
end
```
