### ISSUE TITLE
Ruby: configuration.rb:406: warning: instance variable @dsn not initialized

### ISSUE THREAD

**Issue by bkazez** [getsentry/sentry-ruby#1615]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When running ruby with `-w`, I get this warning repeatedly:

```
sentry-ruby-core-4.7.2/lib/sentry/configuration.rb:406: warning: instance variable @dsn not initialized
```

### Expected Result

No warnings

### Actual Result

```
sentry-ruby-core-4.7.2/lib/sentry/configuration.rb:406: warning: instance variable @dsn not initialized
```

**Comment by st0012** [comment]
@bkazez thanks for reporting this, I think it's been fixed in `4.8.0`. can you give it a look?
