### ISSUE TITLE
Alternatives for config.tags?

### ISSUE THREAD

**Issue by inductor** [getsentry/sentry-ruby#1620]
Helllo, I saw Raven is now deprecated and `config.tags` is removed in the new Ruby/Rails SDK.

I used to use `config.tags` to add an environmentally specific information to Sentry logs, such as Kubernetes namespace and workload label/name.

Now I only see context/scope level tagging in the new SDK, but is there any way to set a global scope tagging to each log?

**Comment by st0012** [comment]
I think you can achieve this by adding `Sentry.set_tags(key: val)` right after the `Sentry.init` call:

```rb

Sentry.init do |config|
  # ....
end

Sentry.set_tags(foo: "bar")
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Somehow this is only working in web server processes, but not in our Sidekiq workers?
Anybody knows why and if there is an alternative?

**Comment by st0012** [comment]
@h0jeZvgoxFepBQ2C this approach should work with all applications. can you open an issue with a demo script/app?
