### ISSUE TITLE
Add a "request body" size option for HTTP request logging

### ISSUE THREAD

**Issue by awei82** [getsentry/sentry-ruby#1633]
**Describe the idea**
Add a "request body" size configuration option for HTTP request logging, basically identical to this implementation: https://docs.sentry.io/platforms/python/guides/logging/configuration/options/#request-bodies

**Why do you think it's beneficial to most of the users**
It'll allow us to control the size of the request body being logged. We want log request bodies, but also want to avoid capturing huge data blobs.

**Possible implementation**
This could probably be a straight port from the Python implementation from the link above.

**Comment by st0012** [comment]
@awei82 I'm not sure about defining size options as there's no standard for that. what do you think about using byte length instead? for example, the current size is `4096 * 4` and you may only want `4096`, so you just use it like:

```rb
config.request_body_size = 4096
```

**Comment by awei82** [comment]
@st0012 sorry for the slow response - having the request body option be a size is totally fine with me. Thanks!
