### ISSUE TITLE
`capture_message` generates exception on message including percent symbol

### ISSUE THREAD

**Issue by piloos** [getsentry/sentry-ruby#1634]
### Issue Description

Using `sentry-raven` version `3.1.2`.

When manually capturing an exception and using a percent symbol (`%`) in the string an exception is triggered.

### Reproduction Steps

`Raven.capture_message("I am only 50% sure that this is an issue")`

### Expected Behavior

No exception

### Actual Behavior

Exception:

```
ArgumentError: invalid value for Integer(): "..."
  from sentry-raven (3.1.1) lib/raven/interfaces/message.rb:13:in `%'
  from sentry-raven (3.1.1) lib/raven/interfaces/message.rb:13:in `unformatted_message'
  from sentry-raven (3.1.1) lib/raven/event.rb:86:in `message'
  from sentry-raven (3.1.1) lib/raven/event.rb:139:in `public_send'
  from sentry-raven (3.1.1) lib/raven/event.rb:139:in `block in to_hash'
  from sentry-raven (3.1.1) lib/raven/event.rb:138:in `each'
  from sentry-raven (3.1.1) lib/raven/event.rb:138:in `each_with_object'
  from sentry-raven (3.1.1) lib/raven/event.rb:138:in `to_hash'
  from sentry-raven (3.1.1) lib/raven/client.rb:34:in `send_event'
  from sentry-raven (3.1.1) lib/raven/instance.rb:83:in `send_event'
  from sentry-raven (3.1.1) lib/raven/instance.rb:131:in `capture_type'
```

### Ruby Version

2.7.3

### SDK Version

?

### Integration and Its Version

Rails 6

### Sentry Config

```
  Raven.configure do |config|
    config.dsn = 'https://xxx'
  end
```

**Comment by piloos** [comment]
Bump

**Comment by st0012** [comment]
@piloos Thanks for reporting the issue. But given that `sentry-raven` SDK doesn't receive much update anymore, it'll probably take a while before we can patch this. So I'd recommend you to migrate to `sentry-ruby` if that's possible, which I don't think has the same issue.
