### ISSUE TITLE
Custom insertion of Sentry::Rails::CaptureExceptions middleware

### ISSUE THREAD

**Issue by ThomasSevestre** [getsentry/sentry-ruby#1639]
**Describe the idea**

Insertion of `Sentry::Rails::CaptureExceptions` is hardcoded after `ActionDispatch::Executor`. `ActionDispatch::Executor` is a good place to insert middlewares and rails applications may insert middlewares at the same place, in `production.rb` for instance.

This leads to this middlware order :
```
$ rails middlewares
...
use ActionDispatch::Executor
use Sentry::Rails::CaptureExceptions
use MyCustomMiddleware
...
```

which might break `Sentry::Rails::CaptureExceptions` while this order works as expected :
```
$ rails middlewares
...
use ActionDispatch::Executor
use MyCustomMiddleware
use Sentry::Rails::CaptureExceptions
...
```

**Possible implementation**

With a new configuration parameter in `Sentry.init` block.

**Comment by ThomasSevestre** [comment]
In order to do that, I have to make sure sentry middleware is inserted before I insert my middlware, which is not the case at the moment.

The natural place to insert custom middleware is in `application.rb`, `production.rb`, etc.
The natural place to load sentry is to create an initializer.
This leads to the "wrong" order. I'm sure I can find a workaround but it would be simplier to have a config parameter.

This is just a suggestion, feel free to close if do not want to add a new configuration parameter for this

**Comment by st0012** [comment]
> In order to do that, I have to make sure sentry middleware is inserted before I insert my middlware, which is not the case at the moment.

I understand the problem, but because of how things are loaded, I don't think a new config would help either:

```
application.rb is loaded
=> Booting Puma
=> Rails 6.1.4.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Sentry adds middleware
Sentry.init is called
```

As you can see, `sentry-rails`'s `sentry.use_rack_middleware` initializer is loaded before `Sentry.init` is even called. I'm afraid this isn't configurable from the SDK level.
