### ISSUE TITLE
Make the rake auto-capturing optional

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#1646]
**Describe the idea**
Currently the rake capturing is enabled automatically. Try to make this optional.

**Why do you think it's beneficial to most of the users**
We got a support request where they wanted to turn this off.

**Possible implementation**
Not sure how to expose this best on the `init` API because we don't really tell people to use `register_integration` for the ruby SDK.

**Comment by st0012** [comment]
@sl0thentr0py I think it can already be turned off with `config.skip_rake_integration = true`?

**Comment by sl0thentr0py** [comment]
@st0012 oh lol thanks, I am blind..
