### ISSUE TITLE
How exactly do I set Devise session data for authenticated users?

### ISSUE THREAD

**Issue by altjx** [getsentry/sentry-ruby#1648]
I'm evaluating BugSnag and Sentry.io and, while I like Sentry.io a lot more, there are just two things that I can't quite figure out after reading the documentation:

1. How to set the user's information if they are authenticated
2. How to expand the before/after view of the error line (to get more context)

I find that Bugsnag automates the whole Devise integration thing, so this is super easy. However, according to [this documentation](https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/identify-user/), we just have to set the user's details manually. However, I'm not exactly sure where this needs to be set.

For the 2nd item (a little off-topic), is there any way to _extend_ the before/after view of the error line to get more context of the issue? Perhaps the 5 lines before and after the error?

EDIT:

Got the first issue implemented by putting this method in the `authenticate_user!` method (for Devise).

**Comment by altjx** [comment]
Just solved the 2nd point after digging through the source code and finding `context_lines`. I set this to 5 and now this looks great.

**Comment by st0012** [comment]
@altjx good to see your issues are all sorted! I'm sorry that I missed the `context_lines` in the document. I've added https://github.com/getsentry/sentry-docs/pull/4536 to fix it.

**Comment by altjx** [comment]
Thanks a lot @st0012 no problem at all! Loving the product! 🙌🏽

**Comment by altjx** [comment]
@st0012 quick question - the default seemed to have been 0 for me because it only showed the single line that caused the error (nothing before or after). I noticed in the PR it mentioned 3. Is that specific to maybe a different framework other than rails? I actually had to set mine to 3 manually.

**Comment by st0012** [comment]
hmm that's weird. here's what I just tested:

```rb
Loading development environment (Rails 6.1.4.4)
irb(main):001:0> Sentry.configuration.context_lines
=> 3
irb(main):002:0>
```

what's the SDK version you're using?
