### ISSUE TITLE
Confused by transaction name

### ISSUE THREAD

**Issue by altjx** [getsentry/sentry-ruby#1649]
This may or may not be similar to #488.

Basically, I set up my initializer to ignore a transaction name based on what I see in Sentry; however, I just realized that what I'm seeing in the UI may not actually be accurate. 

For example, a route in Rails that says "get /blahblah to randomcontroller#hello_world".

In the Sentry dashboard, the transaction name will show up as randomcontroller#hello_world. In my case I'm looking for the transaction name of /hello/, but it turns out this isn't working. 

Should I be looking for /blah instead of /hello/ because the rails route comes in as /blah?

**Comment by st0012** [comment]
@altjx the issue is similar to https://github.com/getsentry/sentry-ruby/issues/1429

long story short: it's by design (or you can say it's a technical limitation atm). so you need to use request path for sampling instead of the controller#action pattern.

**Comment by altjx** [comment]
Got it. Thanks @st0012 ! 🙌🏽
