### ISSUE TITLE
API methods used in the migration guide do not appear in RDoc

### ISSUE THREAD

**Issue by geeksam** [getsentry/sentry-ruby#1657]
### Issue Description

I wanted to update Faraday on an older application, but the `sentry-raven` dependency was preventing it.  YAK SHAVING, HERE WE COME!

### Reproduction Steps

- In the application's Gemfile, replace `sentry-raven` with `sentry-rails` and `sentry-ruby` and run `bundle`
- Get a failure message about the Gemfile.lock being locked to an older version of Faraday
- Run `bundle update faraday`
- Update `config/initializers/sentry.rb`
- Grep the project for references to `Raven`
  - `.capture_exception` is easy enough...
  - `Raven.user_context` doesn't seem to have an equivalent.  Consult [migration guide](https://docs.sentry.io/platforms/ruby/migration/), see mention of `Sentry.set_user` method instead
  - Download the RDoc for both `sentry-ruby` and `sentry-rails` into, e.g., [Dash](https://kapeli.com/dash)
  - Search for `set_user` in the RDoc for both `sentry-rails` and `sentry-ruby`

### Expected Behavior

Documentation that describes the shape of data that MUST/SHOULD/MAY (see [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119)) be passed to the `Sentry.set_user` method.

### Actual Behavior

The `Sentry.set_user` method does not appear in the docs at all.

### Ruby Version

all

### SDK Version

4.8.1

**Comment by st0012** [comment]
@geeksam hey sorry for the missing docs. I'm adding them recently and they should go out with the `v4.9.0` release.

- https://github.com/getsentry/sentry-ruby/pull/1635
- https://github.com/getsentry/sentry-ruby/issues/1636

**Comment by geeksam** [comment]
Thanks so much!  (Sorry for the delay in replying; way too much email over the weekend.)
