### ISSUE TITLE
Sync span operation names

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#1674]
Update all relevant span operation names to match the docs here
https://develop.sentry.dev/sdk/performance/span-operations/

This is necessary for users to use some of the newer Performance dashboard features like slow db and http ops.

![image](https://user-images.githubusercontent.com/6536764/148569851-13368be3-9461-4276-b61b-5bf456bbe66e.png)

**Comment by st0012** [comment]
Some thought on the change:
1. It should be seen as breaking change as it'll could how people filtering transactions.
2. Given that the target of `v5.0` is to get people off `faraday` as easy as possible, I think there should be no other breaking change in that release.
3. Considering the above points, I think we can give it `v6.0`? Which may be released around March or April.

**Comment by sl0thentr0py** [comment]
@st0012 Thanks, that's a good point. 
This will only change span names though, so it should not break any filters which only work with transaction fields currently. It is indeed 'breaking' in a technical sense but shouldn't really affect any users as far as I can see. Given that the next release will be much later because of Faraday, we could add this in?

The filters only have `transaction.op` as seen in the picture

![image](https://user-images.githubusercontent.com/6536764/148572056-900ebd7c-8ce2-4d35-bfea-13c06ca09fd6.png)

**Comment by sl0thentr0py** [comment]
anyway lemme make the PR anyway and we can decide later if and when to merge it. :)

**Comment by st0012** [comment]
I thought since `Transaction` is a subclass of `Span` (in Ruby and in Sentry's concept), this change will also apply to transactions' `op`? 

For example, the current transaction op for `Rack` integration is `rack.request` and for `Rails` it's `rails.request`. If we're changing them to `rack` and `rails`, they'll change how `traces_sampler` work.

**Comment by sl0thentr0py** [comment]
No I won't touch any of those transaction op names, this is purely about span op names. A couple of examples:

* [this `sql.active_record`](https://github.com/getsentry/sentry-ruby/blob/0019e14300913519e0d941f00511cd5fa090c6eb/sentry-rails/lib/sentry/rails/tracing/active_record_subscriber.rb#L7) will become `db.sql.active_record` (it just needs the `db` prefix to be standardized)
* [this `net.http`](https://github.com/getsentry/sentry-ruby/commit/0019e14300913519e0d941f00511cd5fa090c6eb) will become `http.client`

**Comment by st0012** [comment]
I see. Then I think it can go out in any minor release 👍

**Comment by jramiresbrito** [comment]
Hey, @sl0thentr0py thanks for the great work.

I'm trying to create some dashboards and alerts based on slow db queries (Our stack is Rails + GraphlQL + React )
Chatting in the discord community, people said that is not possible and it will be a future feature.

But it's not what I'm seeing in this thread.

I was able to see ```db.sql.active_record``` as part of my spans, but I couldn't filter by this nor create alerts based on this. 

Can you help me with this or point to some documentation?

Also [here's](https://discordapp.com/channels/621778831602221064/1258169394358517920) the question on Sentry Community case you want to share knowledge there for easy ingestion by the community.
![image](https://github.com/getsentry/sentry-ruby/assets/47673606/e110d3bc-ac13-4c80-96bc-6c23bf96b0f8)
