### ISSUE TITLE
Doesn't execute blocks of capture() in tests: doesn't call subscribed from an action cable channel

### ISSUE THREAD

**Issue by dorianmariefr** [getsentry/sentry-ruby#1691]
### Issue Description

I'm trying to reproduce a bug with my action cable channel in my tests (rspec 3) (rails 7) and couldn't get the `subscribed` method to execute

### Reproduction Steps

have a channel:

```ruby
class MessagesChannel < ApplicationCable::Channel
  def subscribed
    raise NotImplementedError
  end
end
```

Test it:

```ruby
require "rails_helper"

RSpec.describe MessagesChannel do
  before do
    stub_connection
  end

  it "rejects subscriptions without a current user" do
    expect { subscribe }.to raise_error(NotImplementedError)
  end
end
```

### Expected Behavior

executes the subscribed block

### Actual Behavior

doesn't execute the subscribed block

### Ruby Version

ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]

### SDK Version

sentry-ruby-core (4.9.1)

### Integration and Its Version

sentry-rails (4.9.1)

**Comment by st0012** [comment]
@dorianmariefr Thanks for reporting this. I've added #1692 for it.

**Comment by dorianmariefr** [comment]
thanks
