### ISSUE TITLE
config.dsn does not respect port 

### ISSUE THREAD

**Issue by laurafeier** [getsentry/sentry-ruby#1699]
### Issue Description

Custom port is not respected by default transport.
I assume the problem is in the [http transport class](https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/transport/http_transport.rb#L133) 
```
server = URI(@dsn.server)
use_ssl = server.scheme == "https"
port = use_ssl ? 443 : 80
```
This probably need to be changed in
```
server = URI(@dsn.server)
use_ssl = server.scheme == "https"
port = server.port
```

### Reproduction Steps

Use custom dsn with custom port.

### Expected Behavior

Connection should respect custom port. Instead it is enforced to 80.

### Actual Behavior

ERROR -- sentry: exception happened in background worker: Failed to open TCP connection to 75.81.74.93:80 (Connection refused - connect(2) for "75.81.74.93" port 80)

### Ruby Version

3.0.2p107

### SDK Version

5.0.1

### Integration and Its Version

rails 6.1.4.4

### Sentry Config

```
config.dsn = 'http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@75.81.74.93:9000/1'
```

**Comment by st0012** [comment]
@laurafeier Yeah it's a bug and thanks for reporting it 👍

**Comment by Bertg** [comment]
@st0012 Any idea on when this fix will be released?

**Comment by st0012** [comment]
It should go out later today 🙂
