### ISSUE TITLE
Allow users to determine when a stacktrace line is in_app or not

### ISSUE THREAD

**Issue by oliverguenther** [getsentry/sentry-ruby#1700]
**Describe the idea**

Right now, `in_app_pattern` is not user-configurable, which results in Rails projects with engines or plugins mounted by paths (e.g., from a Gemfile dependency) to not be counted as an in_app trace line. The sentry UI then collapses this trace by default with the note "Crashed in non-app: ...:"

![Screenshot from 2022-01-26 15-15-10](https://user-images.githubusercontent.com/459462/151180192-cc0d1951-fcd0-4b5a-be29-174d6e262991.png)

**Why do you think it's beneficial to most of the users**

For complex applications, it is common to extract functionality into engines and have them developed in isolation. Ideally, we could mark those as in_app for sentry.

**Possible implementation**

Provide a configuration or block to determine whether a given line is in_app, similar to `backtrace_cleanup_callback`

**Comment by st0012** [comment]
@sl0thentr0py It looks like sentry-python [uses include/exclude sets for in-app matching](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/utils.py#L679-L706). Is it a recommended approach? Or in Ruby we can take block instead?

**Comment by sl0thentr0py** [comment]
block is fine, the more ruby way

**Comment by oliverguenther** [comment]
Thanks for your quick responses. If this is something you deem a worthy addition to sentry-ruby, I'll gladly submit a PR for it in the coming days.

**Comment by oliverguenther** [comment]
As so often, the expression `in the coming days` was a huge understatement, but this is still on my todo list and I will get back to it if it is not something you moved to the roadmap yourselves. I was starting to think about a migration from the current path based configuration and whether we would allow both, or deprecate the old one. Thoughts?

**Comment by st0012** [comment]
@oliverguenther I just checked available configurations again and it seems like `config.app_dirs_pattern` (which's default is `/(bin|exe|app|config|lib|test)/`) can be used to solve that case? Perhaps something like this?

```rb
config.app_dirs_pattern = /(bin|exe|app|config|lib|open_project)/
```

**Comment by oliverguenther** [comment]
Ideally, I would have wanted to check whether the gem is in a special bundler group that we load plugins from, so that we don't have to enforce folder names for that check. But right now, all plugins follow that convention so it will work. I'll close this for now and wait for more feedback.
