### ISSUE TITLE
Sentry sends transaction traces despite having them disabled in the config

### ISSUE THREAD

**Issue by romankovt** [getsentry/sentry-ruby#1709]
### Issue Description

Hello! 

We completely disabled traces but still see that sentry tries sending transaction samples. We see transactions being sent as in our logs as in the Sentry dashboard.

Here is what we see in our logs:
```
/usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/ruby/3.0.0/gems/activejob-6.1.4.3/lib/active_job/execution.rb:47:in `perform_now'
/usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/ruby/3.0.0/gems/activejob-6.1.4.3/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/ruby/3.0.0/gems/activejob-6.1.4.3/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/ruby/3.0.0/gems/activejob-6.1.4.3/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/local/bundle/ruby/3.0.0/gems/activejob-6.1.4.3/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/local/lib/ruby/3.0.0/forwardable.rb:238:in `send_event'
/usr/local/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.8.1/lib/sentry/transport.rb:60:in `send_event'
/usr/local/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.8.1/lib/sentry/transport/http_transport.rb:55:in `rescue in send_data'
[2022-02-01T17:17:36.372314 #35] ERROR -- sentry: ** [Sentry] Transaction sending failed: the server responded with status 429
```

Here is a screenshot from our dashboard:

<img width="1204" alt="Screen Shot 2022-02-01 at 19 12 57" src="https://user-images.githubusercontent.com/6728845/152018154-82ef0170-0bd0-4386-b65a-7e496498a6c7.png">

How can we disable transaction sending?

### Reproduction Steps

Disable transaction sampling as we did in our config and observe transactions being sent anyway

### Expected Behavior

Transactions are not sent to the Sentry

### Actual Behavior

Transactions are sent to the Sentry despite the disabling them in the config

### Ruby Version

3.0.2

### SDK Version

4.8.1

### Integration and Its Version

rails 6.1.4.3, sidekiq 6.1.3

### Sentry Config

```ruby
Sentry.init do |config|
  if Rails.env.production?
    config.dsn = "___DSN___" # main-api-rails project
  end

  config.breadcrumbs_logger = %i[active_support_logger http_logger]

  # set product env (prod\stage\ds1-2 etc.)
  config.environment = ENV["ENV_NAME"] if ENV["ENV_NAME"].present?
  config.async = lambda { |event, hint| Sentry::SendEventJob.perform_later(event, hint) }

  # make sentry less noisy
  config.logger = Sentry::Logger.new($stdout)
  config.logger.level = :error
  # sentry performance tracing rate

  # Whether to capture local variables from the raised exception's frame. Default is false.
  config.capture_exception_frame_locals = true

  # don't send client reports to sentry
  config.send_client_reports = false

  # we don't use traces in sentry because of high cost and using datadog instead
  config.traces_sample_rate = 0.0
  config.traces_sampler = lambda { |_sampling_context| 0.0 }

  # clean secrets, tokens, password etc.
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, _hint|
    if event["request"] && event["request"]["headers"]
      event["request"]["headers"] = filter.filter(event["request"]["headers"])
    end

    event
  end
end
```

**Comment by rmsy** [comment]
We were recently confounded by this as well. In our case, despite setting the `traces_sample_rate` to `0.0`, we were still seeing a lot of transactions being recorded. It turns out that we had a lot of users calling our application with a value in the `Sentry-Trace` header, which was being picked up by the Ruby SDK as a parent transaction, and causing the backend transaction to be sampled. I'm thinking this _might_ be what is happening for you, as well.

If my theory is right, I think because you are using a `traces_sampler`, when #1712 is fixed in an upcoming release, this should stop occurring for you. Otherwise, you could remove the `traces_sample_rate` and `traces_sampler` lines entirely, leaving the default of `nil`, which completely disables APM (if my reading of the code is correct).

**Comment by romankovt** [comment]
@rmsy, thank you
We've removed `traces_sampler,` and `traces_sample_rate` from the config, and all errors disappeared. It's hard to say whether clients send requests with the `Sentry-Trace` header because we don't log request headers. All our API clients are ios and Android apps and they use Sentry SDK. Sentry SDK might somehow auto inject this header when clients send requests to the backend, but it's just speculation :) anyway, our problem is solved and I'll close the issue because there is a #1712 already which is going to fix it

one more time, thank you for your help :)
