### ISSUE TITLE
Bring back extra_context from Raven

### ISSUE THREAD

**Issue by arianf** [getsentry/sentry-ruby#1720]
**Describe the idea**

I'm not sure why extra_context was removed with the move from Raven to Sentry, but it was very useful.

The following issue comment points out the alternative, which is not great. https://github.com/getsentry/sentry-ruby/issues/918#issuecomment-681936998

Because you can't add non tag information, and you can't add arbitrary debug information.

**Why do you think it's beneficial to most of the users**

Given this example, you can see how nice it is to be able to add extra information to sentry events, that are scoped isolated per request. We haven't upgraded from Raven to Sentry because of this single thing alone.

```ruby
before_action :user
before_action :forum_permission

def user
  @user = User.find(session[:user_id])
  Sentry.extra_context(user: @user.inspect)
  @user
end

def forum_permission
  @forum = ForumPermission.find(param[:forum_id]
  Sentry.extra_context(forum: @forum.inspect)
  if !@user.has_access?(@forum)
    Sentry.caputre_message('Invalid Access')
  end

  head :403
end

def create_post
  @post = Post.create!(params)
  # Failure here would send a sentry event with user: @user.inspect
end
```

**Possible implementation**

**Comment by arianf** [comment]
Reading https://docs.sentry.io/platforms/ruby/guides/rack/enriching-events/context/#additional-data is pretty confusing:

> In addition to structured contexts, Sentry supports adding unstructured "Additional Data" via `set_extra`. Additional Data **is deprecated** in favor of structured contexts and should be avoided when possible.

Which is pretty confusing.. First sentence says "Sentry supports it", then it says "It's deprecated", then we are back to "avoid it when possible". So which is it?

If it's deprecated, does that mean it won't be supported in future updates? Or should it should be avoided when possible?

**Comment by arianf** [comment]
Also Raven.extra_context would give you a has back so you could easily see what was in there... I don't see any documentation for getting previously set event context.

```ruby
Sentry.set_extra(x: 5)
# .... 
if error
  Sentry.capture_message('foo')
  Rails.logger("foo.. extras: #{Sentry.extras.inspect)
end
```

**Comment by sl0thentr0py** [comment]
@arianf it seems you answered your own question here
> hmmm it seems like Sentry does have Sentry.set_context, Sentry.set_extras, Sentry.set_tags, Sentry.set_user.

We're not going to bring back `extra_context`. If you want to access user/tags later, you can do so in [`before_send`](https://docs.sentry.io/platforms/ruby/configuration/filtering/#using-platformidentifier-namebefore-send-) from the `event` object.
