### ISSUE TITLE
Duplicate reporting for Sidekiq errors

### ISSUE THREAD

**Issue by lostie** [getsentry/sentry-ruby#1731]
### Issue Description

After the update to version `5.1.0` I started to get `Sidekiq::JobRetry::Skip` errors in Sentry. After close examination, I found that for each of these errors I also had their cause reported as a separate error in Sentry.

It seems the Sidekiq error handler:
https://github.com/getsentry/sentry-ruby/blob/623d0464ce8120cd2ae3bfdb12113a265ad09d44/sentry-sidekiq/lib/sentry-sidekiq.rb#L28

is creating the sentry error for the cause, and the new error subscription for version `5.1.0`:

https://github.com/getsentry/sentry-ruby/blob/623d0464ce8120cd2ae3bfdb12113a265ad09d44/sentry-rails/lib/sentry/rails/railtie.rb#L123

is creating the sentry error for the `Sidekiq::JobRetry::Skip`

### Reproduction Steps

Use the `5.1.0` version of Sentry and raise an error within a sidekiq job.

### Expected Behavior

The raised error should be logged in Sentry

### Actual Behavior

Two errors are logged in sentry:
* The raised error
* The Sidekiq internal `Sidekiq::JobRetry::Skip`

### Ruby Version

3.1.0

### SDK Version

5.1.0

### Integration and Its Version

Rails (7.0.2) + Sidekiq (6.4.1)

### Sentry Config

I don't have any custom error handling configured

**Comment by sl0thentr0py** [comment]
@st0012 thx I think I get it now.
What about moving [this check](https://github.com/getsentry/sentry-ruby/blob/27c3a358569f389d039f4685171ea8caf001a8b4/sentry-rails/lib/sentry/rails/error_subscriber.rb#L15) to [`capture_exception`](https://github.com/getsentry/sentry-ruby/blob/27c3a358569f389d039f4685171ea8caf001a8b4/sentry-ruby/lib/sentry/hub.rb#L96-L97) in general, so the double reporting solution is not specific to the rails `error_subscriber` but we will generally avoid reporting all duplicate exceptions?

This still would not fix the Sidekiq order precedence problem though.

**Comment by jasonrudolph** [comment]
> After the update to version `5.1.0` I started to get `Sidekiq::JobRetry::Skip` errors in Sentry. After close examination, I found that for each of these errors I also had their cause reported as a separate error in Sentry.

I've upgraded to `5.1.1` (which includes the fixes in https://github.com/getsentry/sentry-ruby/pull/1738), but I'm still experiencing this issue.

@lostie: If you've upgraded to `5.1.1`, did that resolve this problem for you, or are you still seeing it as well?

**Comment by micke** [comment]
We are also still seing these after upgrading to 5.1.1

**Comment by st0012** [comment]
@jasonrudolph @micke thanks for reporting. I've done a bit more investigation and reported it in https://github.com/rails/rails/pull/43625#discussion_r820229657.

**Comment by st0012** [comment]
After [consulting Sidekiq's author Mike](https://github.com/rails/rails/pull/43625#issuecomment-1071574110), I think ignoring `Sidekiq::JobRetry::Skip` can be an adhoc but effective solution to this problem. So I added #1763 for it.

**Comment by st0012** [comment]
FYI, I'll change the error reporter integration in `5.3.0`. More details: https://github.com/rails/rails/pull/43625#issuecomment-1072514175
