### ISSUE TITLE
Best way to stop tracing on a rack-attack blocked/throttled request?

### ISSUE THREAD

**Issue by skunkworker** [getsentry/sentry-ruby#1740]
Right now I am getting traces of requests that rack-attack is picking up and throttling/blocking. Currently my traces sampler is set to be true, but I was wondering if there was a best way in order to stop tracing once rack-attack has not safelisted a request?

**Comment by lewispb** [comment]
Are you using a sampling function already @skunkworker?

https://docs.sentry.io/platforms/ruby/configuration/sampling/#setting-a-sampling-function

Perhaps you can inspect the value of `sampling_context[:transaction_context]` and return false or 0 for requests you don't want to track.

**Comment by st0012** [comment]
@skunkworker can you list the middlewares you use? I think the best solution would be to place it **outside** of the SDK's middleware, so those requests won't even start any transactions.
