### ISSUE TITLE
Possible to disable Sentry Ruby logging?

### ISSUE THREAD

**Issue by lewispb** [getsentry/sentry-ruby#1741]
I've noticed logging around tracing decisions in our Rails apps. Can this currently be disabled, or the log level for Sentry SDK logs controlled?

**Comment by st0012** [comment]
You can assign a another logger to the SDK like:

```rb
Sentry.init do |config|
  config.logger = Logger.new(nil)
end
```

You can also assign the logger with the same destination (`$stdout`) but with a different log level.
