### ISSUE TITLE
How to set additional data(which is unique for every exception) for Sentry event?

### ISSUE THREAD

**Issue by saikumar-everest** [getsentry/sentry-ruby#1744]
Hi Sentry-ruby team,

### Brief
We are using "sentry-raven" in our rails application and I'm trying to migrate to "sentry-ruby". In that process, I got an issue with my application architecture to record sentry events with some meta data. I can explain the issue and I would request your suggestions to achieve the intended behaviour without changing much application code.

### Context about my issue
We have a lot of custom defined error classes, where each error class will define a method(i.e `exception_meta_data`). It means, each exception object will have it's own meta data information.
Whenever/wherever application raises an exception, Sentry is capturing the events properly. But I would like to add the `exception_meta_data` information as addition data to the Sentry event. How can I achieve this with "sentry-ruby"?

I have seen the docs as well. Docs suggest to use `Sentry.set_extras()` to set data globally or `Sentry.with_scope do |scope|` to set data locally for that particular event. But they're not helpful in my case because, 
 * There is no way to get hold of the exception object(that's going to be raised at runtime) to set the meta information for sentry extras.
 * Also, I can't use `Sentry.set_extras()` because the meta info I want to set, is specific that particular sentry event.
 * Also, I can't use `Sentry.with_scope do |scope|` because, this block will be useful if I want to explicitly notify sentry by setting specific meta info. But I don't want to explicitly notify Sentry, because doing that will result in recording same event twice in sentry(one is by explicitly notifying, and second is by the usual behaviour of sentry, which captures any thrown exception).

Please suggest what I can do to achieve the intended behaviour without changing much application code.

#### How we used to do with "sentry-raven"?
We've overridden `Raven::Event.from_exception(exception, options, &block)` this class method globally in our sentry initializer, where `options` will be merged with `exception.exception_meta_data`.

**app/initializers/sentry.rb**
```ruby
require 'raven'

module ExceptionMetaData
  def from_exception(exception, options={}, &block)
    if exception.respond_to?(:exception_meta_data)
      options[:extra] ||= {}
      options[:extra].merge! exception.exception_meta_data
    end
    super(exception, options, &block)
  end
end

class Raven::Event
  class << self
    prepend ExceptionMetaData
  end
end

Raven.configure do |config|
  config.dsn = ENV["SENTRY_DSN"]
  ...
end
```

Thanks in advance.

**Comment by st0012** [comment]
You can use `before_send` callback for this:

```rb
Sentry.init do |config|
  config.before_send = lambda do |event, hint|
    exception = hint[:exception] # the exception object
    # assume exception.exception_meta_data returns a hash
    # contexts is better for structured data
    event.contexts[:exception_meta] = exception.exception_meta_data
    event
  end
end
```

**Comment by saikumar-everest** [comment]
@st0012 Thank you so much. It's working as expected.
