### ISSUE TITLE
Confusing error if sentry-sidekiq is imported after Sentry.init

### ISSUE THREAD

**Issue by rgalanakis** [getsentry/sentry-ruby#1756]
### Issue Description

If `sentry-sidekiq` is required AFTER `Sentry.init` has been run, an exception is raised in `ErrorHandler`, as below (the `Sentry.configuration.sidekiq` field is nil).
This is because `configuration.sidekiq` is set in a 'post initialization callback', but once `Sentry.init` is run, the callbacks won't be run.

This is a really tough one to find and diagnose because it is an exception *in an error handler*, so of course trying to figure out what happened is very confusing, but obvious in hindsight.

### Reproduction Steps

- `require sentry-ruby`
- `Sentry.init`
- `require sentry-sidekiq`
- Provoke an error
- An exception is raised:
```
name:NoMethodError
message:undefined method `report_after_job_retries' for nil:NilClass

if Sentry.configuration.sidekiq.report_after_job_retries && retry_option.is_a?(Integer) && retry_option.positive?
```

### Expected Behavior

Any one of:

- `post_initialization_callbacks` are run immediately if Sentry is already initialized
- The lack of configuration is detected in `ErrorHandler`, and a clear error is raised
- The issue with requiring-after-init is detected on import, and a clear error is raised

### Actual Behavior

NoMethodError on nil is raised

### Ruby Version

All (3.1 tested)

### SDK Version

4.8.3

### Integration and Its Version

Sidekiq, 4.8.3

### Sentry Config

Just need to get Sentry configured in some way:

```ruby
Sentry.init do |config|
  config.dsn = 'https://examplePublicKey@o0.ingest.sentry.io/0'
end
```

**Comment by st0012** [comment]
@rgalanakis thanks for reporting this. I think the SDK should let user aware of any require-after-init situation. but I'm not sure if raising an exception fits Sentry's SDK guideline of not breaking user applications. I think logging a warning message should be enough.
@sl0thentr0py wdyt?

**Comment by sl0thentr0py** [comment]
hmm, but is there a valid reason why one should need to require after init? As long as the docs clearly say require first and init, I don't see that much value in adding all these weird branches. But if you do want to add a check, a logger warning sounds good.

**Comment by st0012** [comment]
I think the point here is to allow require-after-init. it's about which approach we should use to notify users if that happens. I just want to confirm that raising error in this case is still considered inappropriate?

**Comment by rgalanakis** [comment]
> but I'm not sure if raising an exception fits Sentry's SDK guideline of not breaking user applications.

I want to point out that require-after-init currently leads to exceptions during error handling. So if it's just a log warning, then I would suggest:

- A warning should be logged when require-after-init, because otherwise you don't find out about the misconfiguration until you start seeing issues in the error handler.
- The error handler handle require-after-init, log a warning, and use the default options (maybe include a warning in the Sentry error itself so it's very visible).

Exceptions/issues in the error handler are one of the most annoying problems to debug (it took a while to understand what we were seeing and why). So I think some additional complexity in the library is warranted, if raising an exception during require is not allowed by the guidelines.

**Comment by st0012** [comment]
The warning will happen when any integration is required after the SDK initialization. But I'm not sure if we should do more than it. I mean, it's not normal to have `sentry-ruby` required, SDK initialized, and then have `sentry-sidekiq` required. If you require them using `Bundler.require`, they should be all required at the same time.

So I'm not sure if we should invest more on this unexpected edge case.
