### ISSUE TITLE
`last_event_id` references transaction event

### ISSUE THREAD

**Issue by entretechno-jeremiah** [getsentry/sentry-ruby#1766]
### Issue Description

When I [call `Sentry.last_event_id` to expose the event ID for the last exception to my event handler](https://docs.sentry.io/clients/ruby/usage/#referencing-events), it includes the ID of a transaction event.

### Reproduction Steps

1. Initialize the client to sample every transaction (see below).
2. Trigger an exception.
3. Call `Sentry.last_event_id`.

### Expected Behavior

`Sentry.last_event_id` should return the event ID for the exception.

### Actual Behavior

`Sentry.last_event_id` returns the event ID for a transaction (`Sentry::TransactionEvent`).

### Ruby Version

3.1.1

### SDK Version

5.2.1

### Integration and Its Version

sentry-rails v5.2.1 (Rails v7.0.2.3)

### Sentry Config

```
Sentry.init do |config|
  config.traces_sample_rate = 1.0
end
```

**Comment by st0012** [comment]
@sl0thentr0py can you take a look at this? thx
