### ISSUE TITLE
`SystemStackError` exceptions dropped by payload truncation logic

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#1799]
These exceptions have lots of `frames` in the exception object, we could be a bit smarter and truncate the frames instead of dropping the whole envelope item.

**Comment by PikachuEXE** [comment]
Where is the payload truncation logic happening now?
I can try to figure out what to change. (As this is affecting one of my projects)

**Comment by sl0thentr0py** [comment]
@PikachuEXE here
https://github.com/getsentry/sentry-ruby/blob/7429e6c239a904bd6b00e1e55b2449fbe5045167/sentry-ruby/lib/sentry/transport.rb#L85-L93
