### ISSUE TITLE
Sentry::Scope#set_contexts fails duplicate keys don't have Hash values

### ISSUE THREAD

**Issue by tsu-shiuan** [getsentry/sentry-ruby#1805]
### Issue Description

Introduced here https://github.com/getsentry/sentry-ruby/pull/1621 in versions 4.8.1 and above.

I believe the intention here is that when additional context is given for the same key, _and_ when the value is a Hash, we want to append any new key values to the existing Hash as shown in the description.

The problem is that not all values are Hashes, which results in 👇 
```
NoMethodError: undefined method `merge' for "bar":String
```

### Reproduction Steps

```
Sentry.configure_scope do |scope|
  scope.set_contexts({:foo => "bar"})
end

Sentry.configure_scope do |scope|
   scope.set_contexts({:foo => "new bar"})
end
```

### Expected Behavior

Replaces the existing "bar" value with "new bar"

### Actual Behavior

```
NoMethodError: undefined method `merge' for "new bar":String
from /srv/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.8.1/lib/sentry/scope.rb:132:in `block in set_contexts'

### Ruby Version

2.7.5

### SDK Version

5.3.0

**Comment by tsu-shiuan** [comment]
If I could get permissions to submit a PR, I'd be happy to 😄 

I think the code should be changes as follows

```
def set_contexts(contexts_hash)
  check_argument_type!(contexts_hash, Hash)
  @contexts.merge!(contexts_hash) do |key, old, new|
    # OLD CODE
    # new.merge(old)
    
    # Suggested new code
    if new.is_a?(Hash) && old.is_a?(Hash)
      new.merge(old)
    else
      new
    end
  end
end
```

This allows the overwriting of values when a key already contains a value but is not a hash. If the team has opinions around how to handle more cases such as when the value is an Array where we'd append new values to the old Array, I'm happy to add the code for that too.

**Comment by st0012** [comment]
@tsu-shiuan Context's values are expected to be hashes. That's why you saw the error.
In your case, I recommend you to use `set_extras` instead.

**Comment by tsu-shiuan** [comment]
Understood! We will do that, thanks for the clarification

**Comment by tsu-shiuan** [comment]
Maybe we could add an additional validation to `check_argument_type!` to also check that the value is a Hash instead of just the first level?
