### ISSUE TITLE
Sentry.with_child_span didn't handle current scope is nil

### ISSUE THREAD

**Issue by elct9620** [getsentry/sentry-ruby#1818]
### Issue Description

https://github.com/getsentry/sentry-ruby/blob/0fe8d27e4f84fda11475437a1cdd16f016efd904/sentry-ruby/lib/sentry-ruby.rb#L401-L420

The `get_current_scope` will return `nil` before initialized then the `with_child_span` will failed.

### Reproduction Steps

```ruby
require 'sentry-ruby'

# May raise exception if Sentry not ready
Sentry.with_child_span do |child_span|
  # ...
end
```

### Expected Behavior

Ignore the span until Sentry is ready.

### Actual Behavior

Raised `UndefinedMethod` error

### Ruby Version

2.7.6

### SDK Version

5.3.0

### Integration and Its Version

Sequel

**Comment by st0012** [comment]
@elct9620 Thanks for reporting this 😄 I've added #1819 to address it.
