### ISSUE TITLE
Rails - Is there a way to disable Sentry for one controller method?

### ISSUE THREAD

**Issue by kiddrew** [getsentry/sentry-ruby#1822]
I have a controller method that generates a ton of low value requests that are chewing through my Sentry transactions, and I'd like to disable monitoring for that one method. Is there an easy way to do that?

**Comment by st0012** [comment]
You should be able to use the `traces_sampler` config for that as described in [this example](https://docs.sentry.io/platforms/ruby/guides/rails/configuration/sampling/#setting-a-sampling-function).

**Comment by kiddrew** [comment]
Perfect, thank you @st0012!

**Comment by st0012** [comment]
@kiddrew np, glad to help 😄
