### ISSUE TITLE
Warning: already initialized constant

### ISSUE THREAD

**Issue by phlegx** [getsentry/sentry-ruby#1837]
### Issue Description

After add `gem 'sentry-ruby', '5.3.1'` to the Gemfile, we get this warnings:

```
/home/test/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/test/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/home/test/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/test/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/home/test/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/test/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
```

### Reproduction Steps

- Install ruby 2.7.2
- Install rails 7.0.3
- Add `gem 'sentry-ruby', '5.3.1'` to the Gemfile
- Run `bundle`
- Run `rake db:create` or another rails command

### Expected Behavior

No warnings should be shown after run `rake db:create` or another rails command.

### Actual Behavior

Warnings are shown after run `rake db:create` or another rails command.

### Ruby Version

2.7.2

### SDK Version

nothing

See https://github.com/ruby/net-imap/issues/16#issuecomment-803086765

**Comment by st0012** [comment]
I don't mind adding `net-http` as dependency but it triggered a lot more warning because of `uri`

```
/Users/st0012/.rbenv/versions/2.7.5/lib/ruby/2.7.0/uri/version.rb:3: warning: already initialized constant URI::VERSION_CODE
/Users/st0012/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/uri-0.11.0/lib/uri/version.rb:3: warning: previous definition of VERSION_CODE was here
/Users/st0012/.rbenv/versions/2.7.5/lib/ruby/2.7.0/uri/version.rb:4: warning: already initialized constant URI::VERSION
# dozens more
```

And this time I can't solve it by adding `uri` to Gemfile. Have you seen anything like this?

**Comment by phlegx** [comment]
Adding `net-http` as dependency helps to remove some warnings. Adding `uri` don't helps. Also upgrading Ruby to 2.7.6 don't removes the warnings. What helps is to move to Ruby 3.x.
