### ISSUE TITLE
rails: allow showing link to sentry page on error page

### ISSUE THREAD

**Issue by grosser** [getsentry/sentry-ruby#1846]
**Describe the idea**
![image](https://user-images.githubusercontent.com/11367/178772153-42a70825-d3a5-4383-b1c8-c5accd73595d.png)

**Why do you think it's beneficial to most of the users**
- useful for internal apps to be able to link directly to the error
- useful for public apps to show an error code that engineers can later hunt down

**Possible implementation**
https://github.com/grosser/sentry-user_informer

**Comment by st0012** [comment]
I like the idea but I'm not sure if we need to use Fiber locals for that. Won't storing it in `env` work?

**Comment by grosser** [comment]
storing in env will work if the core middleware is refactored to pass the env to capture_exception

**Comment by st0012** [comment]
I just did it in https://github.com/getsentry/sentry-ruby/pull/1847 😄

**Comment by st0012** [comment]
I'm not convinced that we should maintain a new middleware + a template (even just minimum) for this. I think as an SDK, it should just inject the event id into the `env` and users/libraries should implement their solutions from there.

**Comment by grosser** [comment]
I'm fine with that too, good step forward and easy to do ...

**Comment by st0012** [comment]
Ok I’ll open a PR for that 👍

**Comment by st0012** [comment]
PR opened: https://github.com/getsentry/sentry-ruby/pull/1849
