### ISSUE TITLE
sentry: can't serialize breadcrumb data because of error

### ISSUE THREAD

**Issue by penso** [getsentry/sentry-ruby#1854]
### Issue Description

I believe there is an issue when an error occurs in the stack, I was expecting sentry to send a new issue but it did not. The error says:

`2022-07-22T14:58:02.391625+00:00 app[web.1]: 14:58:02 web.1    | D, [2022-07-22T14:58:02.374296 #57] DEBUG -- sentry: can't serialize breadcrumb data because of error: "\xD2" from ASCII-8BIT to UTF-8`

I use `.breadcrumbs_logger = [:active_support_logger]` and the code is inserting raw bytes (non utf8) into a pgsql `binary` column. I have the feeling sentry is trying to get a backtrace and converting that binary into UTF8.

### Reproduction Steps

none :(

### Expected Behavior

Get a sentry issue 

### Actual Behavior

crashing, no sentry issue sent

### Ruby Version

3.0.2

### SDK Version

5.1.0

**Comment by st0012** [comment]
The message only notifies you that 1 breadcrumbs record can't be serialized. The [error is rescued](https://github.com/getsentry/sentry-ruby/blob/c9b4eac913f0c6510178c451da57d91fc340fa20/sentry-ruby/lib/sentry/breadcrumb.rb#L55-L67) and it shouldn't prevent the event from being sent nor crash your app.
