### ISSUE TITLE
undefined method `exclude_loggers' for nil:NilClass during Rails boot on production

### ISSUE THREAD

**Issue by tvdeyen** [getsentry/sentry-ruby#1858]
### Issue Description

Booting a Rails app during deployment fails with 

```
undefined method `exclude_loggers' for nil:NilClass (NoMethodError)
```

in

```
/opt/render/project/.gems/ruby/2.7.0/gems/sentry-ruby-5.4.1/lib/sentry/breadcrumb/sentry_logger.rb:80:in `ignored_logger?': undefined method `exclude_loggers' for nil:NilClass (NoMethodError)
  from /opt/render/project/.gems/ruby/2.7.0/gems/sentry-ruby-5.4.1/lib/sentry/breadcrumb/sentry_logger.rb:55:in `add_breadcrumb'
  from /opt/render/project/.gems/ruby/2.7.0/gems/sentry-ruby-5.4.1/lib/sentry/breadcrumb/sentry_logger.rb:18:in `add'
  from /opt/render/project/rubies/ruby-2.7.6/lib/ruby/2.7.0/logger.rb:494:in `debug'
  from /opt/render/project/.gems/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/agent_logger.rb:94:in `block in format_and_send'
  from /opt/render/project/.gems/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/agent_logger.rb:91:in `each'
  from /opt/render/project/.gems/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/agent_logger.rb:91:in `format_and_send'
  from /opt/render/project/.gems/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/agent_logger.rb:44:in `debug'
  from /opt/render/project/.gems/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/threading/agent_thread.rb:20:in `block in create'
```

### Reproduction Steps

1. Update to sentry-ruby 5.4.1
2. Deploy to production
3. Run `rake db:migrate`

### Expected Behavior

It should not fail

### Actual Behavior

It should work

### Ruby Version

2.7.6

### SDK Version

5.4.1

### Integration and Its Version

Rails 6.0.5.1

### Sentry Config

```rb
Sentry.init do |config|
  config.release = "<snip>"
  config.dsn = ENV["SENTRY_DSN"]
  config.breadcrumbs_logger = [:sentry_logger, :active_support_logger, :http_logger]
end
```

**Comment by tvdeyen** [comment]
Downgrading to sentry-ruby 5.3.1 fixes the issue.

**Comment by st0012** [comment]
This is weird because if it reaches there, the SDK should already be initialized so the configuration should present 🤔 
https://github.com/getsentry/sentry-ruby/blob/09308ab1c79440918e0fde0e9f2dc5fef53d06d5/sentry-ruby/lib/sentry/breadcrumb/sentry_logger.rb#L80
@sl0thentr0py any thoughts?

**Comment by sl0thentr0py** [comment]
hmm I guess what is happening is that since this patches `Logger`, some rails logic seems to happen before `Sentry.init` and this patch tries to add breadcrumbs for those logs.
But I don't know why this would only show up in the new release.

**Comment by sl0thentr0py** [comment]
and we did add the `close` to `at_exit` which also sets `initialized?` to false and cause `Sentry.configuration` to be nil.

**Comment by st0012** [comment]
But at the beginning of `add_breadcrumb` we already check `Sentry.get_current_hub` is present. So `Sentry.configuration` should also present I think? Ofc it's possible to have the SDK closed between the 2 calls but I think it's unlikely.

**Comment by sl0thentr0py** [comment]
yeah you're right. No clue, but I also see some `newrelic` in the trace above. I'll try to repro this tomorrow.

**Comment by anteo** [comment]
I got the same error with newrelic_rpm (8.9.0) + sentry-ruby (5.4.1)

Sentry calls `close` in `at_exit` handler which makes `Sentry.configuration` to be nil in the **main thread**.

At the same time NewRelic's AgentThread finalizes its job by sending events and breadcrumbs and also calling `SentryLogger#add_breadcrumb`. This method checks `Sentry.get_current_hub` to be present and it is present, because `Sentry.get_current_hub` returns thread's local hub, which was not yet closed.

But `Sentry.initialized?` returns `false`, because it checks presence of `@main_hub` which was unset already in the main thread. It causes `Sentry.configuration` to return `nil` and `#ignored_logger?` method fail.

Not sure, but maybe it makes sense to get the configuration of the local thread instead of the main thread (get_main_hub) inside `initialized?` check?:

```
    def initialized?
      !!Thread.current.thread_variable_get(THREAD_LOCAL)
    end
```

It solved the issue for me.

**Comment by sl0thentr0py** [comment]
hmm that's a great explanation @anteo, thanks!
I believe we just need a better check in `add_breadcrumb`. Do you agree @st0012?
```
        return unless Sentry.initialized? && Sentry.get_current_hub
```

**Comment by tvdeyen** [comment]
When will this be released as gem?

**Comment by sl0thentr0py** [comment]
oh, I can do a patch release tomorrow

**Comment by tvdeyen** [comment]
Nice

**Comment by sl0thentr0py** [comment]
@tvdeyen 5.4.2 released

**Comment by tvdeyen** [comment]
@sl0thentr0py thank you 🙏🏻
