### ISSUE TITLE
Got error `ArgumentError: wrong number of arguments (given 2, expected 1)`

### ISSUE THREAD

**Issue by dim0627** [getsentry/sentry-ruby#1865]
Hello team!
I have problem and need help.

I just update sentry-ruby from 4.3.1 to 5.4.1, I got this error with rspec.
Anyone have solution? Let me know please 🙏 

```
  1) Xxxx GET /Xxxx/:id Got status 500
     Failure/Error:
       expect do
         get_xxxx
       end.to raise_error(NoMethodError)
     
       expected NoMethodError, got #<ArgumentError: wrong number of arguments (given 2, expected 1)> with backtrace:
```

**Comment by st0012** [comment]
@dim0627 Can you provide the backtrace and the full list of Sentry related gems? That'll help us locate the cause

**Comment by Jaco-Pretorius** [comment]
I'm getting the exact same error, also within an rspec request spec.

`expect { get '/register.asp' }.to raise_error(ActionController::RoutingError)`

used to work, now I get

```
ArgumentError: wrong number of arguments (given 2, expected 1)
from /Users/my-username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sentry-rails-4.8.3/lib/sentry/rails/capture_exceptions.rb:23:in `capture_exception'
Caused by ActionController::RoutingError: No route matches [GET] "/register.asp"
from /Users/my-username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
```

**Comment by st0012** [comment]
@Jaco-Pretorius If you also got the error **after** you upgraded `sentry-ruby` to the latest version, it's because `sentry-rails` is not updated along with it. Once you also upgrade `sentry-rails`, it should solve the problem.
Unfortunately we don't have a way to enforce that as explained in: https://github.com/getsentry/sentry-ruby/issues/1859#issuecomment-1203071794

**Comment by Jaco-Pretorius** [comment]
@st0012 Ah, that did indeed fix it. I do wish there was a way to enforce that, or to make it more obvious. I ran into this error as part of a PR that dependabot opened.

At a high level, why can't `sentry-rails` just have `sentry-ruby` as a dependency? Then you would only need to add `sentry-rails` to your Gemfile and both would be updated at the same time?

**Comment by dim0627** [comment]
@st0012 
Thank you for reply!
And I'm sorry, I solved this problem after the update `sentry-rails`, `sentry-sidekiq` 🙏
