### ISSUE TITLE
Unable to fetch commits

### ISSUE THREAD

**Issue by e-jjj** [getsentry/sentry-ruby#1875]
Hi There,

I'm setting up releases in the sentry.rb initialiser in rails following the documentation, https://docs.sentry.io/platforms/ruby/configuration/releases/#setting-a-release

The format i use in the release config is,

`config.release = app_name@app_version`

I can see the release being created under Releases in the sentry web portal (self hosted), however the commits tab doesn't show any data. I made sure the repository integration is set up and working between sentry and gitlab (attached is a screen shot from the repository showing the status of the push events). Followed the documentation, https://docs.sentry.io/product/releases/setup/release-automation/

As far as I understand I shouldn't need to sent commit data manually (via the sentry-cli) since the repository integration is in place. Can you please confirm this is the case and if I'm missing anything to have the commit data in sentry under the release ?
<img width="692" alt="Screen Shot 2022-08-24 at 12 18 50 am" src="https://user-images.githubusercontent.com/22207113/186182461-46d26ea4-9645-4a9f-baed-e5506a5654d6.png">

Thanks!

**Comment by sl0thentr0py** [comment]
@e-jjj sorry this slipped through the cracks, is this still a problem?
