### ISSUE TITLE
[sidekiq] unhandled errors not captured

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-ruby#1883]
### Issue Description

A customer reported issues sending unhandled errors to Sentry using the sidekiq SDK. While events sent with `captureException` were sent correctly. 

The customer believes the issue is related to the timing of initializations: The error handler that is added by sentry-sidekiq is being cleared later by Sidekiq (which appears to have been introduced in v6.5.x), so while the middleware is working, the error handler isn't being called.

This is where the sentry-sidekiq error handler is added: https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-sidekiq/lib/sentry-sidekiq.rb#L28
This is where Sidekick is clearling all the error handlers: https://github.com/mperham/sidekiq/blob/ea9c86ff5052fff310e83cf51d020771795bb4b6/lib/sidekiq/cli.rb#L26

We just got a workaround in place in our staging environment by adding the error handler directly from our own sidekiq.rb initializer

```
Sidekiq.configure_server do |config|
# ...
if config.error_handlers.none?(Sentry::Sidekiq::ErrorHandler)
config.error_handlers << Sentry::Sidekiq::ErrorHandler.new
end
# ...
end
```

### Reproduction Steps

NA

### Expected Behavior

Unhandled execption to be sent to Sentryexception

### Actual Behavior

No event is sent.

### Ruby Version

--

### SDK Version

5.4.2

### Sentry Config

```rb
Sentry.init do |config|
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda { |event, _hint| filter.filter(event.to_hash) }
  config.breadcrumbs_logger = %i[http_logger monotonic_active_support_logger]
  config.send_default_pii = false
  config.dsn = ENV['SENTRY_RAVEN_DSN'] if ENV['DISABLE_SENTRY'].blank?
  if !Rails.env.production? && ENV['HEROKU_APP_NAME'].present?
    config.enabled_environments = [ENV['HEROKU_APP_NAME']]
    config.environment = ENV['HEROKU_APP_NAME']
    else
    config.enabled_environments = %w[staging production]
    config.environment = Rails.env
  end
  config.release = ENV['RELEASE_VERSION'] || ENV['SOURCE_VERSION']
  
  # temporarily enable debug for BUAPP-48809
  config.debug = true
end
```

Environment: 
sentry-rails (5.4.2)
railties (>= 5.0)
sentry-ruby (~> 5.4.2)
sentry-ruby (5.4.2)
concurrent-ruby (~> 1.0, >= 1.0.2)
sentry-sidekiq (5.4.2)
sentry-ruby (~> 5.4.2)
sidekiq (>= 3.0)

**Comment by jscheid** [comment]
I can confirm that the workaround solves the issue (thanks for sharing it @rbisol), however we've lost a number of reports irretrievably due to this.

**Comment by st0012** [comment]
@rbisol I couldn't reproduce this with `sentry-ruby 5.8` and `sidekiq 6.5.5`. Could the customer provide a simplest reproduction for the issue?

I also don't think what the customer described is a likely because: If we look at the [`sidekiq` executable](https://github.com/sidekiq/sidekiq/blob/6-x/bin/sidekiq), we can see that `cli.parse`, which cleans the error handlers, is run before `cli.run`, which boots the app, including loading the SDK.

That means in a normal setup, the SDK always adds the handler AFTER the error handlers are cleared.  We can verify this by putting breakpoints in both places:

```
be rdbg -n -c -- bundle exec sidekiq
[21, 30] in ~/.gem/ruby/3.2.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb
    21|     attr_accessor :environment
    22|     attr_accessor :config
    23| 
    24|     def parse(args = ARGV.dup)
    25|       @config = Sidekiq
=>  26|       binding.b
    27|       @config[:error_handlers].clear
    28|       @config[:error_handlers] << @config.method(:default_error_handler)
    29| 
    30|       setup_options(args)
=>#0    Sidekiq::CLI#parse(args=[]) at ~/.gem/ruby/3.2.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb:26
  #1    <top (required)> at ~/.gem/ruby/3.2.0/gems/sidekiq-6.5.5/bin/sidekiq:27
  # and 17 frames (use `bt' command for all frames)
(rdbg) c    # continue command
[23, 32] in ~/src/github.com/getsentry/sentry-ruby/sentry-sidekiq/lib/sentry-sidekiq.rb
    23|     end
    24|   end
    25| end
    26| 
    27| Sidekiq.configure_server do |config|
=>  28|   binding.b
    29|   config.error_handlers << Sentry::Sidekiq::ErrorHandler.new
    30|   config.server_middleware do |chain|
    31|     chain.add Sentry::Sidekiq::SentryContextServerMiddleware
    32|   end
=>#0    block {|config=Sidekiq|} in <main> at ~/src/github.com/getsentry/sentry-ruby/sentry-sidekiq/lib/sentry-sidekiq.rb:28
  #1    Sidekiq.configure_server at ~/.gem/ruby/3.2.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:142
  # and 33 frames (use `bt' command for all frames)
(rdbg) 
```

So if the SDK's handler did get cleared, it should be something else. Therefore, it'd really help if the customer (or @jscheid) can provide more information.

**Comment by st0012** [comment]
@sl0thentr0py I think we can close this for now due to lack of feedback?

**Comment by sl0thentr0py** [comment]
yep
