### ISSUE TITLE
Missing configuration for HTTP headers sanitization

### ISSUE THREAD

**Issue by nikhilDevarasetty** [getsentry/sentry-ruby#1886]
**Describe the idea**
Unable to sanitize HTTP headers using sentry configuration

**Why do you think it's beneficial to most of the users**
It helps in sanitize any authentication or sensitive headers present in the HTTP request

**Comment by sl0thentr0py** [comment]
@nikhilDevarasetty please use a `before_send` to filter as per your needs

```ruby
Sentry.init do |config|
  config.before_send = lambda |event, _hint| do
    event.request&.headers.delete("HTTP_SENSITIVE_KEY")
    event
  end
end

```
