### ISSUE TITLE
undefined method `[]' for nil:NilClass in session.flusher.rb

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-ruby#1891]
### Issue Description

A user has reported an issue in the Rails SDK. The stack trace points to [this file](https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/session_flusher.rb#L46) as can be seen the screenshot from the Sentry event:
![Screenshot 2022-09-14 at 11 44 23](https://user-images.githubusercontent.com/64906376/190120883-05b5a8bb-3936-4dce-bd90-af2da4122714.png)

The current workaround is to disable session tracking the SDK initialisation using `auto_session_tracking = false`

### Reproduction Steps

Unknown

### Expected Behavior

No errors

### Actual Behavior

An internal server error is thrown in the client application.

### Ruby Version

2.7.4

### SDK Version

5.4.2

### Integration and Its Version

Rails: 6.1.4.1

### Sentry Config

Sentry.init do |config|
config.dsn = Settings.sentry.dsn
config.environment = Settings.env

config.excluded_exceptions = [ActionController::RoutingError]

filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
config.before_send = lambda do |event, hint|
filter.filter(event.to_hash)
end
end

**Comment by st0012** [comment]
@sl0thentr0py Can you give this a look?
