### ISSUE TITLE
Align Span Operations

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-ruby#1903]
As per https://github.com/getsentry/develop/pull/694, we should align our span operations.

| SDK             | Old Operation                             | New Operation                                  | Link                                                                                                                                                                  | PR                                                         |
| --------------- | ----------------------------------------- | ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| Ruby            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | delayed_job                               | queue.task.delayed_job                         | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-delayed_job/lib/sentry/delayed_job/plugin.rb#L21                        |                                                            |
|                 | rails.action_cable                        | websocket.server                               | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/action_cable.rb#L34                              |                                                            |
|                 | active_job                                | queue.task.active_job                          | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/active_job.rb#L28                                |                                                            |
|                 | rails.request                             | http.server                                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/capture_exceptions.rb#L20                        |                                                            |
|                 | process_action.action_controller          | view.process_action.action_controller          | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/action_controller_subscriber.rb#L10      |                                                            |
|                 | service_upload.active_storage             | file.service_upload.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_download.active_storage           | file.service_download.active_storage           | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_streaming_download.active_storage | file.service_streaming_download.active_storage | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_download_chunk.active_storage     | file.service_download_chunk.active_storage     | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_delete.active_storage             | file.service_delete.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_delete_prefixed.active_storage    | file.service_delete_prefixed.active_storage    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_exist.active_storage              | file.service_exist.active_storage              | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_url.active_storage                | file.service_url.active_storage                | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_mirror.active_storage             | file.service_mirror.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_update_metadata.active_storage    | file.service_update_metadata.active_storage    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | preview.active_storage                    | file.preview.active_storage                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | analyze.active_storage                    | file.analyze.active_storage                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | resque                                    | queue.resque                                   | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-resque/lib/sentry/resque.rb#L27                                         |                                                            |
|                 | db.redis.command                          | db.redis                                       | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-ruby/lib/sentry/redis.rb#L6                                             |                                                            |
|                 | rack.request                              | http.server                                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-ruby/lib/sentry/rack/capture_exceptions.rb#L66                          |                                                            |
|                 | sidekiq                                   | queue.sidekiq                                  | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L41             |                                                            |

**Comment by st0012** [comment]
What's the difference between `queue.task.*` and `queue.*`? I think `resque`, `delayed_job`, and `sidekiq` should all have the same op. I'd also argue that `active_job` should share the same op as well because it's just an abstraction layer for the above libraries.

**Comment by AbhiPrasad** [comment]
`queue.task.*` and `queue.*` are both categorized as `queue` operations to the Sentry products - the difference is basically just semantic meaning.

I'd be all for refactoring this list if you have opinions @st0012 - especially to encourage consistency.
