### ISSUE TITLE
Ruby SDK basic OTEL Support

### ISSUE THREAD

**Issue by vladanpaunovic** [getsentry/sentry-ruby#1907]
## We've published the [sentry OpenTelemetry gem](https://rubygems.org/gems/sentry-opentelemetry)! Docs here: https://docs.sentry.io/platforms/ruby/performance/instrumentation/opentelemetry/. Please give it a try and let us know what you think!

Need to spec out what would be needed in individual SDK to enable span processing
- for reference the hack week project in the [Sentry ruby SDK](https://github.com/getsentry/sentry-ruby/pull/1876)

### Details
- SDK develop spec https://github.com/getsentry/develop/pull/686
- span processor - transforming OTEL spans into Sentry spans within Sentry transactions
  - span name and description
  - parent child relationships
- trace/context propagator - including DSC and trace context 
  - https://opentelemetry.io/docs/reference/specification/context/api-propagators/

Open points:
- OTEL support gRPC, Sentry only HTTP
- could have broken child parent relations due to transactions ending
- which Sentry instrumentation needs to be turned off? And how (default, top level options, ...)

- [x] Add documentation https://github.com/getsentry/sentry-docs/pull/5856

**Comment by AbhiPrasad** [comment]
Hey everyone! We've published the `sentry-opentelemetry` gem: https://rubygems.org/gems/sentry-opentelemetry! Please give it a try and let us know what you think, feedback is greatly appreciated.

docs: https://docs.sentry.io/platforms/ruby/performance/instrumentation/opentelemetry/
