### ISSUE TITLE
Transaction sending failed: source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by hendra** [getsentry/sentry-ruby#1911]
### Issue Description

Hi guys,

I got error **source sequence is illegal/malformed utf-8** on my project. This error caused by invalid JSON data and raised from this method line 21 : 
https://github.com/getsentry/sentry-ruby/blob/5fc11d9278c2edd4d9b421cbf6414dff02726b4e/sentry-ruby/lib/sentry/envelope.rb#L21-L26

Here is the log :

![All-Apps-Papertrail (1)](https://user-images.githubusercontent.com/13773/193981718-94ae808d-9bd9-4761-8716-b59d1e3514f5.png)

And here is the data from log :

![All-Apps-Papertrail](https://user-images.githubusercontent.com/13773/193976036-e4b608b4-528e-47b3-9446-aeca71ee1843.png)

As we can see on the log above the description attribute value contain invalid encoding.
I have not idea where those data coming from but seems the data didn't get validated and encoded correctly before it being sent to JSON generator.

I tried to solve the problem by replacing the trace description with valid encoding using method **force_encoding("ISO-8859-1").encode("UTF-8")** on before_send but didn't work. Here is the code :

```ruby
  config.before_send = lambda do |event, hint|
    desc = event.contexts[:trace][:description].dup || ''
    event.contexts[:trace][:description] = desc.force_encoding("ISO-8859-1").encode("UTF-8")
    event
  end
```

So I end up solving the problem by creating a monkey patch to override method **set_description** on class **Sentry::Span** like this : 

```ruby
# frozen_string_literal: true

module SentrySpanPatch
  def set_description(description)
    @description = description.dup.force_encoding("ISO-8859-1").encode("UTF-8")
  end
end

Rails.application.config.to_prepare do
  Sentry::Span.prepend(SentrySpanPatch)
end
```

My question, is this known issue ?? is there a way solve the problem using before_send block so we don't need to monkey patch this ?

### Reproduction Steps

Set Span description attribute with invalid encoding

### Expected Behavior

There should no error "source sequence is illegal/malformed utf-8" appear

### Actual Behavior

There is error "source sequence is illegal/malformed utf-8" appear

### Ruby Version

3.1.2

### SDK Version

5.5.0

### Integration and Its Version

rails 6.1.0
sidekiq 6.5.7
sentry-ruby 5.5.0
sentry-rails 5.5.0
sentry-sidekiq 5.5.0

### Sentry Config

```ruby
# frozen_string_literal: true

Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.breadcrumbs_logger = [:monotonic_active_support_logger, :http_logger]
  config.capture_exception_frame_locals = true
  config.send_client_reports = false
  config.send_default_pii = true
  config.send_modules = false
  config.debug = true
  config.traces_sample_rate = 0.2
  config.excluded_exceptions = [ActionController::RoutingError]
  
  config.before_send = lambda do |event, hint|
    desc = event.contexts[:trace][:description].dup || ''
    event.contexts[:trace][:description] = desc.force_encoding("ISO-8859-1").encode("UTF-8")
    event
  end
end

```

**Comment by sl0thentr0py** [comment]
thx for reporting @hendra, this because of how we [set the redis span description](https://github.com/getsentry/sentry-ruby/blob/c79aa348595aefe983d76d964dfec1a218d27e7e/sentry-ruby/lib/sentry/redis.rb#L55-L59) I guess. I'll try to fix it.

**Comment by hendra** [comment]
That's great!
