### ISSUE TITLE
Any possibility of tweaking @assets_regex?

### ISSUE THREAD

**Issue by jpcody** [getsentry/sentry-ruby#1913]
We have a domain-specific concept within our application of assets (that is, completely separate from Rails' assets). Thus, we have URLs like `/assets` and `/assets/123` and `/assets/5`. We configure our Rails assets prefix to be "asset" to avoid clobbering our own routes. 

But because `@assets_regex` is defined like so:

```rb
%r(\A/{0,2}#{::Rails.application.config.assets.prefix})
```

In our application, it evaluates to:

```rb
# /\A\/{0,2}\/asset/ 
```
Which means all of the following match:

```rb
# /asset/application-[hash].css - Great, this is an asset that should be ignored!
# /assets                       - Not great, this is a slow route that was being ignored
# /assets/15                    - Not great, this one's fine, but it should still be reported on
```

Would the following be a reasonable change:

```diff
- %r(\A/{0,2}#{::Rails.application.config.assets.prefix})
+ %r(\A/{0,2}#{::Rails.application.config.assets.prefix}/)
```

It _seems_ innocuous, but I'm not the one with millions of people out there happily relying on my regex :)

**Comment by sl0thentr0py** [comment]
not sure about the implication of that change (maybe @st0012 can pitch in?)
but we could just expose `assets_regex` as a config value.

**Comment by st0012** [comment]
Since it's not the core SDK, I think making this configurable is better than messing up regexp that may affect a lot of users.
I implemented the config option in https://github.com/getsentry/sentry-ruby/pull/1915

**Comment by jpcody** [comment]
Thanks for the option on this!
