### ISSUE TITLE
Redis instrumentation doesn't work with latest redis-rb library version

### ISSUE THREAD

**Issue by Linuus** [getsentry/sentry-ruby#1931]
### Issue Description

I don't see any Redis traces in Sentry anymore. I think it's since redis-rb was updated a while back to v5.

I believe the issue is that you are patching the `logging` method in `Redis::Client` [here](https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/redis.rb#L74). But, that method has been removed as you can see in the latest `Redis::Client` code [here](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb).

### Reproduction Steps

Run code that calls Redis, using redis-rb version > 5

### Expected Behavior

There should be a redis trace span in Sentry

### Actual Behavior

There is no redis trace Span in Sentry. It just says "Missing Instrumentation".

### Ruby Version

3.1.2

### SDK Version

5.5.0

**Comment by st0012** [comment]
Some investigation results:

- `redis-rb 5.0+` has a new and only dependency called [redis-client](https://github.com/redis-rb/redis-client), which now handles command execution. 
- `redis-client` provides a [middleware concept](https://github.com/redis-rb/redis-client/blob/ad998f3b1e/lib/redis_client/middlewares.rb) that actually makes tracing easier.

So in the future, we'll keep patch logging for `redis-rb 5.0-` and registers a new middleware if we detect `RedisClient` is present.
