### ISSUE TITLE
5.6.0 changed span names, possibly breaking custom sampling (docs not up-to-date)

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-ruby#1938]
### Issue Description

In 5.6.0, op names for HTTP requests were changed from `rails.request` to `http.server` by https://github.com/getsentry/sentry-ruby/pull/1923

If people [followed the documentation](https://docs.sentry.io/platforms/ruby/guides/rails/configuration/sampling/) to have a custom sampler on some queries (or in my case, ignoring some queries like health endpoints), it stopped working after upgrading to 5.6.0 and (in our case) is causing a lot of non-wanted transactions to flood our sentry instance.

The documentation should be updated, and I think a warning should be added to release notes as well.

### Reproduction Steps

As per the documentation, use the following sampler:

```
Sentry.init do |config|
  #...
  config.traces_sampler = lambda do |sampling_context|
    # if this is the continuation of a trace, just use that decision (rate controlled by the caller)
    unless sampling_context[:parent_sampled].nil?
      next sampling_context[:parent_sampled]
    end

    # transaction_context is the transaction object in hash form
    # keep in mind that sampling happens right after the transaction is initialized
    # for example, at the beginning of the request
    transaction_context = sampling_context[:transaction_context]

    # transaction_context helps you sample transactions with more sophistication
    # for example, you can provide different sample rates based on the operation or name
    op = transaction_context[:op]
    transaction_name = transaction_context[:name]

    case op
    when /request/
      # for Rails applications, transaction_name would be the request's path (env["PATH_INFO"]) instead of "Controller#action"
      case transaction_name
      when /health_check/
        0.0
      else
        0.1
      end
    when /sidekiq/
      0.01 # you may want to set a lower rate for background jobs if the number is large
    else
      0.0 # ignore all other transactions
    end
  end
end
```

### Expected Behavior

Health check requests are not sent to Sentry

### Actual Behavior

All HTTP requests are sent to sentry, as their op name is now `http.server`, which is not matching the `/request/` regexp

### Ruby Version

3.1.1

### SDK Version

5.6.0

**Comment by sl0thentr0py** [comment]
apologies @renchap for missing this
added a note to release notes and updating docs

**Comment by jpcody** [comment]
Woof, yeah. This was painful for us, and support had no idea how to help :/

**Comment by sl0thentr0py** [comment]
apologies @jpcody I've relayed your feedback to support.
