### ISSUE TITLE
Ability to mute transaction spans in a block

### ISSUE THREAD

**Issue by booleanbetrayal** [getsentry/sentry-ruby#1943]
**Describe the idea**

Skylight has [`Skylight.mute`](https://www.skylight.io/support/getting-more-from-skylight#mute) support to selectively disable span construction in a block, during operations known to inflate payload sizes unnecessarily or for any reason a developer might not be interested in that information. I haven't found any sort of corresponding support in Sentry, which is causing us [troubles with payload contraints](https://github.com/getsentry/sentry-ruby/issues/1845#issuecomment-1322368691). Likewise, because there is [no ability to interact with the transaction like `before_send`](https://github.com/getsentry/sentry-ruby/issues/1937), we are at a loss for how to deal with this situation.

**Why do you think it's beneficial to most of the users**

Users will likely have requirements where selective disabling of span recording could allow transactions to succeed / be more contextually relevant, where they were not before. 

**Possible implementation**

`Sentry.mute` method that behaves identically to `Skylight.mute`.

**Comment by sl0thentr0py** [comment]
thx @booleanbetrayal I'll discuss this internally and get back to you. Ideally when we implement high level features such as these, we should do them across all languages.

**Comment by booleanbetrayal** [comment]
Thank you @sl0thentr0py . Feel free to reach out if you need any use-case specifics.

**Comment by sl0thentr0py** [comment]
we're going to eventually move to opentelemetry like api's anyway so for this is out of the picture for now, closing.
