### ISSUE TITLE
Transaction status not reported

### ISSUE THREAD

**Issue by nhorton** [getsentry/sentry-ruby#1950]
### Issue Description

All our Rails transactions (rails 7.0.4 / Ruby 3.1.3) are showing up, but they all have this status breakdown in the UI:
```
Status Breakdown
100% unknown
```
We are not doing any special settings anywhere on this, and in fact I removed all exception types that would be ignored just to try to get 404's in there.
There is nothing in the docs on how the status is set, so I can't find a way to alter this.

### Reproduction Steps

Install in rails 7.0.4 and try hitting bad URLs or return non-200 status codes in your controller

### Expected Behavior

I would expect to see a variety of http status codes reported

### Actual Behavior

100% unknown status codes

### Ruby Version

3.1.3

### SDK Version

5.5.0

### Integration and Its Version

Rails - 5.5.0

### Sentry Config

```ruby
Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]
  config.breadcrumbs_logger = %i[active_support_logger http_logger]
  config.enabled_environments = %w[production staging]
  # config.excluded_exceptions += %w[ActionController::RoutingError ActiveRecord::RecordNotFound]
  config.release = ENV["APP_VERSION"]
  config.traces_sample_rate = 1.0
end
```

**Comment by sl0thentr0py** [comment]
@nhorton sorry this slipped through the cracks, are you still interested in us taking a look at this?
