### ISSUE TITLE
jruby 9.4 support

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#1952]
the new jruby 9.4 seems to be causing a bunch of CI failures, investigate changelog and see what all we might need to change.

**Comment by st0012** [comment]
I think there will be a patch release after RubyConf this week. So it's worth waiting a few days for it.

**Comment by sl0thentr0py** [comment]
the latest changes are already using 9.4.5
https://github.com/getsentry/sentry-ruby/actions/runs/7410091572/job/20161654172#step:4:28
so closing
