### ISSUE TITLE
Update the Rails caching guide example for Sentry

### ISSUE THREAD

**Issue by moenodedev** [getsentry/sentry-ruby#1958]
### Issue Description

The [ActiveSupport::Cache::RedisCacheStore](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore) example in the [Caching with Rails: An Overview](https://guides.rubyonrails.org/caching_with_rails.html) Rails guide provides an error reporting example using `Raven`. Update the example to use current Sentry classes and methods.

```ruby
# https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore

cache_servers = %w(redis://cache-01:6379/0 redis://cache-02:6379/0)
config.cache_store = :redis_cache_store, { url: cache_servers,

  connect_timeout:    30,  # Defaults to 20 seconds
  read_timeout:       0.2, # Defaults to 1 second
  write_timeout:      0.2, # Defaults to 1 second
  reconnect_attempts: 1,   # Defaults to 0

  error_handler: -> (method:, returning:, exception:) {
    # Report errors to Sentry as warnings
    Raven.capture_exception exception, level: 'warning',
      tags: { method: method, returning: returning }
  }
}
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Ruby Version

3.1

### SDK Version

5.7.0

### Integration and Its Version

Rails cache

**Comment by moenodedev** [comment]
https://github.com/rails/rails/pull/46665

**Comment by sl0thentr0py** [comment]
ty @moenodedev !
