### ISSUE TITLE
Transaction sending failed: "\xD9" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by thibaultlavoisey** [getsentry/sentry-ruby#1992]
### Issue Description

(Similar to #1911)

Hello,

I got the error `Transaction sending failed: "\xD9" from ASCII-8BIT to UTF-8` that's raised from this method:

https://github.com/getsentry/sentry-ruby/blob/193446b39dfa0d9d6b484631344fdc5aeaa75db8/sentry-ruby/lib/sentry/envelope.rb#L12-L15

Here is the log:

<img width="1107" alt="Screenshot 2023-02-02 at 22 40 55" src="https://user-images.githubusercontent.com/2022117/216462938-32259d01-1138-4098-84be-f6f9efb1ef4a.png">

We're using [MessagePack](https://msgpack.org/index.html) to serialize data before storing them into Redis. The encoding of the string returned by MessagePack is `ASCII_8BIT`. This string is captured in a Sentry span description, and the serialization into JSON fails due to the invalid encoding:

<img width="1674" alt="Screenshot 2023-02-02 at 22 54 31" src="https://user-images.githubusercontent.com/2022117/216462751-bbcd6d4c-8cad-4839-ad34-e412060b21f1.png">

We try to fix this issue using the `before_send` hook, but unfortunately we've not been able to find spans in the event object.

We finally fixed this issue by monkey patching the `set_description` method of the `Sentry::Span` class:

<img width="634" alt="Screenshot 2023-02-02 at 23 14 30" src="https://user-images.githubusercontent.com/2022117/216461631-c1a4d87b-efb3-4980-ae03-c06c6c8899b2.png">

Is this a known issue that should be fixed in Sentry SDK directly? If not, is there a way to deal with non UTF-8 string using the `before_send` hook?

### Reproduction Steps

In a Rails project with Sentry and MessagePack installed:

`Sentry.capture_message(MessagePack.pack('test message'))`

### Expected Behavior

Event is sent to Sentry.

### Actual Behavior

Event isn't sent to Sentry.

### Ruby Version

2.7.4

### SDK Version

5.7.0

### Integration and Its Version

rails (6.0.5.1), sentry-rails (5.7.0), sidekiq (5.2.2), sentry-sidekiq (5.7.0)

### Sentry Config

``` ruby
# frozen_string_literal: true

Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # Tracing Options
  config.traces_sample_rate = 1.0
end
```

**Comment by sl0thentr0py** [comment]
So re:
```
Sentry.capture_message(MessagePack.pack('test message'))
```

I'm not sure that makes sense to support, wdyt @st0012 .

imo this should just be fixed on the Redis integration so that the description only contains well formatted strings and not binary stuff.

**Comment by sl0thentr0py** [comment]
@thibaultlavoisey if I gather correctly, your redis key is `MessagePack`'d?

**Comment by thibaultlavoisey** [comment]
@sl0thentr0py Yes, correct! So the key is displayed in the Sentry span description, and serialization to JSON fails due to non UTF-8 characters (the ones from the key that has been MessagePack'd.
