### ISSUE TITLE
transaction_info: Discarded unknown attribute ?

### ISSUE THREAD

**Issue by ericproulx** [getsentry/sentry-ruby#2009]
Hi,

We're about to update our gem to the latest version 5.8.0 and while testing locally, I found that our events always end up with: 
`There was 1 problem processing this event: transaction_info: Discarded unknown attribute`

<img width="1201" alt="Screenshot 2023-02-22 at 18 16 16" src="https://user-images.githubusercontent.com/8418467/220705318-7574cde6-1673-4518-aadd-aac269f09aef.png">

Our client looks like this
```ruby
Sentry.init do |config|
  config.send_default_pii = true
  config.send_modules = false
end
```

The event sent looks like this
```json
{"event_id"=>"641843cb6b4843da9e1aab3a12e0f86f", "level"=>"error", "timestamp"=>"2023-02-22T17:09:54Z", "release"=>"3c257db09ce", "environment"=>"development", "server_name"=>"dev", "message"=>"", "user"=>{"ip_address"=>"X.X.X.X"}, "tags"=>{"request_id"=>"5092c9d2-0d70-4f12-b01d-1be0f100cbcb"}, "contexts"=>{"os"=>{"name"=>"Linux", "version"=>"#1 SMP Tue Sep 13 07:51:46 UTC 2022", "build"=>"5.15.49-linuxkit", "kernel_version"=>"#1 SMP Tue Sep 13 07:51:46 UTC 2022"}, "runtime"=>{"name"=>"ruby", "version"=>"ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]"}}, "extra"=>{}, "fingerprint"=>[], "breadcrumbs"=>{"values"=>[]}, "transaction"=>"/api/v2/ping", "transaction_info"=>{"source"=>"url"}, "platform"=>"ruby", "sdk"=>{"name"=>"sentry.ruby", "version"=>"5.8.0"}, "type"=>"event" ...
```

`transaction_info"=>{"source"=>"url"}`

But on our self hosted Sentry version 22.6.0, the processed event looks like :
```json
{"event_id":"aab802351e4a401ab4a7fe1679c4970e","project":4,"release":"3c257db09ce","dist":null,"platform":"ruby","message":"","datetime":"2023-02-22T16:58:44.000000Z","tags":[["browser","PostmanRuntime 7.31.0"],["browser.name","PostmanRuntime"],["environment","development"],["level","error"],["os","Linux #1 SMP Tue Sep 13 07:51:46 UTC 2022"],["os.name","Linux"],["request_id","df6978b3-d1eb-417c-a59e-2913b6696a3d"],["runtime","ruby ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]"],["runtime.name","ruby"],["release","3c257db09ce"],["user","id:eric"],["server_name","dev"],["transaction","/api/v2/ping"],["url","http://localhost:3000/api/v2/ping"]],"_meta":{"request":{"headers":{"2":{"1":{"":{"rem":[["@password:filter","s",0,10]],"len":190}}}}},"transaction_info":{"":{"err":["invalid_attribute"]}}} ...,
```

`"transaction_info":{"":{"err":["invalid_attribute"]}}}`

The SDK shows `transaction_info` as a part of it and I can't figured why we have this error.

Thanks

**Comment by roxanebellot** [comment]
Hi ! Running in the same issue, but in python ! 
Curious to see if any lead or solution you found can be applied to our env.

For record : sentry-python 1.15.0, self hosted version... 9.1.2 (shame, I know : we are also looking for upgrading hoping it will solve everything)

**Comment by sl0thentr0py** [comment]
@ericproulx are you also on self-hosted?

**Comment by sl0thentr0py** [comment]
hey, yea this is because we upgraded the protocol in newer versions and added some new fields. That's just a warning, hopefully should not affect any actual product functionality. 

The only answer here unfortunately is to upgrade your self-hosted instance if you can. We can't really backport fixes to older versions for minor UX changes, sorry!

**Comment by ericproulx** [comment]
Alright, we are self-hosted also. Thanks for the info.
