### ISSUE TITLE
Convert calls from Random to SecureRandom throughout the gem.

### ISSUE THREAD

**Issue by Waffleman62** [getsentry/sentry-ruby#2011]
**Describe the idea**

I would like to convert all the calls to Random to SecureRandom throughout the code to make this gem FEDRAMP compliant

**Why do you think it's beneficial to most of the users**

Could use this gem in US Gov implementations.

**Possible implementation**

Below is a patch log of the change:

diff --git a/sentry-raven/lib/raven/configuration.rb b/sentry-raven/lib/raven/configuration.rb
index cf774ad3..ad1291e4 100644
--- a/sentry-raven/lib/raven/configuration.rb
+++ b/sentry-raven/lib/raven/configuration.rb
@@ -527,7 +527,7 @@ module Raven
     def sample_allowed?
       return true if sample_rate == 1.0
 
-      if Random::DEFAULT.rand >= sample_rate
+      if SecureRandom::DEFAULT.rand >= sample_rate
         @errors << "Excluded by random sample"
         false
       else
diff --git a/sentry-raven/spec/raven/cli_spec.rb b/sentry-raven/spec/raven/cli_spec.rb
index 9a8452e3..57d3310f 100644
--- a/sentry-raven/spec/raven/cli_spec.rb
+++ b/sentry-raven/spec/raven/cli_spec.rb
@@ -31,7 +31,7 @@ RSpec.describe Raven::CLI do
     before do
       # make Configuration#sample_allowed? fail
       config.sample_rate = 2.0
-      allow(Random::DEFAULT).to receive(:rand).and_return(3.0)
+      allow(SecureRandom::DEFAULT).to receive(:rand).and_return(3.0)
     end
 
     it "returns false" do
diff --git a/sentry-raven/spec/raven/configuration_spec.rb b/sentry-raven/spec/raven/configuration_spec.rb
index 5ce8bff0..50edb102 100644
--- a/sentry-raven/spec/raven/configuration_spec.rb
+++ b/sentry-raven/spec/raven/configuration_spec.rb
@@ -325,13 +325,13 @@ RSpec.describe Raven::Configuration do
     end
 
     it 'captured_allowed false when sampled' do
-      allow(Random::DEFAULT).to receive(:rand).and_return(0.76)
+      allow(SecureRandom::DEFAULT).to receive(:rand).and_return(0.76)
       expect(subject.capture_allowed?).to eq(false)
       expect(subject.errors).to eq(["Excluded by random sample"])
     end
 
     it 'captured_allowed true when not sampled' do
-      allow(Random::DEFAULT).to receive(:rand).and_return(0.74)
+      allow(SecureRandom::DEFAULT).to receive(:rand).and_return(0.74)
       expect(subject.capture_allowed?).to eq(true)
     end
   end
diff --git a/sentry-raven/spec/raven/transports/http_spec.rb b/sentry-raven/spec/raven/transports/http_spec.rb
index 0cd9422e..01594595 100644
--- a/sentry-raven/spec/raven/transports/http_spec.rb
+++ b/sentry-raven/spec/raven/transports/http_spec.rb
@@ -15,7 +15,7 @@ RSpec.describe Raven::Transports::HTTP do
 
     before do
       config.sample_rate = 0.5
-      allow(Random::DEFAULT).to receive(:rand).and_return(0.6)
+      allow(SecureRandom::DEFAULT).to receive(:rand).and_return(0.6)
     end
 
     it "logs correct message" do
diff --git a/sentry-ruby/lib/sentry/configuration.rb b/sentry-ruby/lib/sentry/configuration.rb
index 2f2da322..a9c8f084 100644
--- a/sentry-ruby/lib/sentry/configuration.rb
+++ b/sentry-ruby/lib/sentry/configuration.rb
@@ -393,7 +393,7 @@ module Sentry
     def sample_allowed?
       return true if sample_rate == 1.0
 
-      Random.rand < sample_rate
+      SecureRandom.rand < sample_rate
     end
 
     def exception_class_allowed?(exc)
diff --git a/sentry-ruby/lib/sentry/transaction.rb b/sentry-ruby/lib/sentry/transaction.rb
index 52efa6fe..9c512ef7 100644
--- a/sentry-ruby/lib/sentry/transaction.rb
+++ b/sentry-ruby/lib/sentry/transaction.rb
@@ -221,7 +221,7 @@ module Sentry
       if sample_rate == true
         @sampled = true
       else
-        @sampled = Random.rand < sample_rate
+        @sampled = SecureRandom.rand < sample_rate
       end
 
       if @sampled
diff --git a/sentry-ruby/spec/sentry/client/event_sending_spec.rb b/sentry-ruby/spec/sentry/client/event_sending_spec.rb
index fe7aad6b..ea4ec20d 100644
--- a/sentry-ruby/spec/sentry/client/event_sending_spec.rb
+++ b/sentry-ruby/spec/sentry/client/event_sending_spec.rb
@@ -27,13 +27,13 @@ RSpec.describe Sentry::Client do
 
       context "with Event" do
         it "sends the event when it's sampled" do
-          allow(Random).to receive(:rand).and_return(0.49)
+          allow(SecureRandom).to receive(:rand).and_return(0.49)
           subject.capture_event(event, scope)
           expect(subject.transport.events.count).to eq(1)
         end
 
         it "doesn't send the event when it's not sampled" do
-          allow(Random).to receive(:rand).and_return(0.51)
+          allow(SecureRandom).to receive(:rand).and_return(0.51)
           subject.capture_event(event, scope)
           expect(subject.transport).to have_recorded_lost_event(:sample_rate, 'event')
           expect(subject.transport.events.count).to eq(0)
@@ -43,7 +43,7 @@ RSpec.describe Sentry::Client do
       context "with TransactionEvent" do
         it "ignores the sampling" do
           transaction_event = subject.event_from_transaction(Sentry::Transaction.new(hub: hub))
-          allow(Random).to receive(:rand).and_return(0.51)
+          allow(SecureRandom).to receive(:rand).and_return(0.51)
 
           subject.capture_event(transaction_event, scope)
 
diff --git a/sentry-ruby/spec/sentry/configuration_spec.rb b/sentry-ruby/spec/sentry/configuration_spec.rb
index f410e2dd..7ae48226 100644
--- a/sentry-ruby/spec/sentry/configuration_spec.rb
+++ b/sentry-ruby/spec/sentry/configuration_spec.rb
@@ -268,12 +268,12 @@ RSpec.describe Sentry::Configuration do
     end
 
     it 'captured_allowed false when sampled' do
-      allow(Random).to receive(:rand).and_return(0.76)
+      allow(SecureRandom).to receive(:rand).and_return(0.76)
       expect(subject.sample_allowed?).to eq(false)
     end
 
     it 'captured_allowed true when not sampled' do
-      allow(Random).to receive(:rand).and_return(0.74)
+      allow(SecureRandom).to receive(:rand).and_return(0.74)
       expect(subject.sample_allowed?).to eq(true)
     end
   end
diff --git a/sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb b/sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb
index 68c5ee16..7cfd946b 100644
--- a/sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb
+++ b/sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb
@@ -267,11 +267,11 @@ RSpec.describe Sentry::Rack::CaptureExceptions, rack: true do
       end
 
       def wont_be_sampled_by_sdk
-        allow(Random).to receive(:rand).and_return(1.0)
+        allow(SecureRandom).to receive(:rand).and_return(1.0)
       end
 
       def will_be_sampled_by_sdk
-        allow(Random).to receive(:rand).and_return(0.3)
+        allow(SecureRandom).to receive(:rand).and_return(0.3)
       end
 
       before do
@@ -418,7 +418,7 @@ RSpec.describe Sentry::Rack::CaptureExceptions, rack: true do
 
     context "when the transaction is sampled" do
       before do
-        allow(Random).to receive(:rand).and_return(0.4)
+        allow(SecureRandom).to receive(:rand).and_return(0.4)
       end
 
       it "starts a transaction and finishes it" do
@@ -476,7 +476,7 @@ RSpec.describe Sentry::Rack::CaptureExceptions, rack: true do
 
     context "when the transaction is not sampled" do
       before do
-        allow(Random).to receive(:rand).and_return(0.6)
+        allow(SecureRandom).to receive(:rand).and_return(0.6)
       end
 
       it "doesn't do anything" do
@@ -494,7 +494,7 @@ RSpec.describe Sentry::Rack::CaptureExceptions, rack: true do
 
     context "when there's an exception" do
       before do
-        allow(Random).to receive(:rand).and_return(0.4)
+        allow(SecureRandom).to receive(:rand).and_return(0.4)
       end
 
       it "still finishes the transaction" do
diff --git a/sentry-ruby/spec/sentry/transaction_spec.rb b/sentry-ruby/spec/sentry/transaction_spec.rb
index 27c03ba2..a1352941 100644
--- a/sentry-ruby/spec/sentry/transaction_spec.rb
+++ b/sentry-ruby/spec/sentry/transaction_spec.rb
@@ -249,7 +249,7 @@ RSpec.describe Sentry::Transaction do
         end
 
         it "prioritizes inherited decision over traces_sample_rate" do
-          allow(Random).to receive(:rand).and_return(0.4)
+          allow(SecureRandom).to receive(:rand).and_return(0.4)
 
           subject.set_initial_sample_decision(sampling_context: { parent_sampled: false })
           expect(subject.sampled).to eq(false)
@@ -257,7 +257,7 @@ RSpec.describe Sentry::Transaction do
         end
 
         it "uses traces_sample_rate for sampling (positive result)" do
-          allow(Random).to receive(:rand).and_return(0.4)
+          allow(SecureRandom).to receive(:rand).and_return(0.4)
 
           subject.set_initial_sample_decision(sampling_context: {})
           expect(subject.sampled).to eq(true)
@@ -268,7 +268,7 @@ RSpec.describe Sentry::Transaction do
         end
 
         it "uses traces_sample_rate for sampling (negative result)" do
-          allow(Random).to receive(:rand).and_return(0.6)
+          allow(SecureRandom).to receive(:rand).and_return(0.6)
 
           subject.set_initial_sample_decision(sampling_context: {})
           expect(subject.sampled).to eq(false)
diff --git a/sentry-ruby/spec/sentry_spec.rb b/sentry-ruby/spec/sentry_spec.rb
index 0ff2110f..a9ed2189 100644
--- a/sentry-ruby/spec/sentry_spec.rb
+++ b/sentry-ruby/spec/sentry_spec.rb
@@ -331,7 +331,7 @@ RSpec.describe Sentry do
 
         expect(transaction.sampled).to eq(false)
 
-        allow(Random).to receive(:rand).and_return(0.4)
+        allow(SecureRandom).to receive(:rand).and_return(0.4)
         transaction = Sentry::Transaction.from_sentry_trace(not_sampled_trace, op: "rack.request", name: "/payment")
         described_class.start_transaction(transaction: transaction)
 
@@ -344,41 +344,41 @@ RSpec.describe Sentry do
       end
 
       it "gives /payment 0.5 of rate" do
-        allow(Random).to receive(:rand).and_return(0.4)
+        allow(SecureRandom).to receive(:rand).and_return(0.4)
         transaction = described_class.start_transaction(op: "rack.request", name: "/payment")
         expect(transaction.sampled).to eq(true)
 
-        allow(Random).to receive(:rand).and_return(0.6)
+        allow(SecureRandom).to receive(:rand).and_return(0.6)
         transaction = described_class.start_transaction(op: "rack.request", name: "/payment")
         expect(transaction.sampled).to eq(false)
       end
 
       it "gives /api 0.2 of rate" do
-        allow(Random).to receive(:rand).and_return(0.1)
+        allow(SecureRandom).to receive(:rand).and_return(0.1)
         transaction = described_class.start_transaction(op: "rack.request", name: "/api")
         expect(transaction.sampled).to eq(true)
 
-        allow(Random).to receive(:rand).and_return(0.3)
+        allow(SecureRandom).to receive(:rand).and_return(0.3)
         transaction = described_class.start_transaction(op: "rack.request", name: "/api")
         expect(transaction.sampled).to eq(false)
       end
 
       it "gives other paths 0.1 of rate" do
-        allow(Random).to receive(:rand).and_return(0.05)
+        allow(SecureRandom).to receive(:rand).and_return(0.05)
         transaction = described_class.start_transaction(op: "rack.request", name: "/orders")
         expect(transaction.sampled).to eq(true)
 
-        allow(Random).to receive(:rand).and_return(0.2)
+        allow(SecureRandom).to receive(:rand).and_return(0.2)
         transaction = described_class.start_transaction(op: "rack.request", name: "/orders")
         expect(transaction.sampled).to eq(false)
       end
 
       it "gives sidekiq ops 0.01 of rate" do
-        allow(Random).to receive(:rand).and_return(0.005)
+        allow(SecureRandom).to receive(:rand).and_return(0.005)
         transaction = described_class.start_transaction(op: "sidekiq")
         expect(transaction.sampled).to eq(true)
 
-        allow(Random).to receive(:rand).and_return(0.02)
+        allow(SecureRandom).to receive(:rand).and_return(0.02)
         transaction = described_class.start_transaction(op: "sidekiq")
         expect(transaction.sampled).to eq(false)
       end

**Comment by st0012** [comment]
Can you share more about `FEDRAMP`? In `sentry-ruby` all uuids/ids are already generated with `SecureRandom`. `Random` is only used for simple sampling.
AFAIK, `SecureRandom` is more expensive than `Random` (correct me if I'm wrong), so I don't want to just change them right away.

**Comment by sl0thentr0py** [comment]
as @st0012 said, the only `Random` calls are for sampling and do not have any security implications. Can we close this?
