### ISSUE TITLE
sidekiq scope potentially leaks when there's an exception

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2012]
we're manually [clearing scope](https://github.com/getsentry/sentry-ruby/blob/803ba7394bc8301bec7c3de6c78c4b019214eb8f/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L35) in the middleware but if there's an exception in the job this might not run. We should just use `push_scope` instead to ensure cleanup.

Try this out with a proper test case and fix it.

**Comment by st0012** [comment]
Yeah you're right, the scope may not be cleared if there's an error. I'll take a look at this.

**Comment by st0012** [comment]
Ok I should've read my own comment first. I intentionally didn't use `ensure` there because at that moment, the exception is not reported yet. So we need to NOT clear the scope until we reach `ErrorHandler` later.

Was there an incident that made you started looking into this?

**Comment by sl0thentr0py** [comment]
I think @untitaker reported this at some point because he was using the SDK on his mastodon instance

**Comment by untitaker** [comment]
> So we need to NOT clear the scope until we reach ErrorHandler later.

The problem is that the ErrorHandler also does not clear the scope.

**Comment by st0012** [comment]
@untitaker Yes you're right, good catch 👍 I've opened #2059 to address it.
