### ISSUE TITLE
Profiling for Ruby

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-ruby#2013]
We want to look into extending our Profiling product with support for Ruby.

On other platforms, we used an existing profiler as a starting point or completely relied on external packages.

When a txn starts, a new `profiling_sample_rate`, which works in relation to `traces_sample_rate`, determines if this txn should be profiled. Our default sample rate on other platforms is 101Hz.

On finish, we convert the raw output to our own profiling format and attach it as a profile envelope item to the transaction.

https://github.com/rbspy/rbspy might be worth looking into, as it's a sampling profiler that also supports outputting a speedscope compatible format, something our own format is derived from.

**Comment by sl0thentr0py** [comment]
notes
* `rbspy` will probably be the most performant is an external binary so it's mostly out
* the other standard _sampling_ profiler is [stackprof](https://github.com/tmm1/stackprof) this is what we'll likely go with
* the standard _tracing_ profiler is [ruby-prof](https://github.com/ruby-prof/ruby-prof) which is also out since it's not a sampling profiler

**Comment by indragiek** [comment]
@sl0thentr0py agree with this, we can't use an external process and we can't use a deterministic (non-sampling) profiler, so `stackprof` seems like a reasonable choice. Are there any other options for in-process sampling profilers?

**Comment by sl0thentr0py** [comment]
not that I know of or can find, @st0012 do you know any other ones?
The table here is a good survey of the ruby profiler landscape
https://jvns.ca/blog/2017/12/17/how-do-ruby---python-profilers-work-/


![image](https://user-images.githubusercontent.com/6536764/223174796-a0fc5b0a-9f64-4247-a751-c88e3e14f114.png)

**Comment by st0012** [comment]
For Rails, I think we can use Shopify's [app_profiler](https://github.com/Shopify/app_profiler). 

On the first glance:
- It's a gem with native Rails integration
- It also provides a Rack middleware or can be invoked with a block
- It's still actively maintained
- It's battle-tested at Shopify

However, I don't have much experience profiling in production either. So we'll need to do some testing with it ourselves, but do we have a good application/partner for that?

**Comment by st0012** [comment]
Ah sorry I didn't notice `app_profiler` is based on `stackprof` 🤦‍♂️ 

> sample profile from that

That looks amazing.

> it does not include threading info on the captured stacks

Can you explain more on this?

> patch stackprof upstream / fork to send threading info somehow

Given that we don't have experience writing profilers yet, maybe we can go with this first? Even if the result is not accepted by the upstream, at least we'll know more on what we actually want to do.

**Comment by sl0thentr0py** [comment]
yes of course and thanks for the feedback! 

> threading info

In a multi-threaded server like puma, there's stuff happening on each thread, and our [`Sample`](https://github.com/getsentry/relay/blob/643bb93abe13500cfab149a606799a0df8c40c31/relay-profiling/src/sample.rs#L44-L45) structure takes a `thread_id` so you can record and store call stacks from each thread.

Here's the thread switcher in the UI from a multi-threaded python profile.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/6536764/227931356-f5319eed-1daa-425f-a5bf-a61b521a61fa.png">

---

How stackprof works (in `:wall` mode) is
* stores the [thread `Stackprof.start` was called from in `target_thread`](https://github.com/tmm1/stackprof/blob/52d1df6502eaede5061a2b5d28026e982bcf262a/ext/stackprof/stackprof.c#L224) and [forwards the incoming `SIGALRM` signal to that thread](https://github.com/tmm1/stackprof/blob/52d1df6502eaede5061a2b5d28026e982bcf262a/ext/stackprof/stackprof.c#L728-L739) 
* then uses this signal and calls ruby's [`rb_profile_frames` API](https://github.com/tmm1/stackprof/blob/52d1df6502eaede5061a2b5d28026e982bcf262a/ext/stackprof/stackprof.c#L620) to record the call stack in that _current thread_
  * see this [open issue for multi-threaded profiling support](https://bugs.ruby-lang.org/issues/10602)
  * and this [abandoned attempt](https://github.com/glassechidna/stackprofx) at augmenting stackprof - this is basically what we will eventually want to do

>  maybe we can go with this first?

For the first MVP, we decided that we will just go with a limited single thread use case, i.e. Stackprof can only run on one thread at a time and will early return if already running. Eventually based on adoption, we might invest time in doing something similar to `stackprofx `above. :)

**Comment by sl0thentr0py** [comment]
I also fixed some timing issues (but still having some more spurious samples that I'm trying to debug). I'll post some better profiles once everything's done.

If you're curious, I also tried out some simple multi-threaded use cases below with this code.
```ruby
require 'sentry-ruby'
require 'debug'

Sentry.init do |config|
  config.release = "profiling"
  config.debug = true
  config.traces_sample_rate = 1.0
end

def t1
  10000.times { 2 + 2 }
  sleep 0.2
  puts('t1')
end

def t2
  transaction = Sentry.start_transaction(name: 'profiling')
  Sentry.get_current_scope.set_span(transaction)

  sleep 0.5
  t1
  20000.times { 2 * 2 }
  puts('t2')

  transaction.finish
end

def main
  sleep 0.2
  20000.times { 2 ** 2 }
  puts('main')
end


# transaction = Sentry.start_transaction(name: 'profiling')
# Sentry.get_current_scope.set_span(transaction)

threads = [Thread.new { t1 }, Thread.new { t2 }]
main
threads.each(&:join)

# transaction.finish
```

transaction on main thread
https://sentry-sdks.sentry.io/profiling/profile/sentry-ruby/6cde0f4d2f2f405a9246d1f93c8e836b/flamechart/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=42&view=top+down

transaction on child thread
https://sentry-sdks.sentry.io/profiling/profile/sentry-ruby/3794ecdb8ad84140af610646017422c0/flamechart/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=42&view=top+down

**Comment by sl0thentr0py** [comment]
docs PRs:

* https://github.com/getsentry/sentry-docs/pull/6650
*
