### ISSUE TITLE
How to filter sending transactions to Sentry on request IP address? 

### ISSUE THREAD

**Issue by zedtux** [getsentry/sentry-ruby#2019]
There is a probe which is producing a lot of requests to my app, which produce a lot of transaction pushed to Sentry.

I found from the documentation the `before_send_transaction` but I can't figure out where to find the request IP address from the `event` parameter. 

So, could you please help me in order to access the Rails request IP address so that I can filter the transactions pushed to Sentry?

**Comment by sl0thentr0py** [comment]
@zedtux we [filter the IP address headers here](https://github.com/getsentry/sentry-ruby/blob/00843f3c109655c13e8e1651165723ca0a0aa160/sentry-ruby/lib/sentry/interfaces/request.rb#L49-L51) so they won't be present in the `event.request.headers` object if `send_default_pii = false`.

You can however use `sampling_context[:env]` in your `traces_sampler` as outlined here to not sample those transactions.
https://github.com/getsentry/sentry-ruby/issues/1830#issuecomment-1148553129

**Comment by zedtux** [comment]
Quick update, just to not get bothered by the stupid bot. 😉. It's still on my list to try the suggested answer!

**Comment by sl0thentr0py** [comment]
this has been open for fairly long so closing, please re-open if you need help
