### ISSUE TITLE
How to update excluded_exceptions only when process is running as Sidekiq worker

### ISSUE THREAD

**Issue by HarlemSquirrel** [getsentry/sentry-ruby#2020]
How can we remove or specify `excluded_exceptions` based on if the running process is a Sidekiq worker, Rails server, or something else?

I have a Rails application that also uses Sidekiq and it appears that the default excluded exceptions are a combined list of those for Rails and Sidekiq.

Specifically, I would like to remove `ActiveRecord::RecordNotFound` from the exclusion list when the process is running as a Sidekiq worker.

```
irb(main):013:0> Sentry.configuration.excluded_exceptions
=> 
["Mongoid::Errors::DocumentNotFound",
 "Rack::QueryParser::InvalidParameterError",
 "Rack::QueryParser::ParameterTypeError",
 "Sinatra::NotFound",
 "AbstractController::ActionNotFound",
 "ActionController::BadRequest",
 "ActionController::InvalidAuthenticityToken",
 "ActionController::InvalidCrossOriginRequest",
 "ActionController::MethodNotAllowed",
 "ActionController::NotImplemented",
 "ActionController::ParameterMissing",
 "ActionController::RoutingError",
 "ActionController::UnknownAction",
 "ActionController::UnknownFormat",
 "ActionDispatch::Http::MimeNegotiation::InvalidType",
 "ActionController::UnknownHttpMethod",
 "ActionDispatch::Http::Parameters::ParseError",
 "ActiveRecord::RecordNotFound",
 "Sidekiq::JobRetry::Skip"]
```

**Comment by sl0thentr0py** [comment]
@HarlemSquirrel I guess you can use [`Sidekiq.server?`](https://github.com/sidekiq/sidekiq/blob/3b93c250d08df79e9296ade0c0e15d7e512035af/lib/sidekiq.rb#L48-L50) to conditionally change `config.excluded_exceptions` in your initializer? I haven't tried this myself so let me know if it doesn't work.

**Comment by HarlemSquirrel** [comment]
Yeah, that works! Thank you!

```rb
if Sidekiq.server?
    config.excluded_exceptions.delete("ActiveRecord::RecordNotFound")
  end
```
