### ISSUE TITLE
Exception being registered that are added in excluded_exceptions 

### ISSUE THREAD

**Issue by Harshit11071998** [getsentry/sentry-ruby#2037]
I have added few classes in config.excluded_exceptions.
But those class exception are still being registered in sentry.
` config.excluded_exceptions += ['ActiveRecord::RecordNotUnique', 'ActiveRecord::ConnectionTimeoutError', 'Errno::EPIPE']`

I found a similar thread here [#1430](https://github.com/getsentry/sentry-ruby/issues/1430)
But this also doesn't have any resolution for the same problem.

[ActiveRecord::RecordNotUnique]

I am using these gems
sentry-rails (5.9.0)
sentry-ruby (5.9.0)
sentry-raven (3.1.2)

**Comment by st0012** [comment]
You should remove `sentry-raven` from your Gemfile as it's been deprecated and doesn't work with the new SDK. Also, it'd be helpful if you can post your Sentry configuration here.

**Comment by Harshit11071998** [comment]
@st0012 Removing the gem fixed the issue.
It was some how still picking the `sentry-raven` gem instead of `sentry-ruby`.
Though configuration was of `sentry-ruby`.

Anyways thanx for the suggestion. Its fixed
