### ISSUE TITLE
Add transactions and profiling for rspec/minitest

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2046]
Some users have asked for profiling support for their test suite to identify bottlenecks.

We'd need to first add performance / transactions around test runs and then enable profiling there.

**Comment by st0012** [comment]
IMO, this should be extracted to a separate gem. And I'm also not sure if our SDK is the best tool for this.
While I understand the desire to utilise Sentry's nice UI for it, the size limit on the events payload means many data would be lost.

**Comment by sl0thentr0py** [comment]
I also kinda agree @st0012.
A customer asked so I just opened a ticket to track, we'll evaluate if we really want this.

**Comment by sl0thentr0py** [comment]
I'm closing this as not planned, imo doesn't fit into Sentry's value prop and if people really want, they can start a transaction with `profiles_sample_rate` set to `.
