### ISSUE TITLE
breadcrumbs_logger causes exception in background worker: Net::OpenTimeout

### ISSUE THREAD

**Issue by seocahill** [getsentry/sentry-ruby#2060]
### Issue Description

I'm testing turning off legacy async job in rails app and using built in worker per deprecation warning

Sending message causes OOM killed in pod, cause seems to be huge params logged.  

**Removing breadcrumbs logger config fixes.**

### Reproduction Steps

Image ruby:3.0-alpine
rails-6.1.7.3
sentry-ruby-5.9.0
sentry-rails-5.9.0

```
Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]
  config.breadcrumbs_logger = [:active_support_logger, :http_logger] <== ISSUE
end

Sentry.capture_message "test"
```

### Expected Behavior

background job posts message to sentry.io

### Actual Behavior

```
# killed pod
Sentry.capture_message "test"
2023-06-27 15:11:21.499492 I [22:worker-1 logging_helper.rb:15] Rails -- sentry -- [Transport] Sending envelope with items [event] c55e1d9b8e494b9bb00ee6daf2e64df7 to Sentry
2023-06-27 15:11:23.798450 E [22:worker-1 logging_helper.rb:9] Rails -- sentry -- Event sending failed: Net::OpenTimeout
2023-06-27 15:11:23.999700 I [22:worker-1 logging_helper.rb:15] Rails -- sentry -- Unreported Event: test
2023-06-27 15:11:24.198138 E [22:worker-1 logging_helper.rb:9] Rails -- sentry -- exception happened in background worker: Net::OpenTimeout
Killed

# with enough resources to send
 <Sentry::ThreadsInterface:0x00007f27ebc478f8 @id=28900, @name="28900", @current=true, @crashed=true, @stacktrace=nil> 

# or...
...<huge trace> 
and succeeds e.g. https://accounto.sentry.io/share/issue/f704c7d80c1d428b92149a68575a3f49/



### Ruby Version

ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux-musl]

### SDK Version

5.9

### Integration and Its Version

rails

### Sentry Config

Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]
end

**Comment by seocahill** [comment]
Just to confirm the root cause is the :active_support_logger.  Constraining breadcrumbs length will allow send to succeed at least but it seems to be dumping huge volumes of trace info in the breadcrumbs.  Going to try downgrading just to see.

**Comment by seocahill** [comment]
Issue  persists in 4.9

**Comment by sl0thentr0py** [comment]
@seocahill we actually changed our handling of active support breadcrumbs in https://github.com/getsentry/sentry-ruby/pull/2048 to an allowlist.
which we will release shortly. Maybe this fixes the huge payload as well.

**Comment by seocahill** [comment]
This fixes the huge payload, sending works ok now.  I'm unsure if this issue is truly fixed -  I'll leave it to you @sl0thentr0py to decide if the issue should be closed or not.

Thinking about the design, was running in background worker not more resilient from a user pov?  

I feel like I'm potentially adding some instability to the api server here, in that I'm now spawning extra processes in the same container as the api server, that could potentially result in OOM, given large params (as in this case) or some other unforeseen variable / issue.

Thank you for the quick response and fix btw, appreciate it and the gem.
