### ISSUE TITLE
Error in capturing low-level errors when using puma v4

### ISSUE THREAD

**Issue by krororo** [getsentry/sentry-ruby#2067]
### Issue Description

I got an error in capturing low-level errors when using puma v4.
The following error messages are output in large numbers.

```
Error in reactor loop escaped: wrong number of arguments (given 3, expected 2) (ArgumentError)
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/server.rb:961:in `lowlevel_error'
/path/to/lib/ruby/gems/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/puma.rb:7:in `lowlevel_error'
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/reactor.rb:263:in `rescue in block in run_internal'
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/reactor.rb:218:in `block in run_internal'
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/reactor.rb:157:in `each'
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/reactor.rb:157:in `run_internal'
/path/to/lib/ruby/gems/3.1.0/gems/puma-4.3.12/lib/puma/reactor.rb:313:in `block in run_in_thread'
```

I think the related PR is below.
* #2026

There seems to have been arguments change in the following PR that went into puma v5.
* https://github.com/puma/puma/pull/2203

### Reproduction Steps

**Gemfile**

```rb
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails'

gem 'puma', '4.3.12'
gem 'sentry-ruby', '~> 5.9'
```

Start server

```console
bundle exec rails server
```

### Expected Behavior

No error messages should be output.

### Actual Behavior

Error message is output.

### Ruby Version

3.1.4

### SDK Version

5.10.0

### Integration and Its Version

Puma 4.3.12

**Comment by EugeneKovalev** [comment]
Any news on this? I am facing the same error!

**Comment by sl0thentr0py** [comment]
@st0012 i'm a bit swamped rn, do you know why this would happen?

**Comment by nadirkhann487** [comment]
same issue for me as well

**Comment by EugeneKovalev** [comment]
Upgrade to puma 5 helped. They don’t support puma 4.Best regards,Eugene Kovalev / Yevgeniy Kovalev / Eugeniusz KowalewOn 12 Oct 2023, at 01:51, Nadir Khan ***@***.***> wrote:﻿
same issue for me as well

**Comment by st0012** [comment]
@sl0thentr0py Yeah it's because of the puma patch. I'll open a fix shortly.
