### ISSUE TITLE
Send trace and span origin

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-ruby#2068]
See https://github.com/getsentry/team-sdks/issues/14

**Comment by natikgadzhi** [comment]
Reference implementation in JS SDK: https://github.com/getsentry/sentry-javascript/pull/8765/files#diff-5d0f3b11ab97c0b33599238bf8fd5d242e334bbe1f625612ab2595011c0a3c19

@st0012, @sl0thentr0py, tracing noob here. Do you think we should set origin into a `Transaction`, or at a `Span` level? 

If we go with Spans: 
- Add Span.origin attr. Make sure it's serialized correctly. Default to parent_span.origin, or `manual`, if there's no parent span.
- Then once that's done — we'll go over integrations that make spans and add origins to each of those invocations.

Right? What am I missing?

**Comment by sl0thentr0py** [comment]
yes that's fine (on the span)

**Comment by natikgadzhi** [comment]
Alright, I'll work on this next once I get my open PRs sorted out, unless you beat me to it.
