### ISSUE TITLE
sentry-ruby does not send profiling data because payload is oversized

### ISSUE THREAD

**Issue by arusa** [getsentry/sentry-ruby#2070]
### Issue Description

I enabled profiling, but most of the time don't get any profiling information on interesting requests, because sentry-ruby throws away the Envelope with the message:

```
sentry: Envelope item [profile] is still oversized after size reduction: {event_id: 34, platform: 6, version: 3, profile: 261786, environment: 12, release: 4, timestamp: 27, device: 25, os: 72, runtime: 90, transaction: 153}
```

The serialize function tries to remove breadcrumbs and stacktrace to reduce the size below MAX_SERIALIZED_PAYLOAD_SIZE, but it seems to me, that MAX_SERIALIZED_PAYLOAD_SIZE (200kb) is too small for profiling data.

https://github.com/getsentry/sentry-ruby/blob/7764384e07bf7927c5a9a9d4c19688e9c1b11f56/sentry-ruby/lib/sentry/envelope.rb#L25

### Reproduction Steps

Try to find profile data for requests with too much profile information. In my case I would need profiling in formation in Sentry for Proposal#index of the open source application https://github.com/decidim/decidim

Look in rails application logs for the message "Envelope item [profile] is still oversized after size reduction", probably it happens in a lot of rails applications.

### Expected Behavior

I would expect sentry-rails to send profile information for all requests (according to config.profiles_sample_rate) to sentry, and to not throw away valid and important profiling information.

### Actual Behavior

sentry-ruby throws away profiling information and I can't find any reason in Sentry why still no profiling data is arriving. I can only find information in the application logs, but also no error or warning.

### Ruby Version

3.0.6

### SDK Version

5.10.0

### Integration and Its Version

Rails 6.1.7.4

### Sentry Config

Sentry.init do |config|
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]
  config.traces_sample_rate = 1.0
  config.profiles_sample_rate = 1.0
end

**Comment by antonpirker** [comment]
Hey @arusa !

Thanks for bringing this up. @sl0thentr0py is on a conference right now, so he can not reply. 
But I guess it would be save to increase the max payload size, because the ingestion part of Sentry has a higher limit. 
@sl0thentr0py will address this when he is back from the conference.

**Comment by arusa** [comment]
Hey, any updates on this topic? Does it make sense to allow a higher payload size than 200kb?
(see MAX_SERIALIZED_PAYLOAD_SIZE https://github.com/getsentry/sentry-ruby/blob/97da98c5b44b98e00f65685cd9efb473854069cd/sentry-ruby/lib/sentry/envelope.rb#L8)

**Comment by sl0thentr0py** [comment]
#2108 should help with this so closing for now

**Comment by twolfvb** [comment]
Although this was closed, my solution to a huge payload where the POST data had some binary encoded files was to butcher the sentry scope and remove the files.

```
    rescue_from 'my_custom_error' do |exception|
      Sentry.with_scope do |scope|
        scope.set_extra(:params, '')
        ...
        scope.set_rack_env(scope.rack_env.except(...).merge(<relevant parameters with files scrubbed>))
        Sentry.capture_exception(exception)
      end
      respond_unexpected_error(detail: exception.detail)
    end
```

**Comment by sl0thentr0py** [comment]
@twolfvb that works but you could also probably do that more cleanly in `before_send` which is a hook we expose for stuff like this.
https://docs.sentry.io/platforms/ruby/configuration/filtering/#using-
