### ISSUE TITLE
Migration Guide Does Not Mention Sentry 20.6.0 Requirement

### ISSUE THREAD

**Issue by alexymik** [getsentry/sentry-ruby#2074]
https://github.com/getsentry/sentry-ruby

in `README.md` it states:

> If you use self-hosted Sentry, please also make sure its version is above 20.6.0.

However, on the Migration Guide

https://docs.sentry.io/platforms/ruby/guides/rails/migration/

There is no mention of this requirement.

Separately, what is the maximum version of Sentry server that `sentry-raven` supports?

**Comment by shanamatthews** [comment]
@sl0thentr0py - no issues with having it in docs, but we'd need the SDK engineers to maintain the info.

I wonder if it might make sense to keep it somewhere in the develop docs self-hosted section (https://develop.sentry.dev/self-hosted/). I think self-hosted folks would likely check there.
