### ISSUE TITLE
Sanitize Sidekiq args?

### ISSUE THREAD

**Issue by ericproulx** [getsentry/sentry-ruby#2075]
Hi,

Is there a way to sanitize Sidekiq args ? We're already sanitizing within the `before_send` but I can't find how to sanitize Sidekiq context through an `event`

Thanks.

**Comment by ericproulx** [comment]
> @ericproulx by sanitize you mean filter out or replace?

Replace

**Comment by natikgadzhi** [comment]
@ericproulx, so something like [this behavior](https://github.com/getsentry/sentry-ruby/blob/82e1ffe711af287ddc23e8517bdb8275beff94d5/sentry-raven/lib/raven/processor/sanitizedata.rb#L101), but for sidekiq job arguments, when they're reported via Sentry?

When Raven split into new sentry gems, they've moved away from allowing you to set what fields and headers to sanitize to `config.send_default_pii = false`. https://docs.sentry.io/platforms/ruby/migration/#removed-processors

There's already [`Sentry::Sidekiq::ContextFilter`](https://docs.sentry.io/platforms/ruby/migration/#removed-processors) that filters out sidekiq context. If you wanted to filter things out, you could patch into that. 

@st0012, what's our stance on filtering out personal / sensitive information beyond the `filter_default_pii` info? I assume that it's up to the user now, in `before_send` and such?

**Comment by st0012** [comment]
That question is better asking @sl0thentr0py as it's probably changed since the last time I answered a similar question 😛

**Comment by sl0thentr0py** [comment]
`before_send` should work for this, it should be available in `event.contexts[:sidekiq]` where you can do the replace/masking.
