### ISSUE TITLE
Redis middleware adds 10% to micro-benchmarks

### ISSUE THREAD

**Issue by jdelStrother** [getsentry/sentry-ruby#2080]
### Issue Description

The Redis middleware (https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/redis.rb) seems to add about 10% overhead to each redis call [^*], even though we don't have Sentry's redis breadcrumbs enabled.

 [^*]: in artificial micro-benchmarks

### Reproduction Steps

Comment out the GlobalRedisInstrumentation insertion at the bottom of https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/redis.rb so we can compare it on a per-instance basis:

```ruby
redis = RedisClient.new
redis_with_sentry = RedisClient.new(middlewares: [Sentry::Redis::GlobalRedisInstrumentation])
Benchmark.ips {|x|
  x.report("base") { redis.call('set', 'x', 1) }
  x.report('with-sentry') { redis_with_sentry.call('set', 'y', 1) }
  x.compare!
}
```

### Expected Behavior

Minimal overhead

### Actual Behavior

11% overhead:

```
Warming up --------------------------------------
                base     3.329k i/100ms
         with-sentry     2.999k i/100ms
Calculating -------------------------------------
                base     32.804k (± 3.9%) i/s -    166.450k in   5.082409s
         with-sentry     29.596k (± 3.5%) i/s -    149.950k in   5.072707s

Comparison:
                base:    32804.3 i/s
         with-sentry:    29596.0 i/s - 1.11x  slower
```

If I disable spans & breadcrumbs (with the following change:)

```diff
diff --git a/sentry-ruby/lib/sentry/redis.rb b/sentry-ruby/lib/sentry/redis.rb
index 8646cf24..b9c3d985 100644
--- a/sentry-ruby/lib/sentry/redis.rb
+++ b/sentry-ruby/lib/sentry/redis.rb
@@ -11,7 +11,7 @@ module Sentry
     end
 
     def instrument
-      return yield unless Sentry.initialized?
+      return yield unless Sentry.initialized? && Sentry.configuration.breadcrumbs_logger.include?(LOGGER_NAME)
 
       Sentry.with_child_span(op: OP_NAME, start_timestamp: Sentry.utc_now.to_f) do |span|
         yield.tap do
```

it returns to negligible overhead:

```
Warming up --------------------------------------
                base     3.268k i/100ms
         with-sentry     3.132k i/100ms
Calculating -------------------------------------
                base     32.820k (± 3.3%) i/s -    166.668k in   5.084203s
         with-sentry     31.543k (± 2.8%) i/s -    159.732k in   5.068441s

Comparison:
                base:    32819.9 i/s
         with-sentry:    31543.2 i/s - same-ish: difference falls within error
```

We're only using the error-monitoring part of Sentry, and don't use the redis_logger breadcrumbs. Could we have a way of opting out?

### Ruby Version

3.2.2

### SDK Version

5.10.0

### Integration and Its Version

Rails 7.0

### Sentry Config

```ruby
Sentry.init do |config|
  if Rails.env.is_production?
    config.dsn = "..."
  end
  config.excluded_exceptions += %w[
    AbstractController::ActionNotFound
    ActionController::BadRequest
    ActionController::InvalidAuthenticityToken
    ActionController::InvalidCrossOriginRequest
    ActionController::RoutingError
    ActionController::UnknownFormat
    ActionController::UnknownHttpMethod
    ActionDispatch::ParamsParser::ParseError
    ActiveRecord::RecordNotFound
    Mime::Type::InvalidMimeType
  ]

  config.include_local_variables = true

  # Sentry by default doesn't include params on error reports.
  # Which is probably reasonable, but can make it hard to determine error-causes.
  # I think we can assume that our query-strings don't contain anything too sensitive.
  config.rack_env_whitelist = [*config.rack_env_whitelist, "QUERY_STRING"] # rubocop:disable Naming/InclusiveLanguage

  # This will exclude exceptions that are triggered by one of the ignored
  # exceptions. For example, when any exception occurs in a template,
  # Rails will raise a ActionView::Template::Error, instead of the original error.
  config.inspect_exception_causes_for_exclusion = true
end
```

**Comment by jdelStrother** [comment]
Just to follow up with some real-world data rather than the micro-benchmark - I kept seeing Sentry crop up in flamegraphs in code I was profiling, which is why I started to look into this. However, after monkey-patching `Sentry::Redis#instrument` to just immediately call `yield`, I'm not really seeing any dent in our end-to-end transaction times (even in throttled Rack::Attack responses which spend ~ 30% of their time talking to redis).

I still think globally inserting a redis middleware that we don't use would be nice to be able to opt-out of, but just wanted to confirm I don't think this is having much real-world impact on our app.

**Comment by sl0thentr0py** [comment]
@st0012 this is the same discussion as with puma. Ultimately I guess we should always provide a config where people can opt out of certain patches (other SDKs have `integrations` so this is easier to manage), what do you think?

**Comment by st0012** [comment]
I'm not sure if it's the same as with Puma. The Puma's case was for error monitoring and the root cause was insufficient filtering default when the integration was introduced, not performance overhead. Once it's added, there's no need to opt-out on that one.

That being said, I agree that we'll eventually need a way to mass configure integrations to opt-in/out to, like most other services' SDKs have.

**Comment by sl0thentr0py** [comment]
whatever the reason, people should be able to opt out of patches, it's fine to have them on by default.

**Comment by sl0thentr0py** [comment]
tracking in https://github.com/getsentry/sentry-ruby/issues/2095, closing this
