### ISSUE TITLE
Sentry.logger does not default to Rails.logger

### ISSUE THREAD

**Issue by viktorvsk** [getsentry/sentry-ruby#2081]
### Issue Description

Documentation [says](https://docs.sentry.io/platforms/ruby/configuration/options/):

> The logger used by Sentry. Default is Rails.logger in Rails, otherwise an instance of Sentry::Logger.

But actually if logger is not specified in config its `Sentry::Logger.new(STDOUT)`

### Reproduction Steps

* Create rails app `rails new test-sentry`
* Add `gem "sentry-ruby"` to `Gemfile`
* Run `bundle install`
* Create `config/initializers/sentry.rb` with the following content:
```ruby
if ENV["SENTRY_DSN"].present?
  Sentry.init do |config|
    config.dsn = ENV["SENTRY_DSN"]
    config.breadcrumbs_logger = [:sentry_logger, :http_logger]

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    config.traces_sample_rate = 1.0
    # or
    config.traces_sampler = lambda do |_context|
      true
    end
  end
end
```
* Run `SENTRY_DSN=anything bin/rails runner "puts Sentry.logger == Rails.logger"`

### Expected Behavior

true

### Actual Behavior

false

### Ruby Version

3.2.2

### SDK Version

5.10.0

### Integration and Its Version

Rails 7

### Sentry Config

```ruby
if ENV["SENTRY_DSN"].present?
  Sentry.init do |config|
    config.dsn = ENV["SENTRY_DSN"]
    config.breadcrumbs_logger = [:sentry_logger, :http_logger]

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    config.traces_sample_rate = 1.0
    # or
    config.traces_sampler = lambda do |_context|
      true
    end
  end
end

```

**Comment by sl0thentr0py** [comment]
@viktorvsk did you also add `sentry-rails` to your `Gemfile`?

**Comment by viktorvsk** [comment]
No, I did not add it. Adding `sentry-rails` fixes this. However, it's not clear from  documentation (probably, after changes in `sentry-raven` etc) that I have to. I've found that quote about `Rails.logger` on `ruby` SDK which doesn't say anything about `sentry-rails` (Rails integration docs however are clear on that)

Apart from settings `Sentry.logger` what are the advantages of using `sentry-rails` in a Rails app? Could you point me to the docs in this regard? Initially I didn't use it because I though its outdated after SDK changes

Thanks!
