### ISSUE TITLE
Sentry Crons support!

### ISSUE THREAD

**Issue by adamzapasnik** [getsentry/sentry-ruby#2090]
Is there any plan to support Sentry Crons in Ruby sdk?

https://docs.sentry.io/product/crons/getting-started/

**Comment by stephanie-anderson** [comment]
Hey Adam! Yes, development is planned within the next 2-3 weeks ✌️

**Comment by sl0thentr0py** [comment]
@adamzapasnik yes we will do this soon, can you tell me what gems you'd like to see support for?

**Comment by sl0thentr0py** [comment]
gems we will support first
- sidekiq-cron
- sidekiq-scheduler
- whenever
- clockwork

**Comment by sl0thentr0py** [comment]
manual crons support is done, automatic for gems split into separate task

**Comment by sl0thentr0py** [comment]
released in 5.12.0! try it out and let us know @adamzapasnik

**Comment by swanson** [comment]
@sl0thentr0py we've been testing this out this week in our project. Do you plan to add a `heartbeat` method for times when we aren't reporting runtime? This seems like it reads better in our code -- even if it is just an alias for `capture_check_in` that doesn't return the check_id

**Comment by natikgadzhi** [comment]
> Do you plan to add a heartbeat method for times when we aren't reporting runtime? 

You can just send a check_in :ok, ignoring the returned value, that'll do a heartbeat.
```ruby
  Sentry.capture_check_in(
    "rake-task-example",
    :ok, 
    monitor_config: monitor_config
  )
```

Does that solve it?

> I'm also finding it a bit confusing that the Ruby parameters are things like checkin_margin but the UI in Sentry for this same field in the UI is called Grace Period.

I _think_ the underlying field is internally called `checkin_margin` in the API as well. 

Interestingly, I didn't find documentation on how to programmatically create monitors (i.e. pass `monitor_config`) in Python, but I see it accepts `monitor_config`, and I'm certain I've seen a demo of it — so I assume it's just a hash, let me double-check what keys are there.

**Comment by sl0thentr0py** [comment]
> I'm also finding it a bit confusing that the Ruby parameters are things like checkin_margin but the UI in Sentry for this same field in the UI is called Grace Period. Might be worth aliasing these.

@swanson  I passed this feedback to the product team, thanks!

Re: heartbeat, see [this](https://docs.sentry.io/platforms/ruby/crons/#heartbeat) (and also as @natikgadzhi said above).
We're still iterating on crons so we might make some of this APIs better eventually, thanks for the feedback again!

Docs for creating programmatically with `monitor_config` are [here](https://docs.sentry.io/platforms/ruby/crons/#upserting-cron-monitors).

I will also eventually get around to doing what celery does above with gems like `sidekiq-cron`, `sidekiq-scheduler`, `clockwork`, `whenever` and so on.

**Comment by swanson** [comment]
Is it too late to change `capture_check_in` and `checkin_margin` to use consistent spacing? Is it supposed to be `check_in` or `checkin`?

**Comment by sl0thentr0py** [comment]
I just followed what other SDKs already implemented in camel case - `captureCheckIn`, `checkinMargin`, etc.
Anyway, changing this at this point is difficult without breaking stuff and aliases and not that important, sorry.
