### ISSUE TITLE
Try vernier for profiling

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2124]
https://github.com/jhawthorn/vernier

does multithreaded stuff

**Comment by natikgadzhi** [comment]
@sl0thentr0py, mind if I try and poke around?

**Comment by natikgadzhi** [comment]
Still on it — got distracted by shiny things like Spotlight and Crons 🤦🏼

**Comment by sl0thentr0py** [comment]
it's ok.. take your time we're happy to take contributions but you don't have to do everything at once :)

**Comment by solnic** [comment]
@sl0thentr0py do we want to support both and make it configurable?
