### ISSUE TITLE
👯‍♀️ Multiple dsn's per one codebase. Possible? How?

### ISSUE THREAD

**Issue by d4mk0** [getsentry/sentry-ruby#2132]
Hi!

**Problem:**
Our services creates too much events for sentry and we use too much quota events.
We raised sentry self hosted solution for decrease quota (thank u for open source!!!).
But sometimes self hosted solution crashes by different reasons.
And we want to send events to 2 DSN per one codebase.

**Question:**
Please tell me how I can use 2 dsn right now, or maybe give me some advices for solving my problem.

Sorry if i didn`t see obvious solution. Thanks for attention!

**Comment by sl0thentr0py** [comment]
hey @d4mk0 this is sort of supported with different hubs but has its own issues but you can try it out.

There is a similar discussion [over at python](https://github.com/getsentry/sentry-python/discussions/1521).

In ruby this would look like 

```ruby
# init with first DSN normally
Sentry.init do |config|
   config.dsn = "<DSN1>"
end

# setup second config
config2 = Sentry.configuration.clone
config2.dsn = "<DSN2">

hub1 = Sentry.get_current_hub
hub2 = hub1.clone
hub2.bind_client(Sentry::Client.new(config2))

# goes to first DSN
hub1.capture_message("first DSN")
# goes to second DSN
hub2.capture_message("seconf DSN")
```
