### ISSUE TITLE
Crons automatic support for gems

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2134]
- sidekiq-cron
- sidekiq-scheduler
- ~whenever~ bash based, so just use `sentry-cli`
- ~clockwork~ also unaware of job system, so we can't really patch

_Originally posted by @sl0thentr0py in https://github.com/getsentry/sentry-ruby/issues/2090#issuecomment-1737351435_

**Comment by natikgadzhi** [comment]
Cool if I work on `sidekiq-scheduler`? Using #2170 as a reference, that's pretty straightforward.

**Comment by natikgadzhi** [comment]
Looking at [Whenever]https://github.com/javan/whenever#define-your-own-job-types, it's a bit funny:

> All jobs are by default run with bash -l -c 'command...'. Among other things, this allows your cron jobs to play nice with RVM by loading the entire environment instead of cron's somewhat limited environment. Read more: http://blog.scoutapp.com/articles/2010/09/07/rvm-and-cron-in-production
> 
> You can change this by setting your own :job_template.

I think we can make our own wrapper that: 
1. Works as a rake task, and therefore loads Sentry configuration from the existing Rails app
2. Starts, loads Sentry config, reports monitor check-in for the invoked command.
3. Executes the actual command by shelling out
4. If successful, reports successful monitor check-in.

I wonder if this should be configurable, so the user could opt-out of that behavior? I have a sneaky suspicion performance of starting a rake task only to ping Sentry, and then start another wrapped rake task could be not entirely great.

**Comment by sl0thentr0py** [comment]
@natikgadzhi  hmm if it's bash based, I'd leave that out of the scope of this task.
We already have CLI support here, so then they can just [wrap their runs in `sentry-cli`](https://docs.sentry.io/product/crons/getting-started/cli/).

**Comment by sl0thentr0py** [comment]
clockwork is also fully unaware of what scheduling system is in use, so we can't do much there either, let's just ship the sidekiq stuff for now.

**Comment by natikgadzhi** [comment]
I looked into Clockwork yesterday and tried to prototype it. 

1. We can setup the error handler at least, relatively easy. Although it’s just three lines for the user to setup themselves. 
2. We could try and hook into their execute method that, in theory, wraps execution of _block_ tasks, but some tasks are allowed to be passed as _strings_ and I have no clue what the hell is going on. If it doesn’t look clear to me and you after taking a look, I doubt whatever integration we can do will be clear for users, and won’t get in their way. 

So, agreed.

**Comment by natikgadzhi** [comment]
> hmm if it's bash based, I'd leave that out of the scope of this task.
We already have CLI support here, so then they can just [wrap their runs in sentry-cli](https://docs.sentry.io/product/crons/getting-started/cli/).

If you're open to it, and if it'll be useful, I'm down to prepare a documentation PR to sentry-docs and README here that would cover how to plug crons monitoring for sidekiq-* and clockwork / whenever too.

**Comment by sl0thentr0py** [comment]
@natikgadzhi of course, feel free to PR, help is always appreciated! We can collaborate on the docs PR if we need consistency with other platform docs. Let me know if you run in to problems.

**Comment by natikgadzhi** [comment]
I'm starting to look at the docs — will mention you in a PR.

**Comment by natikgadzhi** [comment]
Both `sidekiq-cron` and `sidekiq-schedule` support is merged!

**Comment by sl0thentr0py** [comment]
alright can close this now
