### ISSUE TITLE
Extra options in ALLOWED_LIST of ActiveSupportLogger

### ISSUE THREAD

**Issue by igordepolli** [getsentry/sentry-ruby#2135]
Hi, 

The pull request #2048 add a constant called `ALLOWED_LIST` to filter ActiveSupport breadcrumbs data. I would like to know if it is possible to make the addition/removal of allowed attributes dynamic.

The reason? Well, in our company, we used to use a lot for the `type_casted_binds` attribute that the subscription in `sql.active_record` gives us. This attribute provides us with all the where clauses for the queries that were made up to the time of the raise, which helped a lot with debugging for our cases.

I understand that it may not be a universal need, so my idea to implement this would be to make this addition of extra attributes optional on initialize, like excluded exceptions, for example.

**Comment by sl0thentr0py** [comment]
yea we can make this configurable, feel free to PR if you want it quicker :)

**Comment by igordepolli** [comment]
> yea we can make this configurable, feel free to PR if you want it quicker :)

@sl0thentr0py PR opened :)
