### ISSUE TITLE
Improve slug generation for crons

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-ruby#2138]
I have a question regarding the Ruby SDK. In the [documentation](https://docs.sentry.io/platforms/ruby/crons/#job-monitoring), it states

```ruby
# slug defaults to the job class name
sentry_monitor_check_ins slug: 'custom_slug'
```
Currently it appears that the `slug` parameter is always required, since Ruby class names can contain punctuation (`::`) and will have capital letters.

###### e.g.
```ruby
SuperFancy::PrivateGroups::SpecialOrganizations::ScheduleOutreachWorker
```
[In the code](https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/cron/monitor_check_ins.rb#L6), I would suggest that they use `self.class.name.parameterize` as the default, which will downcase the class name and replace the double colons with a dash.

```ruby
[1] pry(main)> e=SuperFancy::PrivateGroups::SpecialOrganizations::ScheduleOutreachWorker.new
=> #<SuperFancy::PrivateGroups::SpecialOrganizations::ScheduleOutreachWorker:0x00007f13c7a366f0>
[2] pry(main)> e.class.name.parameterize
=> "superfancy-specialgroups-specialorganizations-scheduleoutreachworker"
[3] pry(main)> e.class.name.parameterize.size
=> 68
```

This example demonstrates the other issue that we're running into, which is one of length. Since the Dashboard UI constrains the value to 50 characters (this not mentioned in the documentation), it appears the `slug` parameter will still have to be used.

Are these assumptions correct?

_Originally posted by @nimylian in https://github.com/getsentry/sentry/discussions/42283#discussioncomment-7274839_

**Comment by swanson** [comment]
One concern I have is that it appears slugs can be duplicated across environments -- could/should the gem prefix the Rails environment to the slug?

**Comment by natikgadzhi** [comment]
> This example demonstrates the other issue that we're running into, which is one of length. Since the Dashboard UI constrains the value to 50 characters (this not mentioned in the documentation), it appears the slug parameter will still have to be used.

Would it be better to try and omit pieces of the default slug if it runs out of 50 characters, or would it be more beneficial to omit the middle part of the longer slugs in the Dashboard UI? I would assume Dashboard will have to deal with many things that are too long to display, eventually?

**Comment by sl0thentr0py** [comment]
thanks for the feedback everyone, I'll think about a good way to do this when I have some time to fix this. 
Will keep all the above in mind!

**Comment by sl0thentr0py** [comment]
ok so I will parameterize and truncate from the beginning, I think that's more useful since the job name stays at the end

**Comment by sl0thentr0py** [comment]
@swanson the environment is already sent as part of the check-in in the event payload, so they will already be categorized correctly. 
![image](https://github.com/getsentry/sentry-ruby/assets/6536764/931e2142-4eec-42c6-a3ad-5f2a2b49baf3)
