### ISSUE TITLE
Discarded invalid value in Ruby events

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-ruby#2145]
### Issue Description

Sentry started marked invalid values in the UI:

From what I understand from here: https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/breadcrumb/sentry_logger.rb#L11 breadcrumbs from logger.warn are set with level "warn", which is not accepted by the server.

As described in the breadcrumb interface specification the level should be "warning" not "warn": https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/

This similar to this workaround used for event level: https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/event.rb#L124

### Reproduction Steps

Trigger events that contain warn level breadcrumbs. 

### Expected Behavior

The level is set to a value that Sentry's server accepts. 

### Actual Behavior

<img width="476" alt="Screenshot 2023-10-18 at 08 55 52" src="https://github.com/getsentry/sentry-ruby/assets/64906376/509d84ce-cd91-4ab2-97bb-01ae9e45b64c">

### Ruby Version

3.1.2

### SDK Version

5.12.0

**Comment by sl0thentr0py** [comment]
thx for the report @rodolfoBee !
