### ISSUE TITLE
Logging exception even when sending is disabled

### ISSUE THREAD

**Issue by chulkilee** [getsentry/sentry-ruby#2147]
Hi - I'd like to log all captured events from Sentry when Sentry is configured not to send events - especially to find which `Sentry.capture_exception` actually happened in development or test.

I was thinking of using `before_send` callback but it seems like Sentry ignores the event earlier than calling that method ([link](https://github.com/getsentry/sentry-ruby/blob/5.12.0/sentry-ruby/lib/sentry/client.rb#L43))

One option is to wrap Sentry.capture_exception with my custom wrapper to log it - but I'm wondering whether it's possible to do that by extending sentry-ruby or making reasonable changes in it.

**Comment by sl0thentr0py** [comment]
yea tbh those `sending_allowed?` checks are a bit out of place but I guess they are optimized for not creating unnecessary objects in memory. @st0012 do you know why they are before creating the events in client and not before the exact sending in transport?

**Comment by st0012** [comment]
I'd say it's mostly inherited from `sentry-raven`'s implementation. But I also think returning early from the sending workflow is best for most users. 

For example, users may have rather complicated `before_send` logic, which when being run repeatedly in test environment could add observable overhead and cause tests to take longer. (If the user uses the SDK's test helper, they should be aware of the overhead though). 
And if the user uses `async`, that'd be even worse as the job processing logic would be called too.

To the original question, I think you should simply monkey-patch the `Sentry.capture_exception` method for it, with a condition like `unless Rails.env.production?`. Using `before_send` is risky as it will be executed in production too.
