### ISSUE TITLE
Supporting older Ruby versions (move link to docs)

### ISSUE THREAD

**Issue by lleirborras** [getsentry/sentry-ruby#2152]
**Supporting old ruby versions for**

**People migrating from other platforms such as Rollbar that supported older Ruby versions would make transitions easy**

**IFAD has implemented a backwards compatible version based on polifills here https://github.com/ifad/sentry-legacy-ruby**

**Sidekiq gem was also actively used and we have crafted a version compatible with legacy Ruby versons here https://github.com/ifad/sentry-legacy-sidekiq**

**Comment by sl0thentr0py** [comment]
wow great work @lleirborras !
I'll see where the best place in our docs to reference to the fork is, not sure this github issue is the best place.
