### ISSUE TITLE
Sentry rejects breadcrumb data when a field contains a malformed unicode string

### ISSUE THREAD

**Issue by timcowlishaw** [getsentry/sentry-ruby#2155]
### Issue Description

Hey there folks,

I'm trying to track down a bug in a system i'm working on using Sentry, and i think i've found a bug in the breadcrumbs SDK.

For some context, we ([SmartCitizen](https://smartcitizen.me/)) make small IoT-type devices which monitor environmental data for our users. We have a platform that receives, aggregates, stores and presents the data from these devices, which number in the thousands.

The devices send us messages (a custom format over MQTT, which is later parsed into JSON), and unsurprisingly occasionally devices misbehave or the messages get mangled in transit, raising errors that appear in Sentry. I'm trying to debug one of these at the moment, where a message arrives which appears to be invalid unicode:

<img width="518" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/4279/cff7fcfe-05dc-4916-af8d-d78fd9efda84">

I've been using Breadcrumbs to do this, logging the device and message as it arrives from mqtt, in order to identify what devices are causing the issue, and what the specific problem with the message is.

This is where something weird happens.

I log the message using the Breadcrumbs API (with an object in the `data` field, as specified):

```ruby
class MqttMessagesHandler
  def self.handle_topic(topic, message)
    crumb = Sentry::Breadcrumb.new(
      category: "MqttMessagesHandler.handle_topic",
      message: "Handling topic #{topic}",
      data: { topic: topic, message: message.scrub }
    )
    Sentry.add_breadcrumb(crumb)
    # snip
  end
  # snip
end

```

... but when the breadcrumb arrives in sentry, its data is invalid:

<img width="691" alt="Screenshot 2023-10-28 at 16 42 23" src="https://github.com/getsentry/sentry-ruby/assets/4279/89390ed0-d48a-48dd-bf67-4cbea73ceba5">
<img width="691" alt="Screenshot 2023-10-28 at 16 42 30" src="https://github.com/getsentry/sentry-ruby/assets/4279/267ce303-1a24-4b42-af16-5ea933d0c03c">

The first weird thing is that `data` itself is an object (or it was when i created the crumb)! The extra weird thing is this happens regardless of if i `scrub` the message (sanitizing invalid unicode) before creating the breadcrumb or not. I can't see anything else i could be doing incorrectly in creating and sending the breadcrumb, so i'm assuming that something in the `message` (probably the same thing that's causing the underlying error i'm investigating) is also causing sentry to reject the breadcrumb data, but it's tricky to diagnose both the underlying error and the problem with Sentry without being able to see the message in some form.

Any idea how to fix, or workaround this? Thanks!

Tim

### Reproduction Steps

Send a breadcrumb with a data hash in which one of the values is a string that has some malformed  or invalid unicode characters

### Expected Behavior

The breadcrumb should display in the sentry interface correctly

### Actual Behavior

The sentry interface shows that the message has an invalid data hash

### Ruby Version

3.0.6

### SDK Version

5.9.0

### Integration and Its Version

Ruby (with Rails and Sidekiq elsewhere in the app)

### Sentry Config

```ruby
Sentry.init do |config|
  config.dsn = ENV['RAVEN_DSN_URL']
  config.breadcrumbs_logger = [:sentry_logger, :active_support_logger, :http_logger]
end
```

**Comment by sl0thentr0py** [comment]
@timcowlishaw we expect the `data` to be JSON serializable.
https://github.com/getsentry/sentry-ruby/blob/3f46bef16472dea06974ee2c96284192c587ca2b/sentry-ruby/lib/sentry/breadcrumb.rb#L63
Question: if your your data has some weird binary in there that is not encodable, what would you expect to see on the Sentry interface that helps you in any way?

**Comment by timcowlishaw** [comment]
ha yep, fair point - i guess in some respect I'm just pushing the same bug that I'm trying to deal with onto you.

I guess in response to your question, I'd ideally be able to see one of two things - either the complete data hash with something like `U+FFFD` (�) replacing the unparseable parts of the JSON, or, at a slightly coarser level of granularity, at least be able to see the data key/values which *were* parseable, for instance:

```javascript
{ 
  "topic_id": "/foo/bar/baz",
  "message": <INVALID>
}
```

...however, I totally get why this is somewhere between tricky and impossible, and of fairly marginal benefit outside the context of dealing with this specific bug.

However, your response has helped no end - now I understand what Sentry's doing with the message, I'm pretty sure my attempt to sanitise the incoming message before passing it on to Sentry isn't actually working. I'll investigate that further. Thank you!

**Comment by timcowlishaw** [comment]
Aha, that was the clue i needed - it turns out `String#scrub` in ruby doesn't scrub strings quite as effectively as i thought. I've got something usable now. Thanks a lot for your help!

**Comment by sl0thentr0py** [comment]
glad to help!

>  at a slightly coarser level of granularity

I do plan to cleanup the breadcrumbs logic a bit at some point, but I haven't really thought through what will replace the current JSON parse/unparse. Will keep this in mind!
