### ISSUE TITLE
Deprecation warning in sentry-sidekiq: Sidekiq exception handlers now take three arguments

### ISSUE THREAD

**Issue by rnestler** [getsentry/sentry-ruby#2157]
### Issue Description

sentry-sidekiq triggers the following deprecation warning from sidekiq: ` Sidekiq exception handlers now take three arguments`.

Context:
 * Changelog from sidekiq: https://github.com/sidekiq/sidekiq/blob/main/Changes.md#715
 * https://github.com/appsignal/appsignal-ruby/commit/c8698dca465d84fdac33d88debc6fbb004458bf1 seems to fix this bug for appsignal.

### Reproduction Steps

Use sidekiq 7.1.6

### Expected Behavior

Don't trigger deprecation warning.

### Actual Behavior

Triggers deprecation warning.

### Ruby Version

3.2.2

### SDK Version

5.12.0

### Integration and Its Version

Sidekiq 7.1.6

**Comment by natikgadzhi** [comment]
@sl0thentr0py, I didn't mean to be rude or arrogant — was just looking for issues to play around with, and pushed up this: https://github.com/getsentry/sentry-ruby/pull/2160

But, totally fair and no hard feelings if you'd rather do this on your own and/or differently! Hope the PR helps and saves you a few minutes 😊
