### ISSUE TITLE
Question about the override to `Rake::Task#execute`

### ISSUE THREAD

**Issue by hosamaly** [getsentry/sentry-ruby#2196]
I'm a bit confused about this piece of code:

https://github.com/getsentry/sentry-ruby/blob/f15f58e4a6138f1b826379325678756641ea29bc/sentry-ruby/lib/sentry/rake.rb#L21-L28

The override doesn't seem to do much other than call `Sentry.get_current_hub`.

If this is the case, it would be slightly clearer, in my humble opinion, to define it as:

```ruby
def execute(args=nil) 
  Sentry.get_current_hub if Sentry.initialized?
  super
end
```

Did I understand the purpose of the method correctly?

**Comment by sl0thentr0py** [comment]
I think this is leftover code from #1617, I don't even think we need the `Task` patch anymore. @st0012 can you verify?

**Comment by st0012** [comment]
@sl0thentr0py Yes you're right. I've opened #2214 to remove it.
@hosamaly Thanks for raising this!
