### ISSUE TITLE
Not getting alerts for errors in my views

### ISSUE THREAD

**Issue by jimmypoulsen** [getsentry/sentry-ruby#2197]
### Issue Description

The envelope is not being sent if an error occurs in my view. It works just fine when doing `Sentry.capture_exception` in a Rails console which suggests that the integration is working.

We have multiple projects and we use the same initializer in all of them but not the same versions of sentry-ruby, sentry-rails, and sentry-sidekiq.

In the project I'm referring to here we're running version 5.10.0 of all the gems. In the other project, we're running version 5.7.0. In the other project, it's working just fine so I tried downgrading to version 5.7.0 and all of a sudden it's working. I then upgraded to version 5.15.0 (latest) and that doesn't work either. My conclusion then is that something changed after version 5.7.0. Beware, I didn't change my Sentry config when downgrading from 5.10.0 to 5.7.0 or when upgrading from 5.10.0 to 5.15.0.

### Reproduction Steps

1. Create a new route
2. Create a new controller action
3. Create a new view and render it in the controller action
4. Inside the view, put `<%= @foo[:bar] # an instance variable that doesn't exist %>`.

### Expected Behavior

It was expected that an `ActionView::Template::Error` error was raised and reported in Sentry.

### Actual Behavior

I can tell by looking at my application logs that the error is raised just fine. But for version 5.10.0 and 5.15.0 the classic `INFO -- sentry: [Transport] Sending envelope with items [event]` is not logged.

### Ruby Version

3.2.1

### SDK Version

5.10.0, 5.15.0

### Integration and Its Version

Rails/Sidekiq

### Sentry Config

```
Sentry.init do |config|
  config.dsn = ENV.fetch('SENTRY_DSN')
  config.enabled_environments = %w[production]
  config.excluded_exceptions += []
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # Set tracesSampleRate to 1.0 to capture 100%
  # of transactions for performance monitoring.
  # We recommend adjusting this value in production
  config.traces_sample_rate = 1.0
  # or
  config.traces_sampler = lambda do |context|
    true
  end
end if Rails.env.production? && ENV['SENTRY_DSN']
```

**Comment by jimmypoulsen** [comment]
@adipasquale I see that you did a pull request for upgrading to 5.15. That **didn't** solve our problem. We're now using 5.7 and that seems to work.

**Comment by sl0thentr0py** [comment]
@jimmypoulsen can i also have your rails version?

**Comment by jimmypoulsen** [comment]
@sl0thentr0py Sorry. I should have included that! We're on Rails 7.1.0.alpha.

**Comment by jimmypoulsen** [comment]
@sl0thentr0py Hmm .. I see that you're on Ruby 3.2.2. We're on Ruby 3.2.1. Could that be the cause? Honestly, I don't know how to come up with a better case. We're hosting our system on Heroku. Could that have something to do with it?

**Comment by sl0thentr0py** [comment]
no I don't think that a patch ruby version difference matters here, nor heroku as far as I can tell.

**Comment by sl0thentr0py** [comment]
maybe check that you don't have some middleware that is swallowing that error and not re-raising it?

**Comment by jimmypoulsen** [comment]
I checked and it doesn't seem like it .. 🤔

**Comment by sl0thentr0py** [comment]
@jimmypoulsen you need to give me a repro case if you want me to help

**Comment by jimmypoulsen** [comment]
@sl0thentr0py I can give you another repro case but it will be similar to the one I did on the issue. For now, we'll stick to using version 5.7.0.

**Comment by ishields** [comment]
@jimmypoulsen i know this is quite an old ticket but i am experiencing a similar issue where errors in controllers, services and sidekiq go to sentry, but errors fired in the haml view don't and are dropped somehow. It only happen in production and the error works fine in development. Did you ever figure out the cause?

**Comment by ishields** [comment]
Fixed! We had the same problem @victormours with Bootsnap. An old version of bootsnap was causing the errors to be dropped. "Fix for NameErrors not being reported in Sentry". For us the errors dropped were only in our views I believe. Updating Bootsnap to a more recent version and clearing cached fixed it. https://github.com/betagouv/rdv-service-public/pull/5578

**Comment by jimmypoulsen** [comment]
@ishields We never actually figured out why it happened, but the issue disappeared after a while. At some point we updated our Rails version, and I wonder if that also included a Bootsnap update — that might very well have been the fix.

Anyway, great to hear you figured it out! 😄
