### ISSUE TITLE
Add rake command for adding rails initializer

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2218]
we want to make it easier for rails users to setup sentry, see
https://fly.io/docs/reference/sentry/#ruby-on-rails
and 
https://github.com/getsentry/sentry-wizard

* add new rake command like `bundle exec sentry:setup`
* auto create default initializer
* some questions TBD (see sentry-wizard and how they do it)
   * DSN
   * enable performance
   * enable profiling

**Comment by st0012** [comment]
If this only targets Rails apps, maybe we can use [Rails' generator](https://guides.rubyonrails.org/generators.html#creating-your-first-generator) instead?

It also supports [cli options](https://guides.rubyonrails.org/generators.html#generator-command-line-options). So once this is completed, we can just generate a one line command on the web UI like:

```shell
bundle exec bin/rails generate sentry --dsn <user DSN> --enable-profiling true
```

**Comment by sl0thentr0py** [comment]
yep also a possibility!

**Comment by smeubank** [comment]
> some questions TBD (see sentry-wizard and how they do it)
>  - DSN
>  - enable performance
>  - enable profiling

We do not enable profiling OOTB with wizards, and there are not prompts as far as I know, to ask the user if they want the wizard to add it. 

Ruby doesn't have to worry about uploading source context, it automatically sends sessions and attempts to set unique release values. Those would be the typical prompts we'd try to solve for, we should validate the release detection works as we expect.

For the DSN there is a login flow, which there are some cases we manage via the wizard well, and some we do not manage well. see -> https://github.com/getsentry/sentry-wizard/issues/357 but this is more related to the org auth token

[Setup Wizards](https://develop.sentry.dev/sdk/setup-wizards/): dev spec


fwiw I don't think detailed feature selection is first prio, but they are considering it for the other wizards as well: https://github.com/getsentry/sentry-wizard/issues/558

**Comment by st0012** [comment]
Personally, I wouldn't want to install a npm package just to have it help me set up a SDK, unless it provides significantly better experience. In the Rails community, installing a gem and run its associated Rails generator command for configuration is a pretty standard practice. For example, [bugsnag](https://docs.bugsnag.com/platforms/ruby/rails/#basic-configuration) and [airbrake](https://github.com/airbrake/airbrake?tab=readme-ov-file#rails) have Rails generators too. But I don't think Rails generators can provide the same interactive experience like the wizard does.

FWIW, appsignal provides a [library-agnostic executable](https://docs.appsignal.com/ruby/installation/index.html) to provide a rich [installation](https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/cli/install.rb) or even [diagnose](https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/cli/diagnose.rb) experience. This may be closer to what we want to achieve with wizard? That said, IMO this is not something the Ruby SDK team should prioritize the resource for.


> For the DSN there is a login flow

Is there any doc or example to show this is achieved?

**Comment by smeubank** [comment]
> Personally, I wouldn't want to install a npm package just to have it help me set up a SDK

fair, we also made it available via `brew` for mobile platforms, for similar reasons. I don;t know if something similar is possible for ruby gem's, to make it available in way that would make sense, and even ideally delete if after the wizard is complete.

> FWIW, appsignal provides a [library-agnostic executable](https://docs.appsignal.com/ruby/installation/index.html) to provide a rich [installation](https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/cli/install.rb) or even [diagnose](https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/cli/diagnose.rb) experience. This may be closer to what we want to achieve with wizard? That said, IMO this is not something the Ruby SDK team should prioritize the resource for.

without any insight on how much effort it would be, I don't think it is a high prio either, we can create a different ticket to track it for possible future work

> > For the DSN there is a login flow
> 
> Is there any doc or example to show this is achieved?

@Lms24 do you have more insights to share about the [project selection](https://develop.sentry.dev/sdk/setup-wizards/#2-project-selection) to fetch the correct DSN?

**Comment by sl0thentr0py** [comment]
added in https://github.com/getsentry/sentry-ruby/releases/tag/5.18.0
