### ISSUE TITLE
Transaction sending failed: Net::OpenTimeout

### ISSUE THREAD

**Issue by 1c7** [getsentry/sentry-ruby#2220]
<img width="1291" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/1804755/a4f542e4-72c5-4ad0-9bbe-8dd62db6fb2c">

<img width="1440" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/1804755/398ded88-cc7e-4dc6-883d-833676ace6c6">

## Environment
1.  Ruby on Rails 7.1.2
2. Ruby 3.2.2

## File
config/initializers/sentry.rb
```ruby
env_sentry_dsn = ENV['SENTRY_DSN']
Sentry.init do |config|
  config.dsn = env_sentry_dsn
  config.environment = ENV['APP_ENVIRONMENT'] || ENV['RAILS_ENV']
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]
  config.traces_sample_rate = ENV['SENTRY_TRACES_SAMPLE_RATE'] || 1.0
  config.excluded_exceptions += %i[AliyunQuerySendDetailWorker::RetrySidekiqWorkerNotError Mime::Type::InvalidMimeType]
end
```

## Expect
Sentry work on my local environment too.

## What went wrong
not working, no error is being sent to Sentry

## Suspect
Sentry being blocked by China's firewall (just like Youtube/Twitter/Instagram/etc)

## Question
How can I debug this and find out why error is not being send to Sentry?

**Comment by sl0thentr0py** [comment]
@1c7 this is some low level network problem (firewall as you already hinted). You can try this
https://gist.github.com/brainlid/2721486
so that `Net::HTTP` outputs more debug info.

**Comment by 1c7** [comment]
## I can confirm it's network issue,
Thanks for providing help on how to output debug info.

## Use with proxy
I have a proxy running at 127.0.0.1:1087.
and then I set these 2 environment variable (I am using macOS Sonoma 14.2.1)
```
export http_proxy=http://127.0.0.1:1087;
export https_proxy=http://127.0.0.1:1087;
```
and then
```
rails console
```

```
Sentry.capture_message("aaa", level: :fatal)
```


![0](https://github.com/getsentry/sentry-ruby/assets/1804755/e3b0f947-d57c-43e7-8507-b4cd0a1540ad)

![1](https://github.com/getsentry/sentry-ruby/assets/1804755/2a1dd613-24b8-4d31-bb9e-5940e91f8108)

## When I am not using proxy
![2](https://github.com/getsentry/sentry-ruby/assets/1804755/18ff6e9f-87d0-4469-9be4-3a1cb14132c6)

![3](https://github.com/getsentry/sentry-ruby/assets/1804755/5092ca70-e0b4-450c-9780-02e154732e81)


## Thanks
