### ISSUE TITLE
Missing release on rubygems.org?

### ISSUE THREAD

**Issue by gael-ian** [getsentry/sentry-ruby#2221]
Hello,

All sentry gems for Ruby seem to have been updated to 5.16.0 but `sentry-rails` and `sentry-delayed_job` are still only available as 5.15.2 on rubygems.org. Maybe there was a bug with the release script? Can you push them manually?

Thanks.

**Comment by sl0thentr0py** [comment]
oh damn, on it

**Comment by sl0thentr0py** [comment]
sigh, github is also having an incident right now, I'll try to get it out as soon as they're back up.

**Comment by sl0thentr0py** [comment]
cause was failure to install latest `sqlite3` release 
```
sqlite3-1.7.0-x86_64-darwin requires ruby version < 3.4.dev, >= 3.0, which is incompatible with the current version, ruby 2.7.8p225
```

**Comment by sl0thentr0py** [comment]
@gael-ian 5.16.1 was released correctly for all gems, sorry for the inconvenience!
