### ISSUE TITLE
Add "Query Sources" Ruby support

### ISSUE THREAD

**Issue by gggritso** [getsentry/sentry-ruby#2242]
### Problem Statement

[Query Sources](https://docs.sentry.io/product/performance/queries/#query-sources) are supported in Python frameworks and in Laravel, but not in Ruby. Opening this issue so we can keep track of customer requests, which have come up a few times already.

### Solution Brainstorm

There's some prior art on this in our own SDKs _and_ in the OSS world, since Rails has built-in query source collection. Maybe we can hook into that, or just do something similar.

### Product Area

Performance - Queries

**Comment by swanson** [comment]
We are trying to consolidate our tooling on Sentry, but this is a big loss in moving from Scout. Happy to help with beta testing.

**Comment by sl0thentr0py** [comment]
will prio this soon

**Comment by st0012** [comment]
I'll give this a look.
