### ISSUE TITLE
Ensure prevent bug to be sent

### ISSUE THREAD

**Issue by ppascualv** [getsentry/sentry-ruby#2260]
### Issue Description

When `ensure` is used the exception halted between the `begin` and `ensure` block is not sent to Sentry

### Reproduction Steps

```
def foo
  raise "error"
ensure
  puts "Ensure"
end
```

### Expected Behavior

Send raised error to Sentry

### Actual Behavior

The error is not sent

### Ruby Version

3.1.1

### SDK Version

5.16

### Integration and Its Version

Rails, Sidekiq, same version

### Sentry Config

 config.dsn = Rails.application.credentials.sentry.dsn unless Rails.env.test?
  config.breadcrumbs_logger = [:active_support_logger, :sentry_logger, :http_logger]
  config.environment = Rails.env
  config.enabled_environments = %w[production staging].freeze
  config.send_modules = false
  config.max_breadcrumbs = 15
  config.traces_sample_rate = 0.2

**Comment by sl0thentr0py** [comment]
@ppascualv is this in some rails code or in plain ruby somewhere in a script.
If it's plain ruby, you'll need a manual `Sentry.capture_exception` call.

**Comment by ppascualv** [comment]
it's rails

**Comment by sl0thentr0py** [comment]
cannot repro, so I will need repro steps from you to investigate further.

with the following controller:
https://github.com/sl0thentr0py/sentry_sample_apps/commit/d587d41dfdcabe28ce9a9ed9974fc17ce169679a#diff-4390d009262006d4b3916229bab087f2bd24aacc3a088b52a876c56ded21ef2f

I got this issue

![image](https://github.com/getsentry/sentry-ruby/assets/6536764/0a684b3d-a744-4a70-8a57-df692ff25b43)
