### ISSUE TITLE
Custom extraction/injection of Sentry otel baggage

### ISSUE THREAD

**Issue by jscheid** [getsentry/sentry-ruby#2264]
I'd like to use `Sentry::OpenTelemetry::Propagator` to extract baggage from, and inject baggage into, carriers other than HTTP headers. I seem to have this working for extraction, but when I try to re-inject the baggage into a fresh carrier it doesn't seem to work, nothing is added to the carrier.

I've tried both with and without creating a new span inside the extracted context, please see this test case:

https://gist.github.com/jscheid/9b685ebaaa0ab088c36a66059c33694f

This is probably due to faulty assumptions on my part -- can you spot what's wrong with my code?

**Comment by jscheid** [comment]
I'm fairly sure that this is caused by `Sentry.start_transaction` returning `nil` [here](https://github.com/getsentry/sentry-ruby/blob/60cf6c407a755c89ff404c5f7bfa85dcd77ed98e/sentry-opentelemetry/lib/sentry/opentelemetry/span_processor.rb#L51). I'll try to work out why, or perhaps you can provide any clues?

**Comment by sl0thentr0py** [comment]
oh i was about to investigate, but glad you figured it out!
Can you also write briefly what the problem/fix was so that other people who land on this issue have a reference?

**Comment by jscheid** [comment]
`Sentry::OpenTelemetry::Propagator.inject` doesn't do anything (for imported contexts) unless `Sentry.configuration.tracing_enabled?` returns truthy, even if called explicitly like in my example. 😊
