### ISSUE TITLE
Bulk Distribution Metric

### ISSUE THREAD

**Issue by mu4farooqi** [getsentry/sentry-ruby#2312]
I want to capture metrics in a Sidekiq job where I'm doing batch processing. I'm doing something like following:

```
  time_now = Time.now.utc.to_f
  messages.each do |message|
    Sentry::Metrics.distribution(
      'message_dispatch_latency', time_now - message.created_at.to_f, unit: 'millisecond'
    )
  end
```

Is there a better way to do this. Because here if we have 10 messages, we'll make 10 network calls right? Do we have any option to send bulk metrics.

**Comment by sl0thentr0py** [comment]
@mu4farooqi that will not send 10 network calls, we locally collect the metrics in a thread and [flush them out every 5 seconds](https://github.com/getsentry/sentry-ruby/blob/7f8dcdd06123599a128c4ae32d2e8d5703b9ea69/sentry-ruby/lib/sentry/metrics/aggregator.rb#L6). The aggregation / batching is already handled by the SDK. :)
