### ISSUE TITLE
Sample rate override ignored when set to 0

### ISSUE THREAD

**Issue by azaslavsky** [getsentry/sentry-ruby#2321]
### Issue Description

At https://github.com/search?q=repo%3Agetsentry%2Fsentry-ruby+valid_sample_rate&type=code, setting `sample_rate` to 0 does not work.

### Reproduction Steps

This was reported to us by a downstream user of the SDK.

### Expected Behavior

One should be able to set the sample rate to 0.

### Actual Behavior

The sample rate override is ignored.

### Ruby Version

--

### SDK Version

--

**Comment by bauffman** [comment]
We're having the same issue over here. We're using ruby 3.1.5 and the latest versions of the sentry gems.

**Comment by sl0thentr0py** [comment]
@azaslavsky @bauffman what do you mean by 'does not work'?

**Comment by bauffman** [comment]
What I mean is that the system keeps sending logs to Sentry even though the sample rate is 0.0.

**Comment by sl0thentr0py** [comment]
@bauffman I need you to be more precise when you report a problem. 'Does not work' is not helpful for me to reproduce or analyze the issue.

* what is your app? a rails app?
* what is your sentry init configuration?
* are you talking about errors with `sample_rate` 0 or performance with `traces_sample_rate` 0?
* ideally give me a clear reproduction case that shows the problem so I can fix or tell you what to do
