### ISSUE TITLE
Failed to open TCP connection ingest.us.sentry.io

### ISSUE THREAD

**Issue by leoburgos** [getsentry/sentry-ruby#2343]
### Issue Description

App is failing to connect to Sentry DNS presumably by using the wrong port (433) and throws a `Sentry::ExternalError` exception, randomly and on very few specific occasions. It works correctly the other 99% of the times

### Reproduction Steps

Use custom DNS from a Heroku add-on

I can't say if this comes from the few `Sentry.capture_message` custom calls that we have or from the default exception raising logging. 

### Expected Behavior

Connection should not be trying to connect to port 433 on any given time

### Actual Behavior

Out of the hundreds of logs we've gotten in the past, 4 have seen this error

Error coming from `gems/sentry-ruby-5.18.1/lib/sentry/transport/http_transport.rb:69:in `rescue in send_data'`:
`Sentry::ExternalError: Failed to open TCP connection to XXXXXXXX.ingest.us.sentry.io:443 (getaddrinfo: Temporary failure in name resolution)`

### Ruby Version

3.3.1

### SDK Version

5.18.1

### Sentry Config

This is the initializer `sentry.rb`

`Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]

  # get breadcrumbs from logs
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # enable tracing
  # we recommend adjusting this value in production
  config.traces_sample_rate = 0.5

  # enable profiling
  # this is relative to traces_sample_rate
  config.profiles_sample_rate = 0.5

  config.include_local_variables = true
  config.send_client_reports = true
end`

ENV['SENTRY_DNS'] = https://xxxxxxxx:yyyyyyyyy@zzzzzzzz.ingest.us.sentry.io/450.......

**Comment by sl0thentr0py** [comment]
@leoburgos this seems like a DNS thing between your network and our servers, I'm not sure how the SDK could do anything differently for preventing network issues? Do you have a suggested fix?

**Comment by jhirsh** [comment]
Ran into issues where local machine was failing to post data to ingest.sentry.io. Ruby's built in OpenSSL library does not include the ISRG root, which trusts Sentry.

So you can vendor isrg-root-x1.pem to establish certificate trust:
`curl -o certs/isrg-root-x1.pem https://letsencrypt.org/certs/isrgrootx1.pem`

Then in sentry.rb:
```
cert_store = OpenSSL::X509::Store.new
cert_store.set_default_paths
cert_store.add_file(Rails.root.join('certs/isrg-root-x1.pem').to_s)
config.transport.ssl = { cert_store: cert_store }
```
