### ISSUE TITLE
Invalid monitor payload for Cron monitors using sidekiq-scheduler

### ISSUE THREAD

**Issue by william-stacken** [getsentry/sentry-ruby#2344]
### Issue Description

I have configured sidekiq auto-discovery and tried running a scheduled job. However, it seems the default check-in payload is detected as invalid.
![Screenshot 2024-07-18 at 14 58 33](https://github.com/user-attachments/assets/973f191d-a9a2-4a4c-98a6-f971d598db5b)
I also received the error message `A check-in was sent for a monitor that does not exist. If you meant to create a new monitor via upsert, please provide a valid monitor configuration in the check-in payload.`

I checked the documentation as suggested in the error message, and the payload that was received by Sentry seems consistent with it.

### Reproduction Steps

- Configure sidekiq auto-discovery
- Run a scheduled job
- Check the Cron monitors in Sentry

### Expected Behavior

The cron monitor shows up as expected.

### Actual Behavior

Invalid check-in payload

### Ruby Version

3.2.4

### SDK Version

5.18.1

### Integration and Its Version

rails 7.0.8 and sidekiq-scheduler 3.1

### Sentry Config

```rb
Sentry.init do |config|
  # ...
  config.enabled_patches += [:sidekiq_scheduler]
end
```

**Comment by sl0thentr0py** [comment]
hey @william-stacken we sadly don't support 6 field crontab values
see the last item here: 
https://docs.sentry.io/product/crons/troubleshooting/

**Comment by william-stacken** [comment]
Thanks for the help!
