### ISSUE TITLE
Configure SDK to raise error when event exceeds size limit

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-ruby#2356]
Currently, when an event exceeds the size limit, the sdk trims the breadcrumbs of the event.  If it still exceeds the size limit, we discard the event with a log message.

The log message can be easily missed.  It would be nice to be able to configure this behavior so that the sdk can raise an error instead, otherwise users may not be aware their events are being discarded unless they happen to look at the logs.

**Comment by sl0thentr0py** [comment]
hey @Fwang36, thanks for the issue.
Our SDKs are always designed with the principle of never throwing exceptions within user code. Our SDKs are used in a wide variety of applications, some of which operate at very high scale so we will never raise an exception within the SDK ourselves. All problems internal to the SDK are logged with a level and are visible by setting the log level to `:debug`.

In the future, we will expose more fine grained statistics on `sentry.io` that will help you analyze event drops of various kinds.
Closing this, sorry!
