### ISSUE TITLE
RSpec matchers

### ISSUE THREAD

**Issue by solnic** [getsentry/sentry-ruby#2395]
We already have test_helper with some helper methods but it would be great to also add various RSpec matchers so that matching on Sentry events is easy and concise.

Rough API sketch:

```ruby
expect(sentry_events).to include_sentry_event("Ooops")
  .with_exception(RuntimeError, "Gaah!")
  .with_context("rails.error" => {some: "stuff"})
  .with_tags(%w[foo bar])
```

**Comment by johngallagher** [comment]
One request from me - please can we make the failures readable with plain old diffs that we can read and immediately understand what's wrong. Thank you!
