### ISSUE TITLE
Error on a page load in a `trace` containing a replay doesn't include the replay_id

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-ruby#2400]
### Issue Description

Currently, replay on backend error is limited, when the replay isn't yet sampled.
* https://github.com/getsentry/sentry-javascript/issues/9490

But when the replay is already recording when the request is done to the backend, we can send that `replay_id` in the `baggage` header. Allowing for any events captured by the backend SDK to include it in the DSC. This should allow 

### Reproduction Steps

Add replay to the FE with `replaysSessionSampleRate` set to `1.0`.
Cause an error on the BE when serving the request.

### Expected Behavior

Replay attached to the BE error

### Actual Behavior

no replay on the BE error.

### Ruby Version

3.3.4

### SDK Version

5.18.2

**Comment by bruno-garcia** [comment]
For reference, Python:
* https://github.com/getsentry/sentry-python/pull/2234

**Comment by sl0thentr0py** [comment]
@antonpirker fyi, this logic seems to have gone away from python during the scope refactor.
