### ISSUE TITLE
Error installing sentry-rails 5.20.0: installing symlink '.rubocop.yml' pointing to parent path

### ISSUE THREAD

**Issue by matthewrfindley** [getsentry/sentry-ruby#2419]
### Issue Description

Gem::Package::SymlinkError: installing symlink '.rubocop.yml' pointing to parent path /path-to-project/gems/ruby/3.3.0/gems/.rubocop.yml of /path-to-project/gems/ruby/3.3.0/gems/sentry-rails-5.20.0 is not allowed

It appears `sentry-rails` is symlinking to a rubocop.yml file located in the root of the project. This breaks any project that does not have a rubocop.yml

https://github.com/getsentry/sentry-ruby/pull/2377

### Reproduction Steps

gem install sentry-rails

### Expected Behavior

Installing `sentry-rails` with no `rubocop.yml` succeeds

### Actual Behavior

Raises an error on install.

Gem::Package::SymlinkError: installing symlink '.rubocop.yml' pointing to parent path /path-to-project/gems/ruby/3.3.0/gems/.rubocop.yml of /path-to-project/gems/ruby/3.3.0/gems/sentry-rails-5.20.0 is not allowed

### Ruby Version

3.3.4

### SDK Version

5.20.0

**Comment by sl0thentr0py** [comment]
uhh sorry, looking into it

**Comment by sl0thentr0py** [comment]
cc @solnic

**Comment by sl0thentr0py** [comment]
sorry everyone, please pin to `~> 5.19.0` for now, docker is having an incident as well so I need to wait for that so our CI passes and I can release. :(

**Comment by sl0thentr0py** [comment]
5.20.1 is out, can someone verify that it's ok?

**Comment by lsglick** [comment]
@sl0thentr0py this appears to be working now for us.
