### ISSUE TITLE
skip_rake_integration doesn't skip sentry messages from console

### ISSUE THREAD

**Issue by MaicolBen** [getsentry/sentry-ruby#2435]
### Issue Description

Basically this [issue](https://github.com/getsentry/sentry-ruby/issues/1378) for `capture_message` , maybe it worked back then when the rails console was a task. 

### Reproduction Steps

- Enable `skip_rake_integration`
- Send a message with `Sentry.capture_message` 

### Expected Behavior

- It doesn't show up in Sentry

### Actual Behavior

- It shows up in Sentry

### Ruby Version

3.2.3

### SDK Version

5.21

### Sentry Config

```ruby
Sentry.init do |config|
  config.traces_sample_rate = 0
  config.sidekiq.report_after_job_retries = true
  config.skip_rake_integration = true
  config.send_default_pii = true
```

**Comment by sl0thentr0py** [comment]
hey, `skip_rake_integration` only controls whether exceptions in your rake tasks are captured or not. An explicit `Sentry.capture_message` is always sent if the SDK is initialized (which is true in the rails console).

If you want to completely disable Sentry inside your console you can wrap your `Sentry.init` with a console check like this:

```ruby
unless Rails.const_defined?('Console')
  Sentry.init do |config|
    config.dsn = "<DSN>"
    # ....
  end
end
```

**Comment by MaicolBen** [comment]
Thank you!
