### ISSUE TITLE
Set db.* data for active_record DB calls

### ISSUE THREAD

**Issue by frederikspang** [getsentry/sentry-ruby#2449]
**Describe the idea**

Currently, Table and Command fields in the Queries page on Sentry is blank for ActiveRecord, because we do not fill these out. (`db.collection.name` and `db.operation`)

![Image](https://github.com/user-attachments/assets/676df9ab-7422-4393-97a9-57a26e46b7cd)

**Why do you think it's beneficial to most of the users**

Being able to filter on these, would utilize the more full product of Sentry for Ruby/Rails SDK's.

**Possible implementation**

OpenTelemetry does (within `pg` instrumentation) this by "mildly" parsing the query text - Regex for extracting etc.
We could do the same,
https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L18

**See also:** 
- https://develop.sentry.dev/sdk/telemetry/traces/span-data-conventions/

**Comment by sl0thentr0py** [comment]
I think we could also do this server side, will talk to the ingest peeps

**Comment by sl0thentr0py** [comment]
@frederikspang can you link a transaction in Sentry or the paste the event json payload? It seems we should already be extracting this on the server, so I need to see what your queries look like and see if the parsing fails on some case.

**Comment by frederikspang** [comment]
@sl0thentr0py We're on-prem Sentry (For various reasons).
JSON here, hopefully somewhat redacted/anonymized.. :)

If something is wrong in it, let me know, I can email to you.

**Comment by sl0thentr0py** [comment]
ahh okay, we usually do bundle relay with self-hosted so if you're a new-ish version, your server side extraction should also be working. 
We just like to avoid logic in SDKs that could be done more generally on the server so that we maintain it in one place rather in every language.

The JSON looks fine, that should be transformed correctly and show up in product if you have the right versions.

**Comment by sl0thentr0py** [comment]
aha the tables are indeed extracted, see the `domain` key

![Image](https://github.com/user-attachments/assets/7d738093-6974-4219-9096-bb1214bf9c44)

so something else in the product is not picking it up later!

**Comment by frederikspang** [comment]
> ahh okay, we usually do bundle relay with self-hosted so if you're on a new-ish version, your server side extraction should also be working. 
> We just like to avoid logic in SDKs that could be done more generally on the server so that we maintain it in one place rather in every language.
> 
> The JSON looks fine, that should be transformed correctly and show up in product if you have the right versions.

@sl0thentr0py That makes sense!

Where do we report this up the chain? Can you confirm it on your test setup, and we can move this issue there?

**Comment by sl0thentr0py** [comment]
I opened 
https://github.com/getsentry/sentry/issues/79990

closing this one.
