### ISSUE TITLE
How to print error in development instead of sending it to sentry?

### ISSUE THREAD

**Issue by Paxa** [getsentry/sentry-ruby#2454]
is it possible to print errors in development instead sending?

With empty `dsn` it just skip sending

**Comment by sl0thentr0py** [comment]
hey @Paxa you can simply not initialize the SDK if you don't want it to interfere in development
```ruby
unless Rails.env.development?
   Sentry.init do |config|
     ...
    end
end
```

**Comment by Paxa** [comment]
Is it possible for `Sentry.capture_exception(e)` to print errors?

**Comment by sl0thentr0py** [comment]
no, but you can use spotlight (our development sentry tool) 
https://spotlightjs.com/setup/other/#bonus-leverage-sentry-sdks (click on the ruby tab)
