### ISSUE TITLE
Using `ActiveSupport::ErrorReporter` with `capture_message`

### ISSUE THREAD

**Issue by viralpraxis** [getsentry/sentry-ruby#2460]
I'm sorry if it already has been discussed, I couldn't find any info on this topic. `sentry-rails` has built-in integration with ActiveSupport's `ErrorReporter` which allows to report exceptions with service-agnostic `Rails.error` API. Reporting exceptions works fine, but surprisingly it does not work (AFAIK) with sentry's message capturing feature.

It seems like there's no restriction on reported object's type from AS' side; `Rails.error.report("foobar")` propagates message to `capture_exception` where it fails with "ArgumentError: expect the argument to be a Exception, got String" exception.

I'm curious if it's possible to extend sentry's subscriber to propagate strings to `capture_message`? Is there a reason it's not implemented yet?

**Comment by sl0thentr0py** [comment]
agreed we should add this and fix the string problem
