### ISSUE TITLE
NoMethodError in session_flusher.rb

### ISSUE THREAD

**Issue by avdi** [getsentry/sentry-ruby#2468]
### Issue Description

This exception from sentry-ruby popped up on Sentry:

![Image](https://github.com/user-attachments/assets/2c4c13c1-1ce9-4832-b46a-039ffa986ce5)

### Reproduction Steps

We've only seen it happen once, so not sure how to reproduce.

### Expected Behavior

Not an exception

### Actual Behavior

An exception

### Ruby Version

3.2.4

### SDK Version

5.21.0

### Integration and Its Version

Rails

**Comment by sl0thentr0py** [comment]
I'm at a loss how this could happen, this is the relevant code

https://github.com/getsentry/sentry-ruby/blob/ceba0da67755c6168729027b84cb2eaac9179902/sentry-ruby/lib/sentry/session_flusher.rb#L31-L33
