### ISSUE TITLE
Fix Source Code Extraction to Stack Traces (regression via rails)

### ISSUE THREAD

**Issue by chodges15** [getsentry/sentry-ruby#2472]
**Describe the idea**
Currently, the Ruby Sentry SDK provides stack traces that include the file name, line number, and method name where an error occurred. However, it does not include the actual lines of source code. This feature is crucial for debugging, especially when dealing with third-party code, as it provides immediate context around the error without requiring developers to manually locate and open the files.

The feature request is to add functionality to the Ruby Sentry SDK to extract and include source code snippets in stack traces. This can be achieved by implementing a mechanism similar to the CodeExtractor class in the Bugsnag SDK, which reads the relevant files and attaches the surrounding lines of code to the stack trace.

**Why do you think it's beneficial to most of the users**
1. Improved Debugging: Including source code snippets in stack traces allows developers to quickly understand the context of an error, making it easier to diagnose and fix issues.

2. Third-Party Code: When errors occur in third-party libraries, developers may not be familiar with the code. Providing the surrounding lines of code helps them understand what might be going wrong without needing to dive into the third-party codebase.

3. Efficiency: This feature saves time by reducing the need to manually locate and open files to see the relevant lines of code. It streamlines the debugging process and helps developers focus on solving the problem.

**Comment by ndmanvar** [comment]
minor clarification:
I believe we show context_lines/source_code for in-app frames; it seems like we aren't doing so for vendor-libraries (i.e, non-in-app-frames)
![Image](https://github.com/user-attachments/assets/d45b29b2-656d-4a7e-8845-5cba215ade0a)

Also, we may shown context_lines for all frames at some point... 
See following [event](https://demo.sentry.io/issues/4421674299/?project=4504456042774528&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=1#threads) from v5.7.0 which shows that context-lines/source_code for all frames

**Comment by sl0thentr0py** [comment]
we already support this since forever
https://github.com/getsentry/sentry-ruby/blob/a9b3687d3ce5d00d5586ef3fe76ae8233d8405f1/sentry-ruby/lib/sentry/interfaces/stacktrace.rb#L65-L66

but it is true that some vendor frames are missing context lines in the final product, I will investigate why this is happening.

**Comment by sl0thentr0py** [comment]
alright, not technically a regression on our end but at some point rails added this default backtrace gem path cleaner
https://github.com/rails/rails/blob/a8709e6ea26eca73a652af4fdd0a9f7db5352af4/activesupport/lib/active_support/backtrace_cleaner.rb#L118-L125

that causes our source code reading to fail since instead of paths like
```
/Users/neel/.asdf/installs/ruby/3.2.6/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/abstract_controller/base.rb
```
we get paths like
```
activesupport (7.1.2) lib/active_support/callbacks.rb
```

I will think of the best way to fix this since technically this affects all grouping now if I suddenly remove that gem filter..

**Comment by sl0thentr0py** [comment]
in the meantime, if they want to fix this, they can turn of the `backtrace_cleaner` with

```ruby
Sentry.init do |config|
  # ...
  config.backtrace_cleanup_callback = ->(x) { x }
end
```

**Comment by chodges15** [comment]
Ah, this all makes sense, we'd figured this functionality was tablestakes for a Sentry SDK, glad you already support it and thanks for the clarification on the backtrace path cleaner regression. We'll give this a shot and report back.

**Comment by sl0thentr0py** [comment]
fix is up at https://github.com/getsentry/sentry-ruby/pull/2474, will probably take a week or so for review/release.
