### ISSUE TITLE
Rspec expectations looking for an error type receive a NoMethodError instead during capture_exception since Sentry-Ruby 5.4+

### ISSUE THREAD

**Issue by ManickYoj** [getsentry/sentry-ruby#2492]
### Issue Description

When trying to upgrade our Sentry-Ruby version from 4.8 to the latest (5.22) to get access to profiling, I stumbled over an issue where updating from 5.3.2 to 5.4.0 broke a number of our RSpec tests that looked for a specific `raise_error` type. Instead they would receive a NoMethodError from Sentry's capture_exception method.

Eg this expectation:
```
expect { post endpoint, params: params }.to raise_error(ActionController::ParameterMissing)
```

Would fail before ever invoking the controller with:
```
Failure/Error: expect { post endpoint, params: params }.to raise_error(ActionController::ParameterMissing)
     
expected ActionController::ParameterMissing, got #<NoMethodError: undefined method `event_id' for true:TrueClass> with backtrace:
```

I tracked the bug to this PR https://github.com/getsentry/sentry-ruby/pull/1849 which started looking for an event_id on anything that passed through capture_exception, even if it was not an object that supported an event ID.

I fixed it by forking the repo and adding a check to see if the `event` variable `respond_to?(:event_id)`. https://github.com/getsentry/sentry-ruby/compare/master...Koala-Health:sentry-ruby:master

I don't know that this is a good way to do it; I just needed to get it working and - since we're not using that event_id attribute added by https://github.com/getsentry/sentry-ruby/pull/1849, this did it.

To be honest, I'm slightly shocked this hasn't been reported but I couldn't find anything similar on StackOverflow or the Issues yet. I don't have a lot of extra time to build a proper repro case (startup life 😓) so I'm hoping this report suffices as the bug is simple enough in concept 

### Reproduction Steps

See above - I'm afraid I wasn't that scientific in constructing a test exactly for this so I don't know exactly what triggers it.

### Expected Behavior

Capture exception should not raise its own NoMethodError when passed an object that doesn't respond to `event_id`

### Actual Behavior

Capture exception raises a NoMethodError when passed an object that doesn't respond to `event_id`

### Ruby Version

3.0.0

### SDK Version

5.4-5.22

### Integration and Its Version

Rails

### Sentry Config
```
Sentry.init do |config|
  config.dsn = "https://eb4e791f2e424db790b2de4e4a8122cd@o741292.ingest.sentry.io/5951223"
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  config.enabled_environments = %w[production staging]

  # Error sampling rate
  config.sample_rate = 1.0

  # Set tracesSampleRate to 1.0 to capture 100%
  # of transactions for performance monitoring.
  # We recommend adjusting this value in production
  config.traces_sample_rate = 0.2
  # or
  # config.traces_sampler = lambda do |context|
  #   true
  # end
end
```

**Comment by sl0thentr0py** [comment]
well `capture_exception` always returns either an `ErrorEvent` or `nil` and that's the contract so the assumptions on our side for `event_id` on `ErrorEvent` are correct. What are you passing to `capture_exception`?

**Comment by st0012** [comment]
As @sl0thentr0py said, `capture_exception` should return either an event object or `nil`, at least that's what we expect throughout the entire SDK's implementation. I also tested that making `before_send` callback return just `true` doesn't trigger the same exception. (I do notice other issues tho, which I will address in another PR)

So without any further information, my best guess is that somewhere in your tests stubs `capture_exception` and returns `true`. Maybe you can do a quick codebase search?

**Comment by ManickYoj** [comment]
Alas, you are correct. I found the culprit as a test stub that was returning true from capture exception. Sorry for the false lead. 😢 

Closing, with some shame 😆
