### ISSUE TITLE
Rails integration should respect config.filter_parameters

### ISSUE THREAD

**Issue by jfirebaugh** [getsentry/sentry-ruby#39]
`filter_parameters` is the Rails interface to avoid logging sensitive parameters. raven-ruby's Rails integration should integrate it with the data sanitizer.

**Comment by cooperka** [comment]
Update in 2020: the new `sentry-rails` v4 no longer supports `config.sanitize_fields`. After some headaches looking for upgrade documentation, it turns out Sentry handles much filtering automatically so you can probably remove the setting entirely and be on your way.
