### ISSUE TITLE
Support Threads interface

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#551]
see https://docs.sentry.io/hosted/clientdev/interfaces/

---

Update: the new document link is https://develop.sentry.dev/sdk/event-payloads/threads/

**Comment by wk8** [comment]
Would love that indeed :)

@nateberkopec : any ETA on this? otherwise, would you consider a PR adding it?

**Comment by pehcha** [comment]
Hey, guys! 
So, are you planning to implement the threads interface any soon?
