### ISSUE TITLE
Is there any way to configure what paths are considered "app only"?

### ISSUE THREAD

**Issue by wyattisimo** [getsentry/sentry-ruby#614]
I have a Rails app with a couple of engines. When I'm looking at stack traces in Sentry, it excludes paths in the engines when displaying "app only" lines.

Is this something I can configure using Raven? Or is that purely a Sentry thing?

**Comment by nateberkopec** [comment]
Yo!

Can you give an example of an engine path? Is this something that lives somewhere in your Rails application's directories or in a separate gem, for example?

It sounds like what you might want is the ability to set `config.project_root` to an array.

**Comment by wyattisimo** [comment]
Yeah, these engines just live directly under the Rails root.

Specifying multiple project roots could work. Or... could additional project roots just be inferred from the application's Gemfile? An engine is included in the app like `gem 'monkeybutt', path: 'monkeybutt'`. Would it be reasonable to assume that any gem with a relative path under the Rails root should be added to the list of project roots?

**Comment by fikus** [comment]
It looks like you can use `config.app_dirs_pattern` to configure this and include your engine directories in the app stack trace. See https://github.com/getsentry/raven-ruby/blob/master/lib/raven/backtrace.rb#L69-L81.

**Comment by wyattisimo** [comment]
@fikus I think including an engine wholesale would be undesirable because engines have directory structure complexity similar to that of the rails app in which they live. You'd want to apply those directory pattern matchers to each engine.

**Comment by nateberkopec** [comment]
Closing this for now. It's possible with `app_dirs_pattern`, although it will create a pretty big, unwieldy regex.

**Comment by nateberkopec** [comment]
> When I'm looking at stack traces in Sentry, it excludes paths in the engines when displaying "app only" lines.

I just realized this is a consequence of the load paths of the engines being added to LOAD_PATH, and that they are "longer" than the Rails root.

**Comment by nateberkopec** [comment]
Introduced at 2f00ca9a85c32ccf5c1b6

**Comment by st0012** [comment]
since the old SDK has been deprecated, this will be closed now. but feel free to open a new issue if you find a similar problem in the new SDK 🙂
