### ISSUE TITLE
Allow for multiple Raven clients with Rails integration.

### ISSUE THREAD

**Issue by sheki** [getsentry/sentry-ruby#649]
I would like to send Raven messages to multiple DSNs based on the controller name / or some config.

But the integration assumes only one raven client. 
Can I get a better way to integrate so that I can configure different raven-clients based on controllers.

**Comment by nateberkopec** [comment]
You can do this, we just have to document it.

You can have an unlimited amount of `Raven::Instance` objects, each which can have their own configuration (and thus DSN).

**Comment by nateberkopec** [comment]
OK, I just realized you actually can't do this, because the Rack middleware uses the global instance.

*If* you could provide a Raven instance to the Rack middleware, you could:

* Require Sentry without integrations. This will prevent the automatic Rack middleware injection.
* In each controller you want Sentry to watch, add a new Sentry::Rack middleware, providing a config and context object.

This is a big feature, so deferring to 3.0.

**Comment by pedrofurtado** [comment]
@nateberkopec Is this feature available? :+1:

**Comment by omgitsbillryan** [comment]
Welp - time for the yearly bump. I'm also interested in this feature.

**Comment by st0012** [comment]
hello 👋, I'm the current maintainer of this gem and because v3 has been released and this will be a structural change, we need to push this to the next major release (v4). will keep you posted here 😉

**Comment by st0012** [comment]
@sheki thanks for the long-waiting, but I have some good news here 😄 

if you migrate to the new `sentry-ruby` SDK, the [Scope & Hub structure](https://docs.sentry.io/platforms/ruby/enriching-events/scopes/) will allow you to do that. 

this is just a short example on how to initialize multiple hubs with different config objects:

```ruby
dsn_1 = "DSN_1"
dsn_2 = "DSN_2"

config_1 = Sentry::Configuration.new.tap { |config| config.dsn = dsn_1 }
config_2 = Sentry::Configuration.new.tap { |config| config.dsn = dsn_2 }

hub_1 = Sentry::Hub.new(Sentry::Client.new(config_1), Sentry::Scope.new)
hub_2 = Sentry::Hub.new(Sentry::Client.new(config_2), Sentry::Scope.new)

hub_1.capture_message("message to DSN 1") #=> will be sent to DSN_1
hub_2.capture_message("message to DSN 2") #=> will be sent to DSN_2
```

I'm closing this now, but feel free to reopen it if you still have questions 🙂

**Comment by sandstrom** [comment]
@st0012 Great comment above! 🎉 

1. It's two years old though, are there any up-to-date documentation on how to manage to "Sentry clients" (two hubs) in the same Ruby application?
    
    I check the example folder, but couldn't find any.
    
    It's great that the capability exists, but a bit more documentation around it would be super-useful! 😄 

2. I'm guessing it's broadly this logic we want to replicate, right?
    
    https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry-ruby.rb#L209-L255
