### ISSUE TITLE
Don't read in entire request body

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#706]
This is not good: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L85 and will be very slow if the request body is large.

Also we will probably remove it from the event anyway.

**Comment by dentarg** [comment]
> This is not good: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L85 and will be very slow if the request body is large.

Code has been moved around since the above was written, but I think it linked to this line: https://github.com/getsentry/raven-ruby/blob/884998d35edeed29d4fe49519d611d56936058a7/lib/raven/integrations/rack.rb#L85

**Comment by nateberkopec** [comment]
Adding a bug label because this can also cause events to be rejected for being too large.

**Comment by Davidslv** [comment]
@nateberkopec I'm wondering if the request can't be streamed?

**Comment by st0012** [comment]
I think this is not an issue anymore. Sentry now trims long data on the server side instead of rejecting the event.

<img width="80%" alt="截圖 2021-07-01 下午5 35 50" src="https://user-images.githubusercontent.com/5079556/124102283-caf3fc80-da92-11eb-8a51-1e301f9d684e.png">
