### ISSUE TITLE
Pre/post send hooks

### ISSUE THREAD

**Issue by tijmenb** [getsentry/sentry-ruby#737]
We're looking to configure the client to send some things to statsd, so we can use our existing infrastructure to graph errors reported to Sentry. 

We'll probably configure `transport_failure_callback` for this, but it seems there's no place to hook into a successful error report. Is that intentional, and if not, would a PR to add this functionality be considered?

I'm thinking of a callback like [`transport_failure_callback`][cb]:

```ruby
# Optional Proc, called before sending the error to Sentry
# E.g. lambda { |event| $statsd.incr('sentry.errors_reported') }
attr_reader :before_send_callback
```

[cb]: https://github.com/getsentry/raven-ruby/blob/6a946c4da2de2a2777f0b6c1334956389daaf5dd/lib/raven/configuration.rb#L153-L155

**Comment by nateberkopec** [comment]
This is actually on the official "SDK feature list" now, so yeah, we should definitely have this.

**Comment by cantino** [comment]
Is there any recommended way to do this?

**Comment by cantino** [comment]
Would it be safe to use the `async` hook for this?

```ruby
config.async = lambda { |event|
  # Run pre-send hook
  Raven.send_event(event)
  # Run post-send hook
}
```

**Comment by st0012** [comment]
@tijmenb we provide the `config.before_send` option for this purpose. can you give it a try? 

```ruby
config.before_send = lambda do |event, hint|
  event[:message] = 'a'
  event
end
```

**Comment by st0012** [comment]
closing now, but feel free to reopen it if it's still an issue.
