### ISSUE TITLE
Buffer to disk

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#745]
Ability to write events to disk when network (or Sentry) is down and replay them later.

**Comment by st0012** [comment]
> Write events to disk before attempting to send, so that they can be retried in the event of a temporary network failure. Needs to implement a cap on the number of stored events.

> This is mostly useful on mobile clients where connectivity is often not available.

@rhcarvalho based on the document, I think this is for mobile SDKs? and AFAIK, the current server side SDK practice is to drop the event when failed to avoid flooding users' disk?

**Comment by rhcarvalho** [comment]
Right, disk buffer is not part of most SDKs, and when it is I think the fundamental reason to have it is to be able to report events after a crash (for example, mobile apps), and not to retry failed requests.
Such kind of feature could escalate to distributed system problems (https://en.wikipedia.org/wiki/Thundering_herd_problem, https://en.wikipedia.org/wiki/TCP_global_synchronization).

**Comment by st0012** [comment]
@rhcarvalho thanks for quick response and the references 👍 
I'll close this then.
