### ISSUE TITLE
Lazy context

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#747]
Ability to add functions that are run at event-build time and are able to read the current Context. The purpose is to be able to do things lazily only when an event is being sent, for example look up the current user from the session and set the username on the event (which may be expensive).

**Comment by hc2p** [comment]
Has this enhancement been considered at all yet? 
I would like to have that functionality as well.

**Comment by magni-** [comment]
@st0012 where is this feature documented?

**Comment by st0012** [comment]
@magni- this has never been implemented so there's no documentation for it. if you think it's still relevant, feel free to open a new issue and propose it with more detail :-)
