### ISSUE TITLE
extra_context ignored in rack / grape app

### ISSUE THREAD

**Issue by travisp** [getsentry/sentry-ruby#777]
We're using Grape API (https://github.com/ruby-grape/grape) inside of Rails and setup sentry for our apps. We followed the setup here: https://github.com/getsentry/raven-ruby/issues/373

In a grape before block we have,
```
    before do
      Raven.extra_context(
        params: params.to_hash,
        url: request.url,
        declared_client: request.headers['User-Agent']
      )
    end
```

However when we `capture_exception` in grape for errors that occur (we do this because we gracefully handle many exceptions), this extra context never gets passed to Sentry. I'm unsure if this is a bug in Sentry, or a problem with what we're doing

**Comment by nateberkopec** [comment]
I don't know how to use Grape. Can you please modify [this script](https://gist.github.com/nateberkopec/030581ead896bbb8f5ccbc5b961929c7) to get a reproduction?

**Comment by travisp** [comment]
@nateberkopec here you go https://gist.github.com/travisp/044b9e296229f90f5bc3d274414db45b

The problem seems to be that Raven::Rack.call actually captures the exception before Grape's `rescue_all` (triggering it more than expected -- which I missed previously), and then calls `Context.clear!` when it re-raises the exception and sends it to `rescue_all`.

The same issue happens if I don't disable the automatic integrations, don't use `use Raven::Rack` and reliable on the rails integration.

The desired behavior would be to capture the exception in Grape _first_, which would also let us decide not to re-raise the exception to Raven::Rack if we wanted. I'm not sure where the appropriate place to get this working is, or if there's a change I can make myself.

**Comment by nateberkopec** [comment]
I think this test is invalid:

```ruby
def test_has_middleware
    assert_includes app.middleware, Raven::Rack
  end
```

App in this context is the Rails application. You added the middleware to the Grape rack app, not the Rails one, so of course this test will fail.

I think something's wrong with your Grape app as well, because:

```ruby
def test_hello
    get "/hello"
    assert last_response.ok?
  end
```

...also fails.

**Comment by travisp** [comment]
That was the setup in https://github.com/getsentry/raven-ruby/issues/373 but I'll update the test

**Comment by travisp** [comment]
OK, I've updated the gist https://gist.github.com/travisp/044b9e296229f90f5bc3d274414db45b so that test_hello works at least. I do not know an appropriate replacement test for test_has_middleware, but you can still see the particular issue that is happening `Raven.client.transport.events.size` is 2 not 1 because the rescue_from is entered after rack clears the context.

**Comment by travisp** [comment]
@nateberkopec I was able to get the exception capturing to work as expected in this gist https://gist.github.com/travisp/f7500dbe6307cad4d8551352f47f8ed8 by replacing `use Raven::Rack` with `insert_before 0, Raven::Rack`
