### ISSUE TITLE
Track network requests as breadcrumbs

### ISSUE THREAD

**Issue by seanlinsley** [getsentry/sentry-ruby#778]
Particularly for background jobs, it would be really useful to know what inline network requests were performed and what the response code was. Here's an example implementation in Skylight: [[link]](https://github.com/skylightio/skylight-ruby/blob/aef7946b9b90e80f6d9529dfa6563afc15ba6d4d/lib/skylight/probes/net_http.rb).

If this seems like something that belongs in the main repo, I'd be interested in writing it.

**Comment by nateberkopec** [comment]
Big thumbs up from me, sounds like a great idea.
