### ISSUE TITLE
Event creation with no automatically set attributes

### ISSUE THREAD

**Issue by cyrilchampier** [getsentry/sentry-ruby#780]
Hi,
I am trying to remove all automatically added context and tags when I use Event.from_message.
I am reporting very specific issues thanks to this code:
```
      event = Raven::Event.from_message(message, build_arguments(test, try_count))
      Raven::Client.new(config).send_event(event)
```

And in my generated sentry entries, I get informations that flood the ones I set in build_arguments:
server, url, params, etc.

Is there a way to disable all this automatic stuff ?

**Comment by nateberkopec** [comment]
Hm, not easily, no.

The only thing I can think of would be to manually set everything except the message to `nil` in a `should_send` hook:

```ruby
Raven.configure do |config|
  config.should_send = Proc.new { |event| event.server = nil; true } # etc etc, note that the block must return true for the event to actually be sent
end
```

**Comment by cyrilchampier** [comment]
hope there will be a configuration for that in the futur, thank anyway for your response

**Comment by nateberkopec** [comment]
I think a reasonable thing for us to would be to make Raven::Event.new *not* initialize a lot of this basic state but put that in a separate method. Then you could use Raven::Event.new directly if you wanted a barebones Event object to do with as you want.

**Comment by cyrilchampier** [comment]
I find `config.add_automatic_stuff = false` even more explicit, but I would take any way to do that :)

**Comment by nateberkopec** [comment]
I don't really want to add a config point here, because I don't think removing this information is useful in most cases. I suspect it would be misused too often. It's easier for us to just make our own Event APIs more composable/reusable.

**Comment by st0012** [comment]
@cyrilchampier if you migrated to the new SDK `sentry-ruby`, you'll be able to do something like:

```ruby
Sentry.with_scope do |temp_scope|
  temp_scope.clear
  temp_scope.set_contexts({}) # if you don't even want information about os, runtime...etc.
  Sentry.capture_message("completely clean message")
end
Sentry.capture_message("message that still contains contexts and tags")
```

I hope this helps solve your issue. I'm closing this for now, but feel free to reopen it if the above example doesn't work for you 🙂
