### ISSUE TITLE
Raven::Rails::ActiveJobExtensions not working correctly

### ISSUE THREAD

**Issue by dennisvandehoef** [getsentry/sentry-ruby#792]
Hi,

I have A problem with Raven::Rails::ActiveJobExtensions, it seems to be the call to the method [rescue_with_handler](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails/active_job.rb#L20) also raises an error.

Overwriting this method, to a version with a rescue, fixes the problem.
I also found out I need to add a sleep of at least one second to make it work.

```ruby
class ApplicationJob < ActiveJob::Base
  def rescue_with_handler(exception)
    return super
  rescue
    sleep(1) # without this sleep, the error gets not posted
    false
  end
end
```

Is this a bug, or am I doing something wrong?
Using the 2.7.1 version of the gem, rails 5.0.1

**Comment by nateberkopec** [comment]
Hm. That's interesting. Obviously I didn't plan for that!

Should be easy to write a test for.

**Comment by nateberkopec** [comment]
I can't quite repro this. An exception in a `rescue_from` block seems to just cause nothing to happen (the original exception is still captured).
