### ISSUE TITLE
Rails params.to_unsafe_h has side effects

### ISSUE THREAD

**Issue by rpechayr** [getsentry/sentry-ruby#799]
Hello, we recently migrated to sentry using this gem. We basically followed this guide here: 

https://github.com/getsentry/raven-ruby/blob/master/docs/integrations/rails.rst

We then ran into a big issue when going to production. It turned out this was because calling `params.to_unsafe_h` actually mutates the `params` object, and we ended up having sub-params to be `ActionController::Params` instead of `ActiveSupport::HashWithIndifferentAccess`. This created a big bunch of `ActiveModel::ForbiddenAttributesError` in Sentry.

We'll probably use `params.dup.to_unsafe_h` instead.

**Comment by nateberkopec** [comment]
@rpechayr Can you write out some code that shows the behavior you're describing? I'm not sure I understand your example, specifically this part:

> we ended up having sub-params to be ActionController::Params instead of ActiveSupport::HashWithIndifferentAccess

Example:

```ruby
foo = ActionController::Parameters.new("foo"=>{"bar"=>["baz"]})
foo["foo"].class # ActionController::Parameters
qux = foo.to_unsafe_h
foo.object_id # 70115534341460
qux.object_id # 70115528299700
foo.class # ActionController::Parameters
foo["foo"].class # ActionController::Parameters
qux.class # ActiveSupport::HashWithIndifferentAccess
```

**Comment by rpechayr** [comment]
Sure @nateberkopec ! Here is some code : 
```ruby
foo = ActionController::Parameters.new({"param1"=>"", "elements"=>{"0"=>{"parent_id"=>"596dc5da45a800001e0012b4", "key"=>"0"}}})
foo[:elements].values.first.class #ActiveSupport::HashWithIndifferentAccess
foo.to_unsafe_h
foo[:elements].values.first.class # ActionController::Parameters
```
Of course this example is slightly different from yours ... 

Honestly, I would say it's a bug in ActiveSupport itself, but I've never discovered such a thing myself :). What I am sure of is that I can see a way to tweak your documentation in order to work around this behaviour. 

BTW, since I wrote the original issue, I shipped the `params.dup.to_unsafe_h` hack to production and so far so good.

**Comment by rpechayr** [comment]
Oh ! I'm using rails 4.2.7.1

**Comment by kul1** [comment]
I have same issue using Rails 5.1.6

**Comment by st0012** [comment]
The new SDK's doc doesn't encourage such usage anymore, so closing now.
