### ISSUE TITLE
Raven::Instance#capture_type memory leak

### ISSUE THREAD

**Issue by kryali** [getsentry/sentry-ruby#805]
Hey, I believe there's a memory leak in Raven on this [line here](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/instance.rb#L128). As I understand, nothing will clean up these thread variables. Let me know if I misunderstood anything. 

Consider this example & reproduction below.

```
2.3.6 :001 > Thread.current.keys.select {|x| x.to_s.include?("sentry")}
 => []
2.3.6 :002 > Raven::CLI.test(dsn)
 => true
2.3.6 :003 > Thread.current.keys.select {|x| x.to_s.include?("sentry")}
 => [:sentry_context, :sentry_breadcrumbs, :sentry_70244520082880_last_event_id]
2.3.6 :004 > Raven::CLI.test(dsn)
 => true
2.3.6 :005 > Thread.current.keys.select {|x| x.to_s.include?("sentry")}
 => [:sentry_context, :sentry_breadcrumbs, :sentry_70244520082880_last_event_id, :sentry_70244513342000_last_event_id]
```

**Comment by nateberkopec** [comment]
The object_id in `:sentry_70244520082880_last_event_id` is the object id of the Raven::Instance. Raven::CLI.test creates a new client every time it is run. This is fine, because it's usually run once in a rake process and then shuts down. 

In ordinary usage, `Raven.capture_exception` and similar all use the same Raven::Instance. No one should be creating Raven::Instances and not reuse them, so this is not a leak in normal usage.

**Comment by nateberkopec** [comment]
I'm trying to think of a way to just make this not possible anyway, all I can think of is a finalizer:

```ruby
  def initialize(context = nil, config = nil)
      @context = @explicit_context = context
      self.configuration = config || Configuration.new
      ObjectSpace.define_finalizer( self, self.class.finalize(name) )
    end

    def self.finalize(name)
      proc { Thread.current["sentry_#{object_id}_last_event_id".to_sym] = nil }
    end
```

**Comment by kryali** [comment]
Ah I see, this is probably not a huge deal then.

**Comment by nateberkopec** [comment]
Reopening, deciding I want to fix it anyway.

**Comment by nateberkopec** [comment]
Delaying until next bugfix release because I want to investigate other threading issues, e.g. re-use of Raven.instance across threads.

**Comment by st0012** [comment]
since the old SDK has been deprecated, this will be closed now. but feel free to open a new issue if you find a similar problem in the new SDK 🙂
