### ISSUE TITLE
Allow configuring certain gems to be in-app

### ISSUE THREAD

**Issue by schneidmaster** [getsentry/sentry-ruby#808]
Hi there -- recently I had to sort out how to get Sentry to consider a few gems to be a part of the main Rails application. `app_dirs_pattern` wasn't of help because paths also have to be under the project root to be considered in-app, and our gems live in a different shared directory. I ended up monkey-patching as follows:

```ruby
module Raven
  class Backtrace
    class Line
      APP_GEMS = %w[
        my-gem-one
        my-gem-two
      ].freeze

      def in_app
        if file =~ self.class.in_app_pattern || APP_GEMS.any? { |gem_name| file.include?(gem_name) }
          true
        else
          false
        end
      end
    end
  end
end
```

It would be nice if I didn't need the monkey patch and I could just do something like:

```ruby
Raven.configure do |config|
  config.app_gems = %w[my-gem-one my-gem-two]
end
```

Figured I'd open an issue to see if this has come up. I don't mind sending a PR to implement if y'all agree this would be a useful config option.

**Comment by nateberkopec** [comment]
Thanks for the request. I've been thinking a lot about how to improve this feature lately.

In general, the story is that:

> also have to be under the project root to be considered in-app

... causes problems for some people. I *really don't like* how we have used $LOAD_PATH in the past here as well. 

I'm not a huge fan of your proposed solution because the gem has too many config attributes as it is, so I would like to remove or modify existing ones to satisfy this request.

**Comment by schneidmaster** [comment]
Makes sense to me. I'm not particularly opinionated about the nature of the solution, just raising it as a configuration need that I can currently only accomplish with monkey-patching. Thanks for the response 🙂

**Comment by iker-barriocanal** [comment]
Closing this issue due to staleness. Feel free to comment here if you're using the latest version and still think we should work on this.

Thanks!
