### ISSUE TITLE
What's the best way to provide extra_context for all Faraday::Error::ClientError?

### ISSUE THREAD

**Issue by dblock** [getsentry/sentry-ruby#814]
Coming from https://github.com/artsy/doppler/issues/136. Somewhere a Rails controller throws a `Faraday::Error::ClientError`. That gets logged with a generic `to_s` like "The server returned 400". We want the body of that response in Sentry.

What's the best way to accomplish that (customize what gets reported per type of StandardError) generically in a Rails app?

**Comment by nateberkopec** [comment]
Hiya @dblock!

The rescue_from block you posted in your issue there would work fine. You also sound like you might like this:

```ruby
class Faraday::Error::ClientError
  def raven_context
    { :extra => { :response => response } } 
  end
end
```

[See here](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/event.rb#L49).

**Comment by isaacseymour** [comment]
@nateberkopec would you be open to a PR doing this monkey-patching when this gem loads? Since sentry-raven depends on Faraday anyway, it seems helpful to add this context out-of-the-box to me.

**Comment by dblock** [comment]
+1 to what @isaacseymour is saying

**Comment by nateberkopec** [comment]
Hi, I don't maintain this anymore. I should probably remove my own owner status on rubygems.org too! 😅

**Comment by st0012** [comment]
`sentry-raven` is now in maintenance mode, so we won't introduce such change to it.
The new `sentry-ruby` doesn't support exception context anymore and we're planning to drop `faraday` soon. So we won't add the patch to it either 🙂
