### ISSUE TITLE
Support/deal with DebugExceptions interceptors

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#826]
https://github.com/rails/rails/pull/23868/files

**Comment by st0012** [comment]
@nateberkopec wow this actually handles rescued exceptions more elegantly (no more patching needed). thanks for leaving this trace 👍

**Comment by st0012** [comment]
turns out it's added to Rails 6 only 🤦‍♂️

**Comment by sl0thentr0py** [comment]
@st0012 I believe we already handle this? can I close?

**Comment by st0012** [comment]
No we haven't handled this. But with the new exception reporter in Rails 7.0+, I also won't proceed on this one anymore.
So I'll close it as not planned.
