### ISSUE TITLE
upgrading raven makes rails stdout logging no longer work

### ISSUE THREAD

**Issue by atambo** [getsentry/sentry-ruby#831]
When I upgrade `sentry-raven` from `2.3.0` to `2.7.2` and then run `bundle exec rails s` I no longer see rails console output in my terminal. Are there some new configuration settings or something I need to set to make my development logging work again?

**Comment by atambo** [comment]
My guess it is related to this change:



FEATURE: raven-ruby now marks itself as the "ruby" logger by default, to match raven-js behavior [@nateberkopec]

**Comment by st0012** [comment]
@atambo does this still happen in the `3.0+` versions?

**Comment by st0012** [comment]
since the old SDK has been deprecated, this will be closed now. but feel free to open a new issue if you find a similar problem in the new SDK 🙂
