### ISSUE TITLE
Corrupted data at the fourth level of request body (maybe somewhere else)

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry-ruby#839]
Hello!

What happened to the data at the fourth level of nesting?

Especially with non-ASCII (Cyrillic).

![image](https://user-images.githubusercontent.com/6510020/40610906-dcf0532a-627c-11e8-95dc-39d4038392ac.png)

In the event file:

```json
		"data": {
			"fff": {
				"ggg": {
					"hhh": "iii"
				}
			},
			"ooo": {
				"ppp": {
					"qqq": {
						"rrr": "\"u'\\\\u0430\\\\u0431\\\\u0432'\""
					}
				}
			},
			"aaa": "bbb",
			"jjj": {
				"kkk": {
					"lll": {
						"mmm": "\"u'nnn'\""
					}
				}
			},
			"ccc": {
				"ddd": "eee"
			}
		},
```

Code of request: 

```ruby
HTTP.post('http://localhost:3000/en/test', body: "aaa=bbb&ccc[ddd]=eee&&fff[ggg][hhh]=iii&jjj[kkk][lll][mmm]=nnn&ooo[ppp][qqq][rrr]=абв")
```

**Sentry 8.22.0** (Docker), **sentry-raven 2.7.3**.

**Comment by nateberkopec** [comment]
I'll take a look. In the meantime, if you could turn this: https://gist.github.com/nateberkopec/0c17bb4a96114490b00ac9cca14d37a7

into a reproduction, that would be helpful.

**Comment by AlexWayfer** [comment]
@nateberkopec yeah, sure. I'm on vacation now, will do this in the first July.

**Comment by st0012** [comment]
@AlexWayfer not sure if this is still an issue to you? I'm closing it now but feel free to reopen it if you can still reproduce the problem.
