### ISSUE TITLE
2.7.3 possibly broke Activejob with Sidekiq

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#850]

**Comment by jacquescrocker** [comment]
Context: 2.7.3 is not sending ActiveJob parameters when reporting errors to Sentry. Testing on 2.7.2 to see if the issue persists there

**Comment by jacquescrocker** [comment]
Ok, I've confirmed version 2.7.2 of the gem does send the arguments correctly:

On 2.7.2 (arguments)
![screen shot 2018-06-20 at 4 18 05 pm](https://user-images.githubusercontent.com/206662/41689466-904056ca-74a5-11e8-815a-d3001cc9bc76.png)

On 2.7.3 (no arguments)
![screen shot 2018-06-20 at 4 19 24 pm](https://user-images.githubusercontent.com/206662/41689503-ba275a24-74a5-11e8-916b-8fb92aeff3cc.png)
