### ISSUE TITLE
Sanitize cookies

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry-ruby#863]
Hello!

I want to send cookies to Sentry, but sanitize some by keys.

Thank you.

**Comment by AlexWayfer** [comment]
> This would require a custom processor. I think you could do it by looking at some combination of the existing SanitizeData processor and then some code that turns cookies into a hash and then back into cookies again.

Why should it not be a part of `SanitizeData` processor?

**Comment by nateberkopec** [comment]
Sure, I could accept a PR to that effect. The default will always be to just not send any, though.

**Comment by AlexWayfer** [comment]
> The default will always be to just not send any, though.

Why not by field names, as for other data?

**Comment by nateberkopec** [comment]
Cookies are almost solely used to store PII or user authentication data. Exactly the kinds of stuff most people don't want to send to Sentry. Same reason we scrub POST bodies. 

It's easy enough to turn back on if you don't feel that applies to you.

**Comment by AlexWayfer** [comment]
> Cookies are almost solely used to store PII or user authentication data. Exactly the kinds of stuff most people don't want to send to Sentry. Same reason we scrub POST bodies.

I think there should be two different issues (tasks): 
1. Create new processor for removing cookies from sending data, like `PostData`.
2. Add cookies processing into existing `SanitizeData` processor.

I created this issue about the last one. I'm not interested about removing cookies at all (I'm disabling `PostData` processor in our projects).

**Comment by nateberkopec** [comment]
[1 is already done, that's how it works today.](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/processor/cookies.rb)

For 2, I think now even I'm confused about cookies are represented in our events. I'm going to have to look into this, maybe it's easier than I thought.

**Comment by st0012** [comment]
because the new SDK (`sentry-ruby`) has removed data sanitization functionality with a [new data scrubbing strategy](https://docs.sentry.io/platforms/ruby/data-management/sensitive-data/) (like other languages' SDKs), we will close this issue for now.
