### ISSUE TITLE
runtime-dyno-metadata

### ISSUE THREAD

**Issue by leastbad** [getsentry/sentry-ruby#864]
I keep getting warnings from Raven:

> [Raven] You are running on Heroku but haven't enabled Dyno Metadata. For Sentry's release detection to work correctly, please run `heroku labs:enable runtime-dyno-metadata`

When I run `heroku labs` I can verify that runtime-dyno-metadata is enabled.

Running Rails 5.2.0 and Ruby 2.4.1

**Comment by nateberkopec** [comment]
Are you pushing releases using the Releases API?

**Comment by nateberkopec** [comment]
![screen shot 2018-09-18 at 10 33 36 am](https://user-images.githubusercontent.com/845662/45702160-51cbca80-bb2e-11e8-85fa-ebd774051766.png) Guess I'm going to have to come up with another approach :(

**Comment by pjforde1978** [comment]
I admit that I'm new to Sentry and I'm fuzzy on what this would mean. I am using a pretty stock setup.

in my Application controller, inside of a before_action block:
```
Raven.user_context(id: current_user.try(:id), username: current_user.try(:username), email: current_user.try(:email))
Raven.extra_context(params: params.to_unsafe_h, url: request.url)
```
My sentry.rb initializer is also super vanilla:

```
Raven.configure do |config|
  config.current_environment = ENV['ENVIRONMENT']
  config.dsn = ENV['SENTRY'] if Rails.env.production?
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
end
```

Is there something specific that I could check?

**Comment by nateberkopec** [comment]
Sorry, I meant *Heroku's* release API, not Sentry's.

**Comment by pjforde1978** [comment]
All of my deploys happen via `git push` commands, with the possible exception of the occasional rollback via Heroku's web interface.

**Comment by nateberkopec** [comment]
@pjforde1978 Could you kindly either post or email to me (nate@getsentry.io):

* Output of `heroku labs --app <your-app-name>`
* Get a bash console with `heroku run bash --app <your-app-name>`, then paste me the output of `env | grep HEROKU_APP` and `env | grep HEROKU_SLUG`

**Comment by pjforde1978** [comment]
It seems as though your domain is having a rough day...

![sentry](https://user-images.githubusercontent.com/38150464/45722705-a47fa380-bb7b-11e8-9949-c73608a0818c.jpg)

**Comment by nateberkopec** [comment]
Whoops, my bad. Our mail is on sentry.io now. Please email to nate@sentry.io.

**Comment by andyjeffries** [comment]
What do we need to do now that this lab no longer exists?

```
$ heroku labs:enable runtime-dyno-metadata
 ▸    Couldn't find that feature.
```

**Comment by knittingarch** [comment]
@andyjeffries I'm in the same boat.  Were you able to find a solution to this?

**Comment by dentarg** [comment]
@andyjeffries @knittingarch did you try the command with the `--app` flag?

https://devcenter.heroku.com/articles/dyno-metadata still works for me

```
$ heroku labs:info runtime-dyno-metadata
 ▸    Couldn't find that feature.

$ heroku labs:info runtime-dyno-metadata --app <app name>
=== runtime-dyno-metadata
Description: Share dyno metadata in environment variables
Docs:        https://devcenter.heroku.com/articles/dyno-metadata
Enabled:     true
```
