### ISSUE TITLE
Change protocol version to 7

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry-ruby#867]

**Comment by st0012** [comment]
The `protocol` is barely used and basically irrelevant right now. So the change won't be necessary.

**Comment by rhcarvalho** [comment]
I've just noticed this in code, was going to open an issue then found this.
Need to check with the rest of the team what the version is used for, but we should probably be reporting something consistent if we want to ever be able to enforce versioning. For instance, the server could ignore datatypes non-existing in version 5 (for example transactions).

**Comment by rhcarvalho** [comment]
Talked with the rest of the SDK team. Heard that the ingestion pipeline goes through different code paths depending on version, so considering all modern SDKs are on v7, we should update the Ruby SDK to use 7 too.
