### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry-ruby#870]
How not to send packages?

![image](https://user-images.githubusercontent.com/6510020/46418908-5e0e7500-c735-11e8-9ce5-1488a5b78757.png)

Also, we have a strange processing there:

![image](https://user-images.githubusercontent.com/6510020/46418964-81d1bb00-c735-11e8-9f4c-97082efaacf7.png)

**Comment by uxxman** [comment]
I also looking for this.

**Comment by st0012** [comment]
I think you can disable it with:

```ruby
config.send_modules = false
```

closing for now, feel free to reopen it if the config doesn't work 🙂
