### ISSUE TITLE
Clockwork integration

### ISSUE THREAD

**Issue by vassilevsky** [getsentry/sentry-ruby#880]
Hi 🙃

Right now Raven does not automatically capture errors in Clockwork tasks.

Clockwork now has a pretty neat error handling method:

https://github.com/Rykian/clockwork#error_handler

Would you be interested in a PR to plug into Clockwork by default?

**Comment by smit1625** [comment]
Hey there, found this thread while searching for a way to make Raven report on Clockwork, and ended up adding this to my clock.rb to resolve the issue until this hopefully gets added.

```ruby
module Clockwork
  # ...
  error_handler { |error| Raven.capture_exception(error) if defined? Raven }
  # ...
end
```

**Comment by st0012** [comment]
@vassilevsky thanks for the suggestion, but we're not planning to introduce any integration with `Clockwork` right now 🙂
