### ISSUE TITLE
Automatically add request_id tag

### ISSUE THREAD

**Issue by tilsammans** [getsentry/sentry-ruby#891]
The Python library now detects and tags a request id. This technique was recently [in the Sentry blog](https://blog.sentry.io/2019/01/31/using-nginx-sentry-trace-errors-logs)

Seems like a good addition for Rails too. Need a pull request?

**Comment by IvanChou** [comment]
I need this, too

**Comment by st0012** [comment]
this has been added in #1120 so closing now
