### ISSUE TITLE
Send timeout triggered by filtered events

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-ruby#894]
Currently, if an event triggers any of Sentry's server-side filters (like the web crawler filter, for instance), it kicks the ruby SDK into timeout mode, because a filtering error is treated the same way as, say, a rate limit error. Future legit errors therefore get blocked. Compounding the problem, the timeout never ends unless the SDK is entirely idle for 36 seconds. (See the related issue [here](https://github.com/getsentry/raven-ruby/issues/841).)

Other SDK's don't go to timeout mode in response to filtered events. Let's make this configurable, at minimum, or take out the behavior entirely.

**Comment by st0012** [comment]
@lobsterkatie can you try `3.0.x` versions to see if this is still an issue? I think https://github.com/getsentry/raven-ruby/pull/886 has fixed the issue.
