### ISSUE TITLE
sanitizedata credit card regex is matching fields that are not credit cards

### ISSUE THREAD

**Issue by alxyuu** [getsentry/sentry-ruby#905]
We are trying to include fullstory urls in our error reports, and they are erroneously getting scrubbed by the credit card sanitizer because the url will sometimes contain numbers are similar to a credit card number.

Would it be possible to have some more control over this without flat out disabling credit card sanitization? Perhaps if it respected configuration.sanitize_fields_excluded, which it currently does not?

**Comment by st0012** [comment]
because the new SDK (`sentry-ruby`) has removed data sanitization functionality with a [new data scrubbing strategy](https://docs.sentry.io/platforms/ruby/data-management/sensitive-data/) (like other languages' SDKs), we will close this issue for now.
