### ISSUE TITLE
Raven.tags_context is not working - I don't see any tags in my Sentry errors

### ISSUE THREAD

**Issue by ndbroadbent** [getsentry/sentry-ruby#918]
I'm trying to send some extra tags with my Sentry error reports, but they aren't showing up in Sentry. I set up the Sentry config in a file at `config/initializers/sentry.rb`:

```ruby
  Raven.tags_context(
    region: ENV['REGION'],
    domain: ENV['DOMAIN_NAME'],
    service: Sidekiq.server? ? :worker : :web
  )
```

These tags aren't showing up for either Sidekiq jobs, nor for controller actions:

<img width="1104" alt="Screen Shot 2019-09-17 at 3 23 35 PM" src="https://user-images.githubusercontent.com/139536/65024563-50122e00-d95f-11e9-97d7-1cf05d8cfcd6.png">

Should I be calling `Raven.tags_context` somewhere else, or I am doing this wrong? Thanks!

**Comment by grncdr** [comment]
We have very similar code in the same initializer file and also don't see any tags in Sentry itself.

We are using Rails 5 + Unicorn, is that the same for you @ndbroadbent ?

**Comment by mattmcf** [comment]
We are also seeing issues where a block defined with `.tags_context` and `.extra_context` is not tagging the events.

```
def with_error_context(&block)
  Raven.tags_context("organization_id" => @organization.id) do
    Raven.extra_context("descriptoin" => @organization.description, &block)
  end
end

**Comment by st0012** [comment]
@ndbroadbent `Raven.tags_context` is meant to be used like

```ruby
Raven.tags_context(interesting: 'yes') do
  # the `interesting: 'yes'` tag will only present in the requests sent inside the block
  Raven.capture_exception(exception)
end
```

If you want to add tags globally, try:

```ruby
    Raven.configure do |config|
      config.tags.merge!(foo: "bar")
    end
```
