### ISSUE TITLE
Support Resque as a job backend

### ISSUE THREAD

**Issue by mbianco-stripe** [getsentry/sentry-ruby#919]
Curious if there's interest in support Resque natively within the gem. There's https://github.com/gocardless/resque-sentry but it hasn't been updated in a while, it would be great to have this built-in to this gem.

Thoughts? I may be able to create a PR for this if there is interest.

**Comment by st0012** [comment]
@mbianco-stripe I think it'd be great if we can have a resque integration as well. are you still interested in open a PR for it?

**Comment by iloveitaly** [comment]
I'd love to contribute here, but I don't have the time anymore to invest in this. Hopefully someone else can pick up the flag!

**Comment by berniechiu** [comment]
I can look into this since lots of people use Resque~

**Comment by st0012** [comment]
@berniechiu that'll be great! but because we're building the 4.0 version and every integration will be a standalone gem (`sentry-resque` in this case). so maybe you may want to wait for the 4.0 to come out first?

**Comment by berniechiu** [comment]
That sounds more modular, looking forward to it. I'll wait for it then 😁

**Comment by st0012** [comment]
@berniechiu the SDK is now in beta so we can start building other extensions around it 😄 are you still interested in this task? (`sentry-resque`). of course, I'll give you instructions on how to write an extension for the new SDK 😉

**Comment by berniechiu** [comment]
sure, where can I look into it

**Comment by st0012** [comment]
@berniechiu sorry for the delay 😓 
here's a [simple document](https://github.com/getsentry/sentry-ruby/blob/master/EXTENSION.md) on how to write an extension. you can use both `sentry-rails` and `sentry-sidekiq` as an example for the work. let me know if you have any questions.

**Comment by berniechiu** [comment]
Thanks for the good documentation, I'll take a look~

**Comment by st0012** [comment]
@berniechiu have you started the implementation yet? 😄  if you haven't and you don't plan to start it recently, I'll start working on this.

**Comment by st0012** [comment]
I've listed `sentry-resque` in #1369. so closing now
