### ISSUE TITLE
Config as production but sent sentry as staging env?

### ISSUE THREAD

**Issue by gamesover** [getsentry/sentry-ruby#929]
Hi, my current rails project hosted in heroku is staging. However, according to heroku's recommandation, there is no seperate staging env config in my project. So all info are the same as production. As a result, when exception throw out, I still hope they sent to sentry as staging errors, not production errors.

How to do that?

**Comment by st0012** [comment]
@gamesover sorry for the delayed response. is it still troubling you?

**Comment by pil0u** [comment]
For @gamesover (2.5 years later :hourglass:) and others who might encounter this problem, here is my workaround.

1. I set a new environment variable `HEROKU_PIPELINE_STEP` in Heroku's configuration, which value can be `review` (for my Review Apps), `staging` or `production`
2. I use the following configuration in Rails, in my `config/initializers/sentry.rb` file:
```
config.environment = ENV["HEROKU_PIPELINE_STEP"] || ENV["RAILS_ENV"]
```
That way, you can separate these environments in your Sentry monitoring, thus having `staging` errors in the correct staging environment.

If you don't set the `HEROKU_PIPELINE_STEP` variable, it just fall backs to the default behaviour: getting the `RAILS_ENV` (which can be indeed impractical if you follow Heroku's guidelines to use `RAILS_ENV=production` for all your apps).

Note that as @jonekdahl mentioned in https://github.com/getsentry/sentry-ruby/issues/885, you (still) cannot run the `heroku labs:enable runtime-dyno-metadata -a <app_name>` command in Review Apps, so you will be stuck with Sentry's warning in Review Apps.

**Comment by st0012** [comment]
@pil0u thanks for the great suggestion 👍 
@gamesover I think @pil0u's comment is the best solution here and I recommend you to give it a try 🙂 
I'm going to close this now.
