### ISSUE TITLE
Raven.capture_exception(error) just returns false

### ISSUE THREAD

**Issue by 9mm** [getsentry/sentry-ruby#934]
I'm trying to capture messages inside the Que background gem.

This is my que.rb initializer file

```
# frozen_string_literal: true

Que.mode = :off
Que.worker_count = 1
Que.wake_interval = 1.0
Que.logger = Logger.new(STDOUT)
Que.use_prepared_statements = false # PGBouncer

Que.error_notifier = proc do |error, _job|
  binding.pry
  puts "XXXXXXXXXXXXXXXXXXXX #{error}, #{error.class}, #{Rails.env}"
  # THIS JUST RETURNS FALSE... yet error is the actual exception
  Raven.capture_exception(error)
end
```

I'm positive its enabled for development... so I don't know what is going on or how to send the exception.

**Comment by 9mm** [comment]
Bueller? Bueller?

**Comment by st0012** [comment]
If it captures an exception successfully, it should return a `Raven::Event` object. If it returns `false`, it means the SDK is not properly configured to capture exceptions. You can do

```ruby
  # .....
  Raven.capture_exception(error)
  puts(Raven.configuration.error_messages)
end
```

to see what's causing the issue.

**Comment by st0012** [comment]
closing now, but feel free to reopen it if you can still reproduce it in the new `sentry-ruby` SDK.
