### ISSUE TITLE
Display stacktrace when capturing not allowed

### ISSUE THREAD

**Issue by nate** [getsentry/sentry-ruby#942]
It would be nice if the backtrace was also logged when capturing is not allowed.

https://github.com/getsentry/raven-ruby/blob/065cf973cb0ad3672d0d213e80b6e8a9a8e6f8cb/lib/raven/instance.rb#L107

**Comment by st0012** [comment]
we generally don't swallow backtrace for errors regardless they're reported or not. for example, when using the SDK with Rails I can always see the backtrace from the log with/without a DSN set. so can you tell me how to reproduce the issue you're having? I think it might be something else that causes the issue. 

also, the old SDK has entered maintenance mode, so I encourage you to migrate to the new `sentry-ruby` SDK 😄 
(you can find the migration guide [here](https://docs.sentry.io/platforms/ruby/migration/))
